/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/i2c_ack_detector.v:1.1-33.10" *)
module i2c_ack_detector(scl, rst, ack_enable, sda, ack_received);
  wire _0_;
  (* src = "RTL/i2c_ack_detector.v:5.11-5.21" *)
  input ack_enable;
  wire ack_enable;
  (* src = "RTL/i2c_ack_detector.v:8.16-8.28" *)
  output ack_received;
  reg ack_received;
  (* src = "RTL/i2c_ack_detector.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_ack_detector.v:3.11-3.14" *)
  input scl;
  wire scl;
  (* src = "RTL/i2c_ack_detector.v:6.11-6.14" *)
  input sda;
  wire sda;
  (* src = "RTL/i2c_ack_detector.v:12.1-32.4" *)
  always @(posedge scl, posedge rst)
    if (rst) ack_received <= 1'h0;
    else if (ack_enable) ack_received <= _0_;
  assign _0_ = sda ? (* full_case = 32'd1 *) (* src = "RTL/i2c_ack_detector.v:25.12-25.23|RTL/i2c_ack_detector.v:25.9-29.34" *) 1'h0 : 1'h1;
endmodule
