/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\i2c_bit_counter" *)
(* src = "RTL/i2c_bit_counter.v:1.1-43.10" *)
module \$paramod\i2c_bit_counter\DATA_WIDTH=s32'00000000000000000000000000001000 (scl, rst, enable, done, bit_count);
  (* src = "RTL/i2c_bit_counter.v:12.1-42.4" *)
  wire _00_;
  (* src = "RTL/i2c_bit_counter.v:32.26-32.39" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _01_;
  (* src = "RTL/i2c_bit_counter.v:24.12-24.37" *)
  wire _02_;
  wire _03_;
  wire [2:0] _04_;
  (* src = "RTL/i2c_bit_counter.v:9.41-9.50" *)
  output [2:0] bit_count;
  reg [2:0] bit_count;
  (* src = "RTL/i2c_bit_counter.v:8.16-8.20" *)
  output done;
  reg done;
  (* src = "RTL/i2c_bit_counter.v:6.11-6.17" *)
  input enable;
  wire enable;
  (* src = "RTL/i2c_bit_counter.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_bit_counter.v:4.11-4.14" *)
  input scl;
  wire scl;
  assign _01_ = bit_count + (* src = "RTL/i2c_bit_counter.v:32.26-32.39" *) 32'd1;
  (* src = "RTL/i2c_bit_counter.v:12.1-42.4" *)
  always @(posedge scl, posedge rst)
    if (rst) bit_count <= 3'h0;
    else if (enable) bit_count <= _04_;
  assign _02_ = bit_count == (* src = "RTL/i2c_bit_counter.v:24.12-24.37" *) 3'h7;
  (* src = "RTL/i2c_bit_counter.v:12.1-42.4" *)
  always @(posedge scl, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _00_;
  assign _03_ = _02_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_bit_counter.v:24.12-24.37|RTL/i2c_bit_counter.v:24.9-34.12" *) 1'h1 : 1'h0;
  assign _00_ = enable ? (* full_case = 32'd1 *) (* src = "RTL/i2c_bit_counter.v:21.13-21.19|RTL/i2c_bit_counter.v:21.10-41.8" *) _03_ : 1'h0;
  assign _04_ = _02_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_bit_counter.v:24.12-24.37|RTL/i2c_bit_counter.v:24.9-34.12" *) 3'h0 : _01_[2:0];
endmodule

(* dynports =  1  *)
(* hdlname = "\\i2c_shift_register" *)
(* src = "RTL/i2c_shift_register.v:1.1-40.10" *)
module \$paramod\i2c_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000 (scl, rst, load, shift, data_in, sda, shift_reg);
  (* src = "RTL/i2c_shift_register.v:16.1-39.4" *)
  wire [7:0] _0_;
  wire _1_;
  wire [7:0] _2_;
  (* src = "RTL/i2c_shift_register.v:8.28-8.35" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "RTL/i2c_shift_register.v:6.11-6.15" *)
  input load;
  wire load;
  (* src = "RTL/i2c_shift_register.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_shift_register.v:4.11-4.14" *)
  input scl;
  wire scl;
  (* src = "RTL/i2c_shift_register.v:10.12-10.15" *)
  output sda;
  wire sda;
  (* src = "RTL/i2c_shift_register.v:7.11-7.16" *)
  input shift;
  wire shift;
  (* src = "RTL/i2c_shift_register.v:11.33-11.42" *)
  output [7:0] shift_reg;
  reg [7:0] shift_reg;
  (* src = "RTL/i2c_shift_register.v:16.1-39.4" *)
  always @(posedge scl, posedge rst)
    if (rst) shift_reg <= 8'h00;
    else if (_1_) shift_reg <= _0_;
  assign _1_ = | { shift, load };
  assign _2_ = shift ? (* src = "RTL/i2c_shift_register.v:33.13-33.18|RTL/i2c_shift_register.v:33.10-38.8" *) { shift_reg[6:0], 1'h0 } : 8'hxx;
  assign _0_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:26.13-26.17|RTL/i2c_shift_register.v:26.10-38.8" *) data_in : _2_;
  assign sda = shift_reg[7];
endmodule

(* src = "RTL/i2c_ack_detector.v:1.1-33.10" *)
module i2c_ack_detector(scl, rst, ack_enable, sda, ack_received);
  wire _0_;
  (* src = "RTL/i2c_ack_detector.v:5.11-5.21" *)
  input ack_enable;
  wire ack_enable;
  (* src = "RTL/i2c_ack_detector.v:8.16-8.28" *)
  output ack_received;
  reg ack_received;
  (* src = "RTL/i2c_ack_detector.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_ack_detector.v:3.11-3.14" *)
  input scl;
  wire scl;
  (* src = "RTL/i2c_ack_detector.v:6.11-6.14" *)
  input sda;
  wire sda;
  (* src = "RTL/i2c_ack_detector.v:12.1-32.4" *)
  always @(posedge scl, posedge rst)
    if (rst) ack_received <= 1'h0;
    else if (ack_enable) ack_received <= _0_;
  assign _0_ = sda ? (* full_case = 32'd1 *) (* src = "RTL/i2c_ack_detector.v:25.12-25.23|RTL/i2c_ack_detector.v:25.9-29.34" *) 1'h0 : 1'h1;
endmodule

(* src = "RTL/i2c_clock_generator.v:1.1-33.10" *)
module i2c_clock_generator(clk, rst, clk_divider, scl);
  (* src = "RTL/i2c_clock_generator.v:12.1-32.4" *)
  wire [15:0] _0_;
  (* src = "RTL/i2c_clock_generator.v:24.22-24.35" *)
  (* unused_bits = "16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _1_;
  (* src = "RTL/i2c_clock_generator.v:26.12-26.36" *)
  wire _2_;
  (* src = "RTL/i2c_clock_generator.v:29.20-29.24" *)
  wire _3_;
  (* src = "RTL/i2c_clock_generator.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_clock_generator.v:10.12-10.21" *)
  reg [15:0] clk_count;
  (* src = "RTL/i2c_clock_generator.v:5.18-5.29" *)
  input [15:0] clk_divider;
  wire [15:0] clk_divider;
  (* src = "RTL/i2c_clock_generator.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_clock_generator.v:7.16-7.19" *)
  output scl;
  reg scl;
  assign _1_ = clk_count + (* src = "RTL/i2c_clock_generator.v:24.22-24.35" *) 32'd1;
  (* src = "RTL/i2c_clock_generator.v:12.1-32.4" *)
  always @(posedge clk, posedge rst)
    if (rst) scl <= 1'h1;
    else if (_2_) scl <= _3_;
  assign _2_ = clk_count >= (* src = "RTL/i2c_clock_generator.v:26.12-26.36" *) clk_divider;
  assign _3_ = ~ (* src = "RTL/i2c_clock_generator.v:29.20-29.24" *) scl;
  (* src = "RTL/i2c_clock_generator.v:12.1-32.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count <= 16'h0000;
    else clk_count <= _0_;
  assign _0_ = _2_ ? (* src = "RTL/i2c_clock_generator.v:26.12-26.36|RTL/i2c_clock_generator.v:26.9-30.12" *) 16'h0000 : _1_[15:0];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/i2c_master.v:1.1-110.10" *)
module i2c_master(clk, rst, start, data_in, sda_in, clk_divider, scl, sda, busy);
  (* src = "RTL/i2c_master.v:20.6-20.16" *)
  wire ack_enable;
  (* src = "RTL/i2c_master.v:22.6-22.18" *)
  wire ack_received;
  (* src = "RTL/i2c_master.v:24.31-24.40" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] bit_count;
  (* src = "RTL/i2c_master.v:13.12-13.16" *)
  output busy;
  wire busy;
  (* src = "RTL/i2c_master.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_master.v:9.18-9.29" *)
  input [15:0] clk_divider;
  wire [15:0] clk_divider;
  (* src = "RTL/i2c_master.v:7.28-7.35" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "RTL/i2c_master.v:21.6-21.10" *)
  wire done;
  (* src = "RTL/i2c_master.v:18.6-18.10" *)
  wire load;
  (* src = "RTL/i2c_master.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_master.v:11.12-11.15" *)
  output scl;
  wire scl;
  (* src = "RTL/i2c_master.v:12.12-12.15" *)
  output sda;
  wire sda;
  (* src = "RTL/i2c_master.v:8.11-8.17" *)
  input sda_in;
  wire sda_in;
  (* src = "RTL/i2c_master.v:19.6-19.11" *)
  wire shift;
  (* src = "RTL/i2c_master.v:23.23-23.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] shift_reg;
  (* src = "RTL/i2c_master.v:6.11-6.16" *)
  input start;
  wire start;
  (* src = "RTL/i2c_master.v:16.6-16.21" *)
  (* unused_bits = "0" *)
  wire start_condition;
  (* src = "RTL/i2c_master.v:17.6-17.20" *)
  (* unused_bits = "0" *)
  wire stop_condition;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/i2c_master.v:83.18-91.2" *)
  i2c_ack_detector ack (
    .ack_enable(ack_enable),
    .ack_received(ack_received),
    .rst(rst),
    .scl(scl),
    .sda(sda_in)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/i2c_master.v:28.21-35.2" *)
  i2c_clock_generator clock_gen (
    .clk(clk),
    .clk_divider(clk_divider),
    .rst(rst),
    .scl(scl)
  );
  (* src = "RTL/i2c_master.v:71.3-79.2" *)
  \$paramod\i2c_bit_counter\DATA_WIDTH=s32'00000000000000000000000000001000  counter (
    .bit_count(bit_count),
    .done(done),
    .enable(shift),
    .rst(rst),
    .scl(scl)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/i2c_master.v:95.16-109.2" *)
  i2c_master_fsm fsm (
    .ack_enable(ack_enable),
    .ack_received(ack_received),
    .busy(busy),
    .done(done),
    .load(load),
    .rst(rst),
    .scl(scl),
    .shift(shift),
    .start(start),
    .start_condition(start_condition),
    .stop_condition(stop_condition)
  );
  (* src = "RTL/i2c_master.v:54.3-64.2" *)
  \$paramod\i2c_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000  shift_register (
    .data_in(data_in),
    .load(load),
    .rst(rst),
    .scl(scl),
    .sda(sda),
    .shift(shift),
    .shift_reg(shift_reg)
  );
endmodule

(* src = "RTL/i2c_master_fsm.v:1.1-129.10" *)
module i2c_master_fsm(scl, rst, start, done, ack_received, start_condition, stop_condition, load, shift, ack_enable, busy);
  (* src = "RTL/i2c_master_fsm.v:28.1-73.4" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [2:0] _10_;
  wire [2:0] _11_;
  wire _12_;
  (* src = "RTL/i2c_master_fsm.v:13.16-13.26" *)
  output ack_enable;
  wire ack_enable;
  (* src = "RTL/i2c_master_fsm.v:7.11-7.23" *)
  input ack_received;
  wire ack_received;
  (* src = "RTL/i2c_master_fsm.v:14.16-14.20" *)
  output busy;
  wire busy;
  (* src = "RTL/i2c_master_fsm.v:6.11-6.15" *)
  input done;
  wire done;
  (* src = "RTL/i2c_master_fsm.v:11.16-11.20" *)
  output load;
  wire load;
  (* src = "RTL/i2c_master_fsm.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_master_fsm.v:3.11-3.14" *)
  input scl;
  wire scl;
  (* src = "RTL/i2c_master_fsm.v:12.16-12.21" *)
  output shift;
  wire shift;
  (* src = "RTL/i2c_master_fsm.v:5.11-5.16" *)
  input start;
  wire start;
  (* src = "RTL/i2c_master_fsm.v:9.16-9.31" *)
  output start_condition;
  wire start_condition;
  (* src = "RTL/i2c_master_fsm.v:26.11-26.16" *)
  reg [2:0] state;
  (* src = "RTL/i2c_master_fsm.v:10.16-10.30" *)
  output stop_condition;
  wire stop_condition;
  (* src = "RTL/i2c_master_fsm.v:28.1-73.4" *)
  always @(posedge scl, posedge rst)
    if (rst) state <= 3'h0;
    else if (_03_) state <= _00_;
  assign _01_ = { _07_, done } != 2'h2;
  assign _02_ = { _12_, start } != 2'h2;
  assign _03_ = & { _01_, _02_ };
  assign _04_ = | { _09_, _08_, _07_, _06_, _05_ };
  assign busy = _04_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign shift = _07_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign load = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign stop_condition = _05_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign start_condition = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign ack_enable = _06_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  function [2:0] _24_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _24_ = b[2:0];
      6'b????1?:
        _24_ = b[5:3];
      6'b???1??:
        _24_ = b[8:6];
      6'b??1???:
        _24_ = b[11:9];
      6'b?1????:
        _24_ = b[14:12];
      6'b1?????:
        _24_ = b[17:15];
      default:
        _24_ = a;
    endcase
  endfunction
  assign _00_ = _24_(3'h0, { _11_, 6'h13, _10_, 6'h2e }, { _12_, _09_, _08_, _07_, _06_, _05_ });
  assign _05_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h5;
  assign _06_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h4;
  assign _10_ = done ? (* src = "RTL/i2c_master_fsm.v:50.16-50.20|RTL/i2c_master_fsm.v:50.13-51.30" *) 3'h4 : 3'hx;
  assign _07_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h3;
  assign _08_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h2;
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h1;
  assign _11_ = start ? (* src = "RTL/i2c_master_fsm.v:40.16-40.21|RTL/i2c_master_fsm.v:40.13-41.32" *) 3'h1 : 3'hx;
  assign _12_ = ! (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) state;
endmodule

(* src = "RTL/i2c_start_stop_generator.v:1.1-44.10" *)
module i2c_start_stop_generator(clk, rst, start, stop, sda, busy);
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  wire _00_;
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "RTL/i2c_start_stop_generator.v:9.16-9.20" *)
  output busy;
  reg busy;
  (* src = "RTL/i2c_start_stop_generator.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_start_stop_generator.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_start_stop_generator.v:8.16-8.19" *)
  output sda;
  reg sda;
  (* src = "RTL/i2c_start_stop_generator.v:5.11-5.16" *)
  input start;
  wire start;
  (* src = "RTL/i2c_start_stop_generator.v:6.11-6.15" *)
  input stop;
  wire stop;
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  always @(posedge clk, posedge rst)
    if (rst) sda <= 1'h1;
    else if (_02_) sda <= _01_;
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_02_) busy <= _00_;
  assign _02_ = | { stop, start };
  assign _03_ = stop ? (* src = "RTL/i2c_start_stop_generator.v:35.17-35.21|RTL/i2c_start_stop_generator.v:35.14-41.12" *) 1'h0 : 1'hx;
  assign _00_ = start ? (* full_case = 32'd1 *) (* src = "RTL/i2c_start_stop_generator.v:27.12-27.17|RTL/i2c_start_stop_generator.v:27.9-41.12" *) 1'h1 : _03_;
  assign _04_ = stop ? (* src = "RTL/i2c_start_stop_generator.v:35.17-35.21|RTL/i2c_start_stop_generator.v:35.14-41.12" *) 1'h1 : 1'hx;
  assign _01_ = start ? (* full_case = 32'd1 *) (* src = "RTL/i2c_start_stop_generator.v:27.12-27.17|RTL/i2c_start_stop_generator.v:27.9-41.12" *) 1'h0 : _04_;
endmodule
