/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/i2c_master_fsm.v:1.1-129.10" *)
module i2c_master_fsm(scl, rst, start, done, ack_received, start_condition, stop_condition, load, shift, ack_enable, busy);
  (* src = "RTL/i2c_master_fsm.v:28.1-73.4" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [2:0] _10_;
  wire [2:0] _11_;
  wire _12_;
  (* src = "RTL/i2c_master_fsm.v:13.16-13.26" *)
  output ack_enable;
  wire ack_enable;
  (* src = "RTL/i2c_master_fsm.v:7.11-7.23" *)
  input ack_received;
  wire ack_received;
  (* src = "RTL/i2c_master_fsm.v:14.16-14.20" *)
  output busy;
  wire busy;
  (* src = "RTL/i2c_master_fsm.v:6.11-6.15" *)
  input done;
  wire done;
  (* src = "RTL/i2c_master_fsm.v:11.16-11.20" *)
  output load;
  wire load;
  (* src = "RTL/i2c_master_fsm.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_master_fsm.v:3.11-3.14" *)
  input scl;
  wire scl;
  (* src = "RTL/i2c_master_fsm.v:12.16-12.21" *)
  output shift;
  wire shift;
  (* src = "RTL/i2c_master_fsm.v:5.11-5.16" *)
  input start;
  wire start;
  (* src = "RTL/i2c_master_fsm.v:9.16-9.31" *)
  output start_condition;
  wire start_condition;
  (* src = "RTL/i2c_master_fsm.v:26.11-26.16" *)
  reg [2:0] state;
  (* src = "RTL/i2c_master_fsm.v:10.16-10.30" *)
  output stop_condition;
  wire stop_condition;
  (* src = "RTL/i2c_master_fsm.v:28.1-73.4" *)
  always @(posedge scl, posedge rst)
    if (rst) state <= 3'h0;
    else if (_03_) state <= _00_;
  assign _01_ = { _12_, start } != 2'h2;
  assign _02_ = { _07_, done } != 2'h2;
  assign _03_ = & { _02_, _01_ };
  assign _04_ = | { _09_, _08_, _07_, _06_, _05_ };
  assign ack_enable = _06_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign shift = _07_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign load = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign stop_condition = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign start_condition = _05_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  function [2:0] _23_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _23_ = b[2:0];
      6'b????1?:
        _23_ = b[5:3];
      6'b???1??:
        _23_ = b[8:6];
      6'b??1???:
        _23_ = b[11:9];
      6'b?1????:
        _23_ = b[14:12];
      6'b1?????:
        _23_ = b[17:15];
      default:
        _23_ = a;
    endcase
  endfunction
  assign _00_ = _23_(3'h0, { _11_, 6'h13, _10_, 6'h2e }, { _12_, _05_, _08_, _07_, _06_, _09_ });
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h5;
  assign _06_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h4;
  assign _10_ = done ? (* src = "RTL/i2c_master_fsm.v:50.16-50.20|RTL/i2c_master_fsm.v:50.13-51.30" *) 3'h4 : 3'hx;
  assign busy = _04_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:85.5-127.12" *) 1'h1 : 1'h0;
  assign _07_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h3;
  assign _08_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h2;
  assign _05_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) 3'h1;
  assign _11_ = start ? (* src = "RTL/i2c_master_fsm.v:40.16-40.21|RTL/i2c_master_fsm.v:40.13-41.32" *) 3'h1 : 3'hx;
  assign _12_ = ! (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:37.9-70.16" *) state;
endmodule
