/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/i2c_shift_register.v:1.1-40.10" *)
module i2c_shift_register(scl, rst, load, shift, data_in, sda, shift_reg);
  (* src = "RTL/i2c_shift_register.v:16.1-39.4" *)
  wire [7:0] _0_;
  wire _1_;
  wire [7:0] _2_;
  (* src = "RTL/i2c_shift_register.v:8.28-8.35" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "RTL/i2c_shift_register.v:6.11-6.15" *)
  input load;
  wire load;
  (* src = "RTL/i2c_shift_register.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_shift_register.v:4.11-4.14" *)
  input scl;
  wire scl;
  (* src = "RTL/i2c_shift_register.v:10.12-10.15" *)
  output sda;
  wire sda;
  (* src = "RTL/i2c_shift_register.v:7.11-7.16" *)
  input shift;
  wire shift;
  (* src = "RTL/i2c_shift_register.v:11.33-11.42" *)
  output [7:0] shift_reg;
  reg [7:0] shift_reg;
  (* src = "RTL/i2c_shift_register.v:16.1-39.4" *)
  always @(posedge scl, posedge rst)
    if (rst) shift_reg <= 8'h00;
    else if (_1_) shift_reg <= _0_;
  assign _1_ = | { shift, load };
  assign _2_ = shift ? (* src = "RTL/i2c_shift_register.v:33.13-33.18|RTL/i2c_shift_register.v:33.10-38.8" *) { shift_reg[6:0], 1'h0 } : 8'hxx;
  assign _0_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:26.13-26.17|RTL/i2c_shift_register.v:26.10-38.8" *) data_in : _2_;
  assign sda = shift_reg[7];
endmodule
