/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/i2c_start_stop_generator.v:1.1-44.10" *)
module i2c_start_stop_generator(clk, rst, start, stop, sda, busy);
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  wire _00_;
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "RTL/i2c_start_stop_generator.v:9.16-9.20" *)
  output busy;
  reg busy;
  (* src = "RTL/i2c_start_stop_generator.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_start_stop_generator.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_start_stop_generator.v:8.16-8.19" *)
  output sda;
  reg sda;
  (* src = "RTL/i2c_start_stop_generator.v:5.11-5.16" *)
  input start;
  wire start;
  (* src = "RTL/i2c_start_stop_generator.v:6.11-6.15" *)
  input stop;
  wire stop;
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  always @(posedge clk, posedge rst)
    if (rst) sda <= 1'h1;
    else if (_02_) sda <= _01_;
  (* src = "RTL/i2c_start_stop_generator.v:13.1-43.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_02_) busy <= _00_;
  assign _02_ = | { stop, start };
  assign _01_ = start ? (* full_case = 32'd1 *) (* src = "RTL/i2c_start_stop_generator.v:27.12-27.17|RTL/i2c_start_stop_generator.v:27.9-41.12" *) 1'h0 : _04_;
  assign _03_ = stop ? (* src = "RTL/i2c_start_stop_generator.v:35.17-35.21|RTL/i2c_start_stop_generator.v:35.14-41.12" *) 1'h0 : 1'hx;
  assign _00_ = start ? (* full_case = 32'd1 *) (* src = "RTL/i2c_start_stop_generator.v:27.12-27.17|RTL/i2c_start_stop_generator.v:27.9-41.12" *) 1'h1 : _03_;
  assign _04_ = stop ? (* src = "RTL/i2c_start_stop_generator.v:35.17-35.21|RTL/i2c_start_stop_generator.v:35.14-41.12" *) 1'h1 : 1'hx;
endmodule
