/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/binary_counter_4bit.v:1.1-15.10" *)
module binary_counter_4bit(clk, rst, q);
  (* src = "RTL/binary_counter_4bit.v:7.1-13.4" *)
  wire [3:0] _0_;
  (* src = "RTL/binary_counter_4bit.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/binary_counter_4bit.v:4.22-4.23" *)
  output [3:0] q;
  reg [3:0] q;
  (* src = "RTL/binary_counter_4bit.v:3.11-3.14" *)
  input rst;
  wire rst;
  assign _0_ = q + (* src = "RTL/binary_counter_4bit.v:12.14-12.22" *) 1'h1;
  (* src = "RTL/binary_counter_4bit.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q <= 4'h0;
    else q <= _0_;
endmodule
