/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/clock_divider_by2.v:1.1-14.10" *)
module clock_divider_by2(clk, rst, clk_out);
  (* src = "RTL/clock_divider_by2.v:7.1-13.4" *)
  wire _0_;
  (* src = "RTL/clock_divider_by2.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/clock_divider_by2.v:4.16-4.23" *)
  output clk_out;
  reg clk_out;
  (* src = "RTL/clock_divider_by2.v:3.11-3.14" *)
  input rst;
  wire rst;
  assign _0_ = ~ (* src = "RTL/clock_divider_by2.v:12.20-12.28" *) clk_out;
  (* src = "RTL/clock_divider_by2.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_out <= 1'h0;
    else clk_out <= _0_;
endmodule
