/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/d_flip_flop.v:1.1-12.10" *)
module d_flip_flop(clk, d, q);
  (* src = "RTL/d_flip_flop.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/d_flip_flop.v:3.16-3.17" *)
  input d;
  wire d;
  (* src = "RTL/d_flip_flop.v:4.16-4.17" *)
  output q;
  reg q;
  (* src = "RTL/d_flip_flop.v:7.1-10.4" *)
  always @(posedge clk)
    q <= d;
endmodule
