/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/dff_async_reset.v:1.1-16.10" *)
module dff_async_reset(clk, rst, d, q);
  (* src = "RTL/dff_async_reset.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/dff_async_reset.v:4.11-4.12" *)
  input d;
  wire d;
  (* src = "RTL/dff_async_reset.v:5.16-5.17" *)
  output q;
  reg q;
  (* src = "RTL/dff_async_reset.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "RTL/dff_async_reset.v:8.1-14.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q <= 1'h0;
    else q <= d;
endmodule
