/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/register_4bit.v:1.1-16.10" *)
module register_4bit(clk, rst, d, q);
  (* src = "RTL/register_4bit.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/register_4bit.v:4.17-4.18" *)
  input [3:0] d;
  wire [3:0] d;
  (* src = "RTL/register_4bit.v:5.22-5.23" *)
  output [3:0] q;
  reg [3:0] q;
  (* src = "RTL/register_4bit.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "RTL/register_4bit.v:8.1-14.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q <= 4'h0;
    else q <= d;
endmodule
