/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/ring_counter_4bit.v:1.1-15.10" *)
module ring_counter_4bit(clk, rst, q);
  (* src = "RTL/ring_counter_4bit.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/ring_counter_4bit.v:4.22-4.23" *)
  output [3:0] q;
  reg [3:0] q;
  (* src = "RTL/ring_counter_4bit.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "RTL/ring_counter_4bit.v:7.1-13.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q <= 4'h1;
    else q <= { q[2:0], q[3] };
endmodule
