/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/up_down_counter_4bit.v:1.1-19.10" *)
module up_down_counter_4bit(clk, rst, up_down, q);
  (* src = "RTL/up_down_counter_4bit.v:8.1-18.4" *)
  wire [3:0] _0_;
  (* src = "RTL/up_down_counter_4bit.v:14.14-14.22" *)
  wire [3:0] _1_;
  (* src = "RTL/up_down_counter_4bit.v:17.14-17.22" *)
  wire [3:0] _2_;
  (* src = "RTL/up_down_counter_4bit.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "RTL/up_down_counter_4bit.v:5.22-5.23" *)
  output [3:0] q;
  reg [3:0] q;
  (* src = "RTL/up_down_counter_4bit.v:3.11-3.14" *)
  input rst;
  wire rst;
  (* src = "RTL/up_down_counter_4bit.v:4.11-4.18" *)
  input up_down;
  wire up_down;
  assign _1_ = q + (* src = "RTL/up_down_counter_4bit.v:14.14-14.22" *) 1'h1;
  (* src = "RTL/up_down_counter_4bit.v:8.1-18.4" *)
  always @(posedge clk, posedge rst)
    if (rst) q <= 4'h0;
    else q <= _0_;
  assign _0_ = up_down ? (* full_case = 32'd1 *) (* src = "RTL/up_down_counter_4bit.v:13.13-13.20|RTL/up_down_counter_4bit.v:13.10-17.23" *) _1_ : _2_;
  assign _2_ = q - (* src = "RTL/up_down_counter_4bit.v:17.14-17.22" *) 1'h1;
endmodule
