/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/ex_mem_pipeline_register.v:1.1-54.10" *)
module ex_mem_pipeline_register(clk, rst, stall, flush, alu_result_in, store_data_in, rd_in, zero_in, reg_write_in, mem_read_in, mem_write_in, mem_to_reg_in, alu_result_out, store_data_out, rd_out, zero_out, reg_write_out, mem_read_out, mem_write_out, mem_to_reg_out);
  (* src = "RTL/ex_mem_pipeline_register.v:29.13-29.25" *)
  wire _0_;
  (* src = "RTL/ex_mem_pipeline_register.v:7.23-7.36" *)
  input [31:0] alu_result_in;
  wire [31:0] alu_result_in;
  (* src = "RTL/ex_mem_pipeline_register.v:17.23-17.37" *)
  output [31:0] alu_result_out;
  reg [31:0] alu_result_out;
  (* src = "RTL/ex_mem_pipeline_register.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/ex_mem_pipeline_register.v:5.16-5.21" *)
  input flush;
  wire flush;
  (* src = "RTL/ex_mem_pipeline_register.v:13.16-13.27" *)
  input mem_read_in;
  wire mem_read_in;
  (* src = "RTL/ex_mem_pipeline_register.v:23.16-23.28" *)
  output mem_read_out;
  reg mem_read_out;
  (* src = "RTL/ex_mem_pipeline_register.v:15.16-15.29" *)
  input mem_to_reg_in;
  wire mem_to_reg_in;
  (* src = "RTL/ex_mem_pipeline_register.v:25.16-25.30" *)
  output mem_to_reg_out;
  reg mem_to_reg_out;
  (* src = "RTL/ex_mem_pipeline_register.v:14.16-14.28" *)
  input mem_write_in;
  wire mem_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:24.16-24.29" *)
  output mem_write_out;
  reg mem_write_out;
  (* src = "RTL/ex_mem_pipeline_register.v:9.22-9.27" *)
  input [4:0] rd_in;
  wire [4:0] rd_in;
  (* src = "RTL/ex_mem_pipeline_register.v:19.23-19.29" *)
  output [4:0] rd_out;
  reg [4:0] rd_out;
  (* src = "RTL/ex_mem_pipeline_register.v:12.16-12.28" *)
  input reg_write_in;
  wire reg_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:22.16-22.29" *)
  output reg_write_out;
  reg reg_write_out;
  (* src = "RTL/ex_mem_pipeline_register.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "RTL/ex_mem_pipeline_register.v:4.16-4.21" *)
  input stall;
  wire stall;
  (* src = "RTL/ex_mem_pipeline_register.v:8.23-8.36" *)
  input [31:0] store_data_in;
  wire [31:0] store_data_in;
  (* src = "RTL/ex_mem_pipeline_register.v:18.23-18.37" *)
  output [31:0] store_data_out;
  reg [31:0] store_data_out;
  (* src = "RTL/ex_mem_pipeline_register.v:10.16-10.23" *)
  input zero_in;
  wire zero_in;
  (* src = "RTL/ex_mem_pipeline_register.v:20.16-20.24" *)
  output zero_out;
  reg zero_out;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) alu_result_out <= 32'd0;
    else if (!stall) alu_result_out <= alu_result_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) store_data_out <= 32'd0;
    else if (!stall) store_data_out <= store_data_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) rd_out <= 5'h00;
    else if (!stall) rd_out <= rd_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) zero_out <= 1'h0;
    else if (!stall) zero_out <= zero_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) reg_write_out <= 1'h0;
    else if (!stall) reg_write_out <= reg_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) mem_read_out <= 1'h0;
    else if (!stall) mem_read_out <= mem_read_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) mem_write_out <= 1'h0;
    else if (!stall) mem_write_out <= mem_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) mem_to_reg_out <= 1'h0;
    else if (!stall) mem_to_reg_out <= mem_to_reg_in;
  assign _0_ = rst || (* src = "RTL/ex_mem_pipeline_register.v:29.13-29.25" *) flush;
endmodule
