/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/id_ex_pipeline_register.v:1.1-77.10" *)
module id_ex_pipeline_register(clk, rst, stall, flush, pc_in, rs1_value_in, rs2_value_in, immediate_in, rs1_in, rs2_in, rd_in, alu_control_in, reg_write_in, mem_read_in, mem_write_in, mem_to_reg_in, alu_src_in, pc_out, rs1_value_out, rs2_value_out, immediate_out
, rs1_out, rs2_out, rd_out, alu_control_out, reg_write_out, mem_read_out, mem_write_out, mem_to_reg_out, alu_src_out);
  (* src = "RTL/id_ex_pipeline_register.v:41.13-41.25" *)
  wire _00_;
  (* src = "RTL/id_ex_pipeline_register.v:16.23-16.37" *)
  input [3:0] alu_control_in;
  wire [3:0] alu_control_in;
  (* src = "RTL/id_ex_pipeline_register.v:32.23-32.38" *)
  output [3:0] alu_control_out;
  reg [3:0] alu_control_out;
  (* src = "RTL/id_ex_pipeline_register.v:21.16-21.26" *)
  input alu_src_in;
  wire alu_src_in;
  (* src = "RTL/id_ex_pipeline_register.v:37.16-37.27" *)
  output alu_src_out;
  reg alu_src_out;
  (* src = "RTL/id_ex_pipeline_register.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/id_ex_pipeline_register.v:5.16-5.21" *)
  input flush;
  wire flush;
  (* src = "RTL/id_ex_pipeline_register.v:10.23-10.35" *)
  input [31:0] immediate_in;
  wire [31:0] immediate_in;
  (* src = "RTL/id_ex_pipeline_register.v:26.23-26.36" *)
  output [31:0] immediate_out;
  reg [31:0] immediate_out;
  (* src = "RTL/id_ex_pipeline_register.v:18.16-18.27" *)
  input mem_read_in;
  wire mem_read_in;
  (* src = "RTL/id_ex_pipeline_register.v:34.16-34.28" *)
  output mem_read_out;
  reg mem_read_out;
  (* src = "RTL/id_ex_pipeline_register.v:20.16-20.29" *)
  input mem_to_reg_in;
  wire mem_to_reg_in;
  (* src = "RTL/id_ex_pipeline_register.v:36.16-36.30" *)
  output mem_to_reg_out;
  reg mem_to_reg_out;
  (* src = "RTL/id_ex_pipeline_register.v:19.16-19.28" *)
  input mem_write_in;
  wire mem_write_in;
  (* src = "RTL/id_ex_pipeline_register.v:35.16-35.29" *)
  output mem_write_out;
  reg mem_write_out;
  (* src = "RTL/id_ex_pipeline_register.v:7.23-7.28" *)
  input [31:0] pc_in;
  wire [31:0] pc_in;
  (* src = "RTL/id_ex_pipeline_register.v:23.23-23.29" *)
  output [31:0] pc_out;
  reg [31:0] pc_out;
  (* src = "RTL/id_ex_pipeline_register.v:14.22-14.27" *)
  input [4:0] rd_in;
  wire [4:0] rd_in;
  (* src = "RTL/id_ex_pipeline_register.v:30.22-30.28" *)
  output [4:0] rd_out;
  reg [4:0] rd_out;
  (* src = "RTL/id_ex_pipeline_register.v:17.16-17.28" *)
  input reg_write_in;
  wire reg_write_in;
  (* src = "RTL/id_ex_pipeline_register.v:33.16-33.29" *)
  output reg_write_out;
  reg reg_write_out;
  (* src = "RTL/id_ex_pipeline_register.v:12.22-12.28" *)
  input [4:0] rs1_in;
  wire [4:0] rs1_in;
  (* src = "RTL/id_ex_pipeline_register.v:28.22-28.29" *)
  output [4:0] rs1_out;
  reg [4:0] rs1_out;
  (* src = "RTL/id_ex_pipeline_register.v:8.23-8.35" *)
  input [31:0] rs1_value_in;
  wire [31:0] rs1_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:24.23-24.36" *)
  output [31:0] rs1_value_out;
  reg [31:0] rs1_value_out;
  (* src = "RTL/id_ex_pipeline_register.v:13.22-13.28" *)
  input [4:0] rs2_in;
  wire [4:0] rs2_in;
  (* src = "RTL/id_ex_pipeline_register.v:29.22-29.29" *)
  output [4:0] rs2_out;
  reg [4:0] rs2_out;
  (* src = "RTL/id_ex_pipeline_register.v:9.23-9.35" *)
  input [31:0] rs2_value_in;
  wire [31:0] rs2_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:25.23-25.36" *)
  output [31:0] rs2_value_out;
  reg [31:0] rs2_value_out;
  (* src = "RTL/id_ex_pipeline_register.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "RTL/id_ex_pipeline_register.v:4.16-4.21" *)
  input stall;
  wire stall;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) mem_read_out <= 1'h0;
    else if (!stall) mem_read_out <= mem_read_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) mem_write_out <= 1'h0;
    else if (!stall) mem_write_out <= mem_write_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) mem_to_reg_out <= 1'h0;
    else if (!stall) mem_to_reg_out <= mem_to_reg_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) alu_src_out <= 1'h0;
    else if (!stall) alu_src_out <= alu_src_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) pc_out <= 32'd0;
    else if (!stall) pc_out <= pc_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs1_value_out <= 32'd0;
    else if (!stall) rs1_value_out <= rs1_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs2_value_out <= 32'd0;
    else if (!stall) rs2_value_out <= rs2_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) immediate_out <= 32'd0;
    else if (!stall) immediate_out <= immediate_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs1_out <= 5'h00;
    else if (!stall) rs1_out <= rs1_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs2_out <= 5'h00;
    else if (!stall) rs2_out <= rs2_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rd_out <= 5'h00;
    else if (!stall) rd_out <= rd_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) alu_control_out <= 4'h0;
    else if (!stall) alu_control_out <= alu_control_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) reg_write_out <= 1'h0;
    else if (!stall) reg_write_out <= reg_write_in;
  assign _00_ = rst || (* src = "RTL/id_ex_pipeline_register.v:41.13-41.25" *) flush;
endmodule
