/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "RTL/ex_mem_pipeline_register.v:1.1-54.10" *)
module ex_mem_pipeline_register(clk, rst, stall, flush, alu_result_in, store_data_in, rd_in, zero_in, reg_write_in, mem_read_in, mem_write_in, mem_to_reg_in, alu_result_out, store_data_out, rd_out, zero_out, reg_write_out, mem_read_out, mem_write_out, mem_to_reg_out);
  (* src = "RTL/ex_mem_pipeline_register.v:29.13-29.25" *)
  wire _0_;
  (* src = "RTL/ex_mem_pipeline_register.v:7.23-7.36" *)
  input [31:0] alu_result_in;
  wire [31:0] alu_result_in;
  (* src = "RTL/ex_mem_pipeline_register.v:17.23-17.37" *)
  output [31:0] alu_result_out;
  reg [31:0] alu_result_out;
  (* src = "RTL/ex_mem_pipeline_register.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/ex_mem_pipeline_register.v:5.16-5.21" *)
  input flush;
  wire flush;
  (* src = "RTL/ex_mem_pipeline_register.v:13.16-13.27" *)
  input mem_read_in;
  wire mem_read_in;
  (* src = "RTL/ex_mem_pipeline_register.v:23.16-23.28" *)
  output mem_read_out;
  reg mem_read_out;
  (* src = "RTL/ex_mem_pipeline_register.v:15.16-15.29" *)
  input mem_to_reg_in;
  wire mem_to_reg_in;
  (* src = "RTL/ex_mem_pipeline_register.v:25.16-25.30" *)
  output mem_to_reg_out;
  reg mem_to_reg_out;
  (* src = "RTL/ex_mem_pipeline_register.v:14.16-14.28" *)
  input mem_write_in;
  wire mem_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:24.16-24.29" *)
  output mem_write_out;
  reg mem_write_out;
  (* src = "RTL/ex_mem_pipeline_register.v:9.22-9.27" *)
  input [4:0] rd_in;
  wire [4:0] rd_in;
  (* src = "RTL/ex_mem_pipeline_register.v:19.23-19.29" *)
  output [4:0] rd_out;
  reg [4:0] rd_out;
  (* src = "RTL/ex_mem_pipeline_register.v:12.16-12.28" *)
  input reg_write_in;
  wire reg_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:22.16-22.29" *)
  output reg_write_out;
  reg reg_write_out;
  (* src = "RTL/ex_mem_pipeline_register.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "RTL/ex_mem_pipeline_register.v:4.16-4.21" *)
  input stall;
  wire stall;
  (* src = "RTL/ex_mem_pipeline_register.v:8.23-8.36" *)
  input [31:0] store_data_in;
  wire [31:0] store_data_in;
  (* src = "RTL/ex_mem_pipeline_register.v:18.23-18.37" *)
  output [31:0] store_data_out;
  reg [31:0] store_data_out;
  (* src = "RTL/ex_mem_pipeline_register.v:10.16-10.23" *)
  input zero_in;
  wire zero_in;
  (* src = "RTL/ex_mem_pipeline_register.v:20.16-20.24" *)
  output zero_out;
  reg zero_out;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) rd_out <= 5'h00;
    else if (!stall) rd_out <= rd_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) reg_write_out <= 1'h0;
    else if (!stall) reg_write_out <= reg_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) mem_read_out <= 1'h0;
    else if (!stall) mem_read_out <= mem_read_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) mem_write_out <= 1'h0;
    else if (!stall) mem_write_out <= mem_write_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) mem_to_reg_out <= 1'h0;
    else if (!stall) mem_to_reg_out <= mem_to_reg_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) alu_result_out <= 32'd0;
    else if (!stall) alu_result_out <= alu_result_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) store_data_out <= 32'd0;
    else if (!stall) store_data_out <= store_data_in;
  (* src = "RTL/ex_mem_pipeline_register.v:28.5-52.8" *)
  always @(posedge clk)
    if (_0_) zero_out <= 1'h0;
    else if (!stall) zero_out <= zero_in;
  assign _0_ = rst || (* src = "RTL/ex_mem_pipeline_register.v:29.13-29.25" *) flush;
endmodule

(* src = "RTL/id_ex_pipeline_register.v:1.1-77.10" *)
module id_ex_pipeline_register(clk, rst, stall, flush, pc_in, rs1_value_in, rs2_value_in, immediate_in, rs1_in, rs2_in, rd_in, alu_control_in, reg_write_in, mem_read_in, mem_write_in, mem_to_reg_in, alu_src_in, pc_out, rs1_value_out, rs2_value_out, immediate_out
, rs1_out, rs2_out, rd_out, alu_control_out, reg_write_out, mem_read_out, mem_write_out, mem_to_reg_out, alu_src_out);
  (* src = "RTL/id_ex_pipeline_register.v:41.13-41.25" *)
  wire _00_;
  (* src = "RTL/id_ex_pipeline_register.v:16.23-16.37" *)
  input [3:0] alu_control_in;
  wire [3:0] alu_control_in;
  (* src = "RTL/id_ex_pipeline_register.v:32.23-32.38" *)
  output [3:0] alu_control_out;
  reg [3:0] alu_control_out;
  (* src = "RTL/id_ex_pipeline_register.v:21.16-21.26" *)
  input alu_src_in;
  wire alu_src_in;
  (* src = "RTL/id_ex_pipeline_register.v:37.16-37.27" *)
  output alu_src_out;
  reg alu_src_out;
  (* src = "RTL/id_ex_pipeline_register.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/id_ex_pipeline_register.v:5.16-5.21" *)
  input flush;
  wire flush;
  (* src = "RTL/id_ex_pipeline_register.v:10.23-10.35" *)
  input [31:0] immediate_in;
  wire [31:0] immediate_in;
  (* src = "RTL/id_ex_pipeline_register.v:26.23-26.36" *)
  output [31:0] immediate_out;
  reg [31:0] immediate_out;
  (* src = "RTL/id_ex_pipeline_register.v:18.16-18.27" *)
  input mem_read_in;
  wire mem_read_in;
  (* src = "RTL/id_ex_pipeline_register.v:34.16-34.28" *)
  output mem_read_out;
  reg mem_read_out;
  (* src = "RTL/id_ex_pipeline_register.v:20.16-20.29" *)
  input mem_to_reg_in;
  wire mem_to_reg_in;
  (* src = "RTL/id_ex_pipeline_register.v:36.16-36.30" *)
  output mem_to_reg_out;
  reg mem_to_reg_out;
  (* src = "RTL/id_ex_pipeline_register.v:19.16-19.28" *)
  input mem_write_in;
  wire mem_write_in;
  (* src = "RTL/id_ex_pipeline_register.v:35.16-35.29" *)
  output mem_write_out;
  reg mem_write_out;
  (* src = "RTL/id_ex_pipeline_register.v:7.23-7.28" *)
  input [31:0] pc_in;
  wire [31:0] pc_in;
  (* src = "RTL/id_ex_pipeline_register.v:23.23-23.29" *)
  output [31:0] pc_out;
  reg [31:0] pc_out;
  (* src = "RTL/id_ex_pipeline_register.v:14.22-14.27" *)
  input [4:0] rd_in;
  wire [4:0] rd_in;
  (* src = "RTL/id_ex_pipeline_register.v:30.22-30.28" *)
  output [4:0] rd_out;
  reg [4:0] rd_out;
  (* src = "RTL/id_ex_pipeline_register.v:17.16-17.28" *)
  input reg_write_in;
  wire reg_write_in;
  (* src = "RTL/id_ex_pipeline_register.v:33.16-33.29" *)
  output reg_write_out;
  reg reg_write_out;
  (* src = "RTL/id_ex_pipeline_register.v:12.22-12.28" *)
  input [4:0] rs1_in;
  wire [4:0] rs1_in;
  (* src = "RTL/id_ex_pipeline_register.v:28.22-28.29" *)
  output [4:0] rs1_out;
  reg [4:0] rs1_out;
  (* src = "RTL/id_ex_pipeline_register.v:8.23-8.35" *)
  input [31:0] rs1_value_in;
  wire [31:0] rs1_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:24.23-24.36" *)
  output [31:0] rs1_value_out;
  reg [31:0] rs1_value_out;
  (* src = "RTL/id_ex_pipeline_register.v:13.22-13.28" *)
  input [4:0] rs2_in;
  wire [4:0] rs2_in;
  (* src = "RTL/id_ex_pipeline_register.v:29.22-29.29" *)
  output [4:0] rs2_out;
  reg [4:0] rs2_out;
  (* src = "RTL/id_ex_pipeline_register.v:9.23-9.35" *)
  input [31:0] rs2_value_in;
  wire [31:0] rs2_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:25.23-25.36" *)
  output [31:0] rs2_value_out;
  reg [31:0] rs2_value_out;
  (* src = "RTL/id_ex_pipeline_register.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "RTL/id_ex_pipeline_register.v:4.16-4.21" *)
  input stall;
  wire stall;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) pc_out <= 32'd0;
    else if (!stall) pc_out <= pc_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs1_value_out <= 32'd0;
    else if (!stall) rs1_value_out <= rs1_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs2_value_out <= 32'd0;
    else if (!stall) rs2_value_out <= rs2_value_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) immediate_out <= 32'd0;
    else if (!stall) immediate_out <= immediate_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs1_out <= 5'h00;
    else if (!stall) rs1_out <= rs1_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rs2_out <= 5'h00;
    else if (!stall) rs2_out <= rs2_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) rd_out <= 5'h00;
    else if (!stall) rd_out <= rd_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) alu_control_out <= 4'h0;
    else if (!stall) alu_control_out <= alu_control_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) reg_write_out <= 1'h0;
    else if (!stall) reg_write_out <= reg_write_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) mem_read_out <= 1'h0;
    else if (!stall) mem_read_out <= mem_read_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) mem_write_out <= 1'h0;
    else if (!stall) mem_write_out <= mem_write_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) mem_to_reg_out <= 1'h0;
    else if (!stall) mem_to_reg_out <= mem_to_reg_in;
  (* src = "RTL/id_ex_pipeline_register.v:40.5-75.8" *)
  always @(posedge clk)
    if (_00_) alu_src_out <= 1'h0;
    else if (!stall) alu_src_out <= alu_src_in;
  assign _00_ = rst || (* src = "RTL/id_ex_pipeline_register.v:41.13-41.25" *) flush;
endmodule

(* src = "RTL/if_id_pipeline_register.v:1.1-25.10" *)
module if_id_pipeline_register(clk, rst, stall, flush, pc_in, instruction_in, pc_out, instruction_out);
  (* src = "RTL/if_id_pipeline_register.v:15.13-15.25" *)
  wire _0_;
  (* src = "RTL/if_id_pipeline_register.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/if_id_pipeline_register.v:5.16-5.21" *)
  input flush;
  wire flush;
  (* src = "RTL/if_id_pipeline_register.v:8.23-8.37" *)
  input [31:0] instruction_in;
  wire [31:0] instruction_in;
  (* src = "RTL/if_id_pipeline_register.v:11.23-11.38" *)
  output [31:0] instruction_out;
  reg [31:0] instruction_out;
  (* src = "RTL/if_id_pipeline_register.v:7.23-7.28" *)
  input [31:0] pc_in;
  wire [31:0] pc_in;
  (* src = "RTL/if_id_pipeline_register.v:10.23-10.29" *)
  output [31:0] pc_out;
  reg [31:0] pc_out;
  (* src = "RTL/if_id_pipeline_register.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "RTL/if_id_pipeline_register.v:4.16-4.21" *)
  input stall;
  wire stall;
  (* src = "RTL/if_id_pipeline_register.v:14.5-23.8" *)
  always @(posedge clk)
    if (_0_) pc_out <= 32'd0;
    else if (!stall) pc_out <= pc_in;
  (* src = "RTL/if_id_pipeline_register.v:14.5-23.8" *)
  always @(posedge clk)
    if (_0_) instruction_out <= 32'd0;
    else if (!stall) instruction_out <= instruction_in;
  assign _0_ = rst || (* src = "RTL/if_id_pipeline_register.v:15.13-15.25" *) flush;
endmodule

(* src = "RTL/mem_wb_pipeline_register.v:1.1-41.10" *)
module mem_wb_pipeline_register(clk, rst, stall, flush, mem_data_in, alu_result_in, rd_in, reg_write_in, mem_to_reg_in, mem_data_out, alu_result_out, rd_out, reg_write_out, mem_to_reg_out);
  (* src = "RTL/mem_wb_pipeline_register.v:23.13-23.25" *)
  wire _0_;
  (* src = "RTL/mem_wb_pipeline_register.v:8.23-8.36" *)
  input [31:0] alu_result_in;
  wire [31:0] alu_result_in;
  (* src = "RTL/mem_wb_pipeline_register.v:15.23-15.37" *)
  output [31:0] alu_result_out;
  reg [31:0] alu_result_out;
  (* src = "RTL/mem_wb_pipeline_register.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/mem_wb_pipeline_register.v:5.16-5.21" *)
  input flush;
  wire flush;
  (* src = "RTL/mem_wb_pipeline_register.v:7.23-7.34" *)
  input [31:0] mem_data_in;
  wire [31:0] mem_data_in;
  (* src = "RTL/mem_wb_pipeline_register.v:14.23-14.35" *)
  output [31:0] mem_data_out;
  reg [31:0] mem_data_out;
  (* src = "RTL/mem_wb_pipeline_register.v:12.16-12.29" *)
  input mem_to_reg_in;
  wire mem_to_reg_in;
  (* src = "RTL/mem_wb_pipeline_register.v:19.16-19.30" *)
  output mem_to_reg_out;
  reg mem_to_reg_out;
  (* src = "RTL/mem_wb_pipeline_register.v:9.23-9.28" *)
  input [4:0] rd_in;
  wire [4:0] rd_in;
  (* src = "RTL/mem_wb_pipeline_register.v:16.22-16.28" *)
  output [4:0] rd_out;
  reg [4:0] rd_out;
  (* src = "RTL/mem_wb_pipeline_register.v:11.16-11.28" *)
  input reg_write_in;
  wire reg_write_in;
  (* src = "RTL/mem_wb_pipeline_register.v:18.16-18.29" *)
  output reg_write_out;
  reg reg_write_out;
  (* src = "RTL/mem_wb_pipeline_register.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "RTL/mem_wb_pipeline_register.v:4.16-4.21" *)
  input stall;
  wire stall;
  (* src = "RTL/mem_wb_pipeline_register.v:22.5-39.8" *)
  always @(posedge clk)
    if (_0_) rd_out <= 5'h00;
    else if (!stall) rd_out <= rd_in;
  (* src = "RTL/mem_wb_pipeline_register.v:22.5-39.8" *)
  always @(posedge clk)
    if (_0_) reg_write_out <= 1'h0;
    else if (!stall) reg_write_out <= reg_write_in;
  (* src = "RTL/mem_wb_pipeline_register.v:22.5-39.8" *)
  always @(posedge clk)
    if (_0_) mem_to_reg_out <= 1'h0;
    else if (!stall) mem_to_reg_out <= mem_to_reg_in;
  (* src = "RTL/mem_wb_pipeline_register.v:22.5-39.8" *)
  always @(posedge clk)
    if (_0_) alu_result_out <= 32'd0;
    else if (!stall) alu_result_out <= alu_result_in;
  (* src = "RTL/mem_wb_pipeline_register.v:22.5-39.8" *)
  always @(posedge clk)
    if (_0_) mem_data_out <= 32'd0;
    else if (!stall) mem_data_out <= mem_data_in;
  assign _0_ = rst || (* src = "RTL/mem_wb_pipeline_register.v:23.13-23.25" *) flush;
endmodule

(* src = "RTL/pipeline_control_unit.v:1.1-26.10" *)
module pipeline_control_unit(stall_request, flush_request, pc_write, if_id_write, id_ex_flush);
  (* src = "RTL/pipeline_control_unit.v:10.5-24.8" *)
  wire _0_;
  (* src = "RTL/pipeline_control_unit.v:10.5-24.8" *)
  wire _1_;
  (* src = "RTL/pipeline_control_unit.v:3.17-3.30" *)
  input flush_request;
  wire flush_request;
  (* src = "RTL/pipeline_control_unit.v:7.16-7.27" *)
  output id_ex_flush;
  wire id_ex_flush;
  (* src = "RTL/pipeline_control_unit.v:6.16-6.27" *)
  output if_id_write;
  wire if_id_write;
  (* src = "RTL/pipeline_control_unit.v:5.17-5.25" *)
  output pc_write;
  wire pc_write;
  (* src = "RTL/pipeline_control_unit.v:2.17-2.30" *)
  input stall_request;
  wire stall_request;
  assign _0_ = stall_request ? (* full_case = 32'd1 *) (* src = "RTL/pipeline_control_unit.v:19.18-19.31|RTL/pipeline_control_unit.v:19.14-23.12" *) 1'h1 : 1'h0;
  assign _1_ = stall_request ? (* full_case = 32'd1 *) (* src = "RTL/pipeline_control_unit.v:19.18-19.31|RTL/pipeline_control_unit.v:19.14-23.12" *) 1'h0 : 1'h1;
  assign id_ex_flush = flush_request ? (* full_case = 32'd1 *) (* src = "RTL/pipeline_control_unit.v:15.13-15.26|RTL/pipeline_control_unit.v:15.9-23.12" *) 1'h1 : _0_;
  assign if_id_write = flush_request ? (* full_case = 32'd1 *) (* src = "RTL/pipeline_control_unit.v:15.13-15.26|RTL/pipeline_control_unit.v:15.9-23.12" *) 1'h1 : _1_;
  assign pc_write = if_id_write;
endmodule

(* top =  1  *)
(* src = "RTL/pipelined_alu_top.v:1.1-186.10" *)
module pipelined_alu_top(clk, rst, stall_request, flush_request, fetch_pc, fetch_instruction, decode_rs1_value, decode_rs2_value, decode_immediate, decode_rs1, decode_rs2, decode_rd, decode_alu_control, decode_reg_write, decode_mem_read, decode_mem_write, decode_mem_to_reg, decode_alu_src, execute_result, execute_store_data, execute_zero
, memory_read_data, wb_alu_result, wb_memory_data, wb_rd, wb_reg_write, wb_mem_to_reg);
  (* src = "RTL/pipelined_alu_top.v:87.16-87.28" *)
  wire _0_;
  (* src = "RTL/pipelined_alu_top.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "RTL/pipelined_alu_top.v:18.23-18.41" *)
  input [3:0] decode_alu_control;
  wire [3:0] decode_alu_control;
  (* src = "RTL/pipelined_alu_top.v:23.16-23.30" *)
  input decode_alu_src;
  wire decode_alu_src;
  (* src = "RTL/pipelined_alu_top.v:13.23-13.39" *)
  input [31:0] decode_immediate;
  wire [31:0] decode_immediate;
  (* src = "RTL/pipelined_alu_top.v:20.16-20.31" *)
  input decode_mem_read;
  wire decode_mem_read;
  (* src = "RTL/pipelined_alu_top.v:22.16-22.33" *)
  input decode_mem_to_reg;
  wire decode_mem_to_reg;
  (* src = "RTL/pipelined_alu_top.v:21.16-21.32" *)
  input decode_mem_write;
  wire decode_mem_write;
  (* src = "RTL/pipelined_alu_top.v:16.22-16.31" *)
  input [4:0] decode_rd;
  wire [4:0] decode_rd;
  (* src = "RTL/pipelined_alu_top.v:19.16-19.32" *)
  input decode_reg_write;
  wire decode_reg_write;
  (* src = "RTL/pipelined_alu_top.v:14.22-14.32" *)
  input [4:0] decode_rs1;
  wire [4:0] decode_rs1;
  (* src = "RTL/pipelined_alu_top.v:11.23-11.39" *)
  input [31:0] decode_rs1_value;
  wire [31:0] decode_rs1_value;
  (* src = "RTL/pipelined_alu_top.v:15.22-15.32" *)
  input [4:0] decode_rs2;
  wire [4:0] decode_rs2;
  (* src = "RTL/pipelined_alu_top.v:12.23-12.39" *)
  input [31:0] decode_rs2_value;
  wire [31:0] decode_rs2_value;
  (* src = "RTL/pipelined_alu_top.v:59.17-59.34" *)
  wire [31:0] ex_mem_alu_result;
  (* src = "RTL/pipelined_alu_top.v:65.10-65.25" *)
  (* unused_bits = "0" *)
  wire ex_mem_mem_read;
  (* src = "RTL/pipelined_alu_top.v:67.10-67.27" *)
  wire ex_mem_mem_to_reg;
  (* src = "RTL/pipelined_alu_top.v:66.10-66.26" *)
  (* unused_bits = "0" *)
  wire ex_mem_mem_write;
  (* src = "RTL/pipelined_alu_top.v:61.16-61.25" *)
  wire [4:0] ex_mem_rd;
  (* src = "RTL/pipelined_alu_top.v:64.10-64.26" *)
  wire ex_mem_reg_write;
  (* src = "RTL/pipelined_alu_top.v:60.17-60.34" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] ex_mem_store_data;
  (* src = "RTL/pipelined_alu_top.v:62.10-62.21" *)
  (* unused_bits = "0" *)
  wire ex_mem_zero;
  (* src = "RTL/pipelined_alu_top.v:25.23-25.37" *)
  input [31:0] execute_result;
  wire [31:0] execute_result;
  (* src = "RTL/pipelined_alu_top.v:26.23-26.41" *)
  input [31:0] execute_store_data;
  wire [31:0] execute_store_data;
  (* src = "RTL/pipelined_alu_top.v:27.16-27.28" *)
  input execute_zero;
  wire execute_zero;
  (* src = "RTL/pipelined_alu_top.v:9.23-9.40" *)
  input [31:0] fetch_instruction;
  wire [31:0] fetch_instruction;
  (* src = "RTL/pipelined_alu_top.v:8.23-8.31" *)
  input [31:0] fetch_pc;
  wire [31:0] fetch_pc;
  (* src = "RTL/pipelined_alu_top.v:6.16-6.29" *)
  input flush_request;
  wire flush_request;
  (* src = "RTL/pipelined_alu_top.v:52.16-52.33" *)
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] id_ex_alu_control;
  (* src = "RTL/pipelined_alu_top.v:57.10-57.23" *)
  (* unused_bits = "0" *)
  wire id_ex_alu_src;
  (* src = "RTL/pipelined_alu_top.v:39.10-39.21" *)
  wire id_ex_flush;
  (* src = "RTL/pipelined_alu_top.v:46.17-46.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] id_ex_immediate;
  (* src = "RTL/pipelined_alu_top.v:54.10-54.24" *)
  wire id_ex_mem_read;
  (* src = "RTL/pipelined_alu_top.v:56.10-56.26" *)
  wire id_ex_mem_to_reg;
  (* src = "RTL/pipelined_alu_top.v:55.10-55.25" *)
  wire id_ex_mem_write;
  (* src = "RTL/pipelined_alu_top.v:43.17-43.25" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] id_ex_pc;
  (* src = "RTL/pipelined_alu_top.v:50.16-50.24" *)
  wire [4:0] id_ex_rd;
  (* src = "RTL/pipelined_alu_top.v:53.10-53.25" *)
  wire id_ex_reg_write;
  (* src = "RTL/pipelined_alu_top.v:48.16-48.25" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] id_ex_rs1;
  (* src = "RTL/pipelined_alu_top.v:44.17-44.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] id_ex_rs1_value;
  (* src = "RTL/pipelined_alu_top.v:49.16-49.25" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [4:0] id_ex_rs2;
  (* src = "RTL/pipelined_alu_top.v:45.17-45.32" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] id_ex_rs2_value;
  (* src = "RTL/pipelined_alu_top.v:42.17-42.34" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] if_id_instruction;
  (* src = "RTL/pipelined_alu_top.v:41.17-41.25" *)
  wire [31:0] if_id_pc;
  (* src = "RTL/pipelined_alu_top.v:38.10-38.21" *)
  wire if_id_write;
  (* src = "RTL/pipelined_alu_top.v:70.17-70.34" *)
  wire [31:0] mem_wb_alu_result;
  (* src = "RTL/pipelined_alu_top.v:69.17-69.28" *)
  wire [31:0] mem_wb_data;
  (* src = "RTL/pipelined_alu_top.v:74.10-74.27" *)
  wire mem_wb_mem_to_reg;
  (* src = "RTL/pipelined_alu_top.v:71.16-71.25" *)
  wire [4:0] mem_wb_rd;
  (* src = "RTL/pipelined_alu_top.v:73.10-73.26" *)
  wire mem_wb_reg_write;
  (* src = "RTL/pipelined_alu_top.v:28.23-28.39" *)
  input [31:0] memory_read_data;
  wire [31:0] memory_read_data;
  (* src = "RTL/pipelined_alu_top.v:37.10-37.18" *)
  (* unused_bits = "0" *)
  wire pc_write;
  (* src = "RTL/pipelined_alu_top.v:3.16-3.19" *)
  input rst;
  wire rst;
  (* src = "RTL/pipelined_alu_top.v:5.16-5.29" *)
  input stall_request;
  wire stall_request;
  (* src = "RTL/pipelined_alu_top.v:30.24-30.37" *)
  output [31:0] wb_alu_result;
  wire [31:0] wb_alu_result;
  (* src = "RTL/pipelined_alu_top.v:34.17-34.30" *)
  output wb_mem_to_reg;
  wire wb_mem_to_reg;
  (* src = "RTL/pipelined_alu_top.v:31.24-31.38" *)
  output [31:0] wb_memory_data;
  wire [31:0] wb_memory_data;
  (* src = "RTL/pipelined_alu_top.v:32.24-32.29" *)
  output [4:0] wb_rd;
  wire [4:0] wb_rd;
  (* src = "RTL/pipelined_alu_top.v:33.17-33.29" *)
  output wb_reg_write;
  wire wb_reg_write;
  assign _0_ = ~ (* src = "RTL/pipelined_alu_top.v:87.16-87.28" *) if_id_write;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/pipelined_alu_top.v:76.27-82.6" *)
  pipeline_control_unit control_unit (
    .flush_request(flush_request),
    .id_ex_flush(id_ex_flush),
    .if_id_write(if_id_write),
    .pc_write(pc_write),
    .stall_request(stall_request)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/pipelined_alu_top.v:132.30-157.6" *)
  ex_mem_pipeline_register ex_mem (
    .alu_result_in(execute_result),
    .alu_result_out(ex_mem_alu_result),
    .clk(clk),
    .flush(flush_request),
    .mem_read_in(id_ex_mem_read),
    .mem_read_out(ex_mem_mem_read),
    .mem_to_reg_in(id_ex_mem_to_reg),
    .mem_to_reg_out(ex_mem_mem_to_reg),
    .mem_write_in(id_ex_mem_write),
    .mem_write_out(ex_mem_mem_write),
    .rd_in(id_ex_rd),
    .rd_out(ex_mem_rd),
    .reg_write_in(id_ex_reg_write),
    .reg_write_out(ex_mem_reg_write),
    .rst(rst),
    .stall(1'h0),
    .store_data_in(execute_store_data),
    .store_data_out(ex_mem_store_data),
    .zero_in(execute_zero),
    .zero_out(ex_mem_zero)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/pipelined_alu_top.v:95.29-130.6" *)
  id_ex_pipeline_register id_ex (
    .alu_control_in(decode_alu_control),
    .alu_control_out(id_ex_alu_control),
    .alu_src_in(decode_alu_src),
    .alu_src_out(id_ex_alu_src),
    .clk(clk),
    .flush(id_ex_flush),
    .immediate_in(decode_immediate),
    .immediate_out(id_ex_immediate),
    .mem_read_in(decode_mem_read),
    .mem_read_out(id_ex_mem_read),
    .mem_to_reg_in(decode_mem_to_reg),
    .mem_to_reg_out(id_ex_mem_to_reg),
    .mem_write_in(decode_mem_write),
    .mem_write_out(id_ex_mem_write),
    .pc_in(if_id_pc),
    .pc_out(id_ex_pc),
    .rd_in(decode_rd),
    .rd_out(id_ex_rd),
    .reg_write_in(decode_reg_write),
    .reg_write_out(id_ex_reg_write),
    .rs1_in(decode_rs1),
    .rs1_out(id_ex_rs1),
    .rs1_value_in(decode_rs1_value),
    .rs1_value_out(id_ex_rs1_value),
    .rs2_in(decode_rs2),
    .rs2_out(id_ex_rs2),
    .rs2_value_in(decode_rs2_value),
    .rs2_value_out(id_ex_rs2_value),
    .rst(rst),
    .stall(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/pipelined_alu_top.v:84.29-93.6" *)
  if_id_pipeline_register if_id (
    .clk(clk),
    .flush(flush_request),
    .instruction_in(fetch_instruction),
    .instruction_out(if_id_instruction),
    .pc_in(fetch_pc),
    .pc_out(if_id_pc),
    .rst(rst),
    .stall(_0_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/pipelined_alu_top.v:159.30-178.6" *)
  mem_wb_pipeline_register mem_wb (
    .alu_result_in(ex_mem_alu_result),
    .alu_result_out(mem_wb_alu_result),
    .clk(clk),
    .flush(flush_request),
    .mem_data_in(memory_read_data),
    .mem_data_out(mem_wb_data),
    .mem_to_reg_in(ex_mem_mem_to_reg),
    .mem_to_reg_out(mem_wb_mem_to_reg),
    .rd_in(ex_mem_rd),
    .rd_out(mem_wb_rd),
    .reg_write_in(ex_mem_reg_write),
    .reg_write_out(mem_wb_reg_write),
    .rst(rst),
    .stall(1'h0)
  );
  assign wb_alu_result = mem_wb_alu_result;
  assign wb_mem_to_reg = mem_wb_mem_to_reg;
  assign wb_memory_data = mem_wb_data;
  assign wb_rd = mem_wb_rd;
  assign wb_reg_write = mem_wb_reg_write;
endmodule
