/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/branch_control_unit.v:1.1-21.10" *)
module branch_control_unit(branch_enable, branch_taken, current_pc, branch_offset, flush_pipeline, target_pc);
  (* src = "RTL/branch_control_unit.v:13.17-13.35" *)
  wire [31:0] _0_;
  (* src = "RTL/branch_control_unit.v:17.21-17.47" *)
  wire [31:0] _1_;
  (* src = "RTL/branch_control_unit.v:15.9-15.38" *)
  wire _2_;
  (* src = "RTL/branch_control_unit.v:2.17-2.30" *)
  input branch_enable;
  wire branch_enable;
  (* src = "RTL/branch_control_unit.v:5.24-5.37" *)
  input [31:0] branch_offset;
  wire [31:0] branch_offset;
  (* src = "RTL/branch_control_unit.v:3.17-3.29" *)
  input branch_taken;
  wire branch_taken;
  (* src = "RTL/branch_control_unit.v:4.24-4.34" *)
  input [31:0] current_pc;
  wire [31:0] current_pc;
  (* src = "RTL/branch_control_unit.v:7.16-7.30" *)
  output flush_pipeline;
  wire flush_pipeline;
  (* src = "RTL/branch_control_unit.v:8.23-8.32" *)
  output [31:0] target_pc;
  wire [31:0] target_pc;
  assign _0_ = current_pc + (* src = "RTL/branch_control_unit.v:13.17-13.35" *) 32'd4;
  assign _1_ = current_pc + (* src = "RTL/branch_control_unit.v:17.21-17.47" *) branch_offset;
  assign _2_ = branch_enable && (* src = "RTL/branch_control_unit.v:15.9-15.38" *) branch_taken;
  assign target_pc = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/branch_control_unit.v:15.9-15.38|RTL/branch_control_unit.v:15.5-18.8" *) _1_ : _0_;
  assign flush_pipeline = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/branch_control_unit.v:15.9-15.38|RTL/branch_control_unit.v:15.5-18.8" *) 1'h1 : 1'h0;
endmodule
