/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/spi_chip_select.v:1.1-45.10" *)
module spi_chip_select(clk, rst, start, transfer_done, cs_n, busy);
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  wire _00_;
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "RTL/spi_chip_select.v:9.16-9.20" *)
  output busy;
  reg busy;
  (* src = "RTL/spi_chip_select.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_chip_select.v:8.16-8.20" *)
  output cs_n;
  reg cs_n;
  (* src = "RTL/spi_chip_select.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_chip_select.v:5.16-5.21" *)
  input start;
  wire start;
  (* src = "RTL/spi_chip_select.v:6.16-6.29" *)
  input transfer_done;
  wire transfer_done;
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cs_n <= 1'h1;
    else if (_02_) cs_n <= _01_;
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_02_) busy <= _00_;
  assign _02_ = | { transfer_done, start };
  assign _01_ = start ? (* full_case = 32'd1 *) (* src = "RTL/spi_chip_select.v:27.12-27.17|RTL/spi_chip_select.v:27.9-42.12" *) 1'h0 : _04_;
  assign _03_ = transfer_done ? (* src = "RTL/spi_chip_select.v:36.17-36.30|RTL/spi_chip_select.v:36.14-42.12" *) 1'h0 : 1'hx;
  assign _00_ = start ? (* full_case = 32'd1 *) (* src = "RTL/spi_chip_select.v:27.12-27.17|RTL/spi_chip_select.v:27.9-42.12" *) 1'h1 : _03_;
  assign _04_ = transfer_done ? (* src = "RTL/spi_chip_select.v:36.17-36.30|RTL/spi_chip_select.v:36.14-42.12" *) 1'h1 : 1'hx;
endmodule
