/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/spi_master_fsm.v:1.1-114.10" *)
module spi_master_fsm(clk, rst, start, shift_done, load, cs_start, shift_enable, transfer_done, busy);
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _00_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _01_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _02_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _03_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire [2:0] _04_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [2:0] _14_;
  wire _15_;
  wire [2:0] _16_;
  wire _17_;
  wire _18_;
  (* src = "RTL/spi_master_fsm.v:12.16-12.20" *)
  output busy;
  reg busy;
  (* src = "RTL/spi_master_fsm.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master_fsm.v:9.16-9.24" *)
  output cs_start;
  reg cs_start;
  (* src = "RTL/spi_master_fsm.v:8.16-8.20" *)
  output load;
  reg load;
  (* src = "RTL/spi_master_fsm.v:4.17-4.20" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master_fsm.v:6.17-6.27" *)
  input shift_done;
  wire shift_done;
  (* src = "RTL/spi_master_fsm.v:10.16-10.28" *)
  output shift_enable;
  reg shift_enable;
  (* src = "RTL/spi_master_fsm.v:5.17-5.22" *)
  input start;
  wire start;
  (* src = "RTL/spi_master_fsm.v:22.11-22.16" *)
  reg [2:0] state;
  (* src = "RTL/spi_master_fsm.v:11.16-11.29" *)
  output transfer_done;
  reg transfer_done;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_06_) busy <= _00_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_09_) state <= _04_;
  assign _06_ = | { _11_, _10_ };
  assign _07_ = { _17_, start } != 2'h2;
  assign _08_ = { _15_, shift_done } != 2'h2;
  assign _09_ = & { _08_, _07_ };
  assign _10_ = | { _18_, _17_ };
  assign _11_ = | { _15_, _13_, _12_ };
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load <= 1'h0;
    else load <= _02_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cs_start <= 1'h0;
    else cs_start <= _01_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_enable <= 1'h0;
    else shift_enable <= _03_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) transfer_done <= 1'h0;
    else transfer_done <= _05_;
  assign _01_ = _12_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
  assign _02_ = _13_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
  assign _14_ = shift_done ? (* src = "RTL/spi_master_fsm.v:89.16-89.26|RTL/spi_master_fsm.v:89.13-90.35" *) 3'h4 : 3'hx;
  function [2:0] _34_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _34_ = b[2:0];
      4'b??1?:
        _34_ = b[5:3];
      4'b?1??:
        _34_ = b[8:6];
      4'b1???:
        _34_ = b[11:9];
      default:
        _34_ = a;
    endcase
  endfunction
  assign _04_ = _34_(3'h0, { _16_, 6'h13, _14_ }, { _17_, _13_, _12_, _15_ });
  assign _16_ = start ? (* src = "RTL/spi_master_fsm.v:57.16-57.21|RTL/spi_master_fsm.v:57.13-58.33" *) 3'h1 : 3'hx;
  assign _05_ = _18_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
  function [0:0] _37_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _37_ = b[0:0];
      2'b1?:
        _37_ = b[1:1];
      default:
        _37_ = a;
    endcase
  endfunction
  assign _00_ = _37_(1'hx, 2'h2, { _11_, _10_ });
  assign _18_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h4;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h3;
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h2;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h1;
  assign _17_ = ! (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) state;
  assign _03_ = _15_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
endmodule
