/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* hdlname = "\\spi_clock_generator" *)
(* src = "RTL/spi_clock_generator.v:1.1-48.10" *)
module \$paramod\spi_clock_generator\DIVIDER=s32'00000000000000000000000000000100 (clk, rst, spi_clk);
  (* src = "RTL/spi_clock_generator.v:21.1-47.4" *)
  wire [31:0] _0_;
  (* src = "RTL/spi_clock_generator.v:44.24-44.35" *)
  wire [31:0] _1_;
  (* src = "RTL/spi_clock_generator.v:34.12-34.36" *)
  wire _2_;
  (* src = "RTL/spi_clock_generator.v:38.24-38.32" *)
  wire _3_;
  (* src = "RTL/spi_clock_generator.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_clock_generator.v:17.12-17.19" *)
  reg [31:0] counter;
  (* src = "RTL/spi_clock_generator.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_clock_generator.v:12.12-12.19" *)
  output spi_clk;
  reg spi_clk;
  assign _1_ = counter + (* src = "RTL/spi_clock_generator.v:44.24-44.35" *) 32'd1;
  (* src = "RTL/spi_clock_generator.v:21.1-47.4" *)
  always @(posedge clk, posedge rst)
    if (rst) spi_clk <= 1'h0;
    else if (_2_) spi_clk <= _3_;
  assign _2_ = counter == (* src = "RTL/spi_clock_generator.v:34.12-34.36" *) 32'd1;
  assign _3_ = ~ (* src = "RTL/spi_clock_generator.v:38.24-38.32" *) spi_clk;
  (* src = "RTL/spi_clock_generator.v:21.1-47.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 32'd0;
    else counter <= _0_;
  assign _0_ = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_clock_generator.v:34.12-34.36|RTL/spi_clock_generator.v:34.9-45.12" *) 32'd0 : _1_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\spi_shift_register" *)
(* src = "RTL/spi_shift_register.v:1.1-88.10" *)
module \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000 (clk, rst, load, shift, tx_data, miso, mosi, rx_data, done);
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  wire [3:0] _00_;
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  wire _01_;
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  wire [7:0] _02_;
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  wire [7:0] _03_;
  (* src = "RTL/spi_shift_register.v:73.26-73.39" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "RTL/spi_shift_register.v:75.16-75.41" *)
  wire _08_;
  wire _09_;
  wire _10_;
  wire [3:0] _11_;
  wire [3:0] _12_;
  wire [7:0] _13_;
  wire [7:0] _14_;
  (* src = "RTL/spi_shift_register.v:26.11-26.20" *)
  reg [3:0] bit_count;
  (* src = "RTL/spi_shift_register.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_shift_register.v:18.12-18.16" *)
  output done;
  reg done;
  (* src = "RTL/spi_shift_register.v:11.12-11.16" *)
  input load;
  wire load;
  (* src = "RTL/spi_shift_register.v:15.12-15.16" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_shift_register.v:16.13-16.17" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_shift_register.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_shift_register.v:17.29-17.36" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/spi_shift_register.v:25.22-25.30" *)
  (* unused_bits = "7" *)
  reg [7:0] rx_shift;
  (* src = "RTL/spi_shift_register.v:12.12-12.17" *)
  input shift;
  wire shift;
  (* src = "RTL/spi_shift_register.v:13.29-13.36" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "RTL/spi_shift_register.v:24.22-24.30" *)
  reg [7:0] tx_shift;
  assign _04_ = bit_count + (* src = "RTL/spi_shift_register.v:73.26-73.39" *) 32'd1;
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_06_) rx_data <= { rx_shift[6:0], miso };
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  always @(posedge clk, posedge rst)
    if (rst) tx_shift <= 8'h00;
    else if (_05_) tx_shift <= _03_;
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_shift <= 8'h00;
    else if (_05_) rx_shift <= _02_;
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 4'h0;
    else if (_05_) bit_count <= _00_;
  assign _05_ = | { shift, load };
  assign _07_ = ~ load;
  assign _06_ = & { _07_, _08_, shift };
  assign _08_ = bit_count == (* src = "RTL/spi_shift_register.v:75.16-75.41" *) 4'h7;
  (* src = "RTL/spi_shift_register.v:34.1-87.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _09_ = _08_ ? (* src = "RTL/spi_shift_register.v:75.16-75.41|RTL/spi_shift_register.v:75.13-84.16" *) 1'h1 : 1'h0;
  assign _10_ = shift ? (* src = "RTL/spi_shift_register.v:68.17-68.22|RTL/spi_shift_register.v:68.14-85.12" *) _09_ : 1'h0;
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:57.12-57.16|RTL/spi_shift_register.v:57.9-85.12" *) 1'h0 : _10_;
  assign _11_ = _08_ ? (* src = "RTL/spi_shift_register.v:75.16-75.41|RTL/spi_shift_register.v:75.13-84.16" *) 4'h0 : _04_[3:0];
  assign _12_ = shift ? (* src = "RTL/spi_shift_register.v:68.17-68.22|RTL/spi_shift_register.v:68.14-85.12" *) _11_ : 4'hx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:57.12-57.16|RTL/spi_shift_register.v:57.9-85.12" *) 4'h0 : _12_;
  assign _13_ = shift ? (* src = "RTL/spi_shift_register.v:68.17-68.22|RTL/spi_shift_register.v:68.14-85.12" *) { rx_shift[6:0], miso } : 8'hxx;
  assign _02_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:57.12-57.16|RTL/spi_shift_register.v:57.9-85.12" *) 8'h00 : _13_;
  assign _14_ = shift ? (* src = "RTL/spi_shift_register.v:68.17-68.22|RTL/spi_shift_register.v:68.14-85.12" *) { tx_shift[6:0], 1'h0 } : 8'hxx;
  assign _03_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:57.12-57.16|RTL/spi_shift_register.v:57.9-85.12" *) tx_data : _14_;
  assign mosi = tx_shift[7];
endmodule

(* src = "RTL/spi_chip_select.v:1.1-45.10" *)
module spi_chip_select(clk, rst, start, transfer_done, cs_n, busy);
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  wire _00_;
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "RTL/spi_chip_select.v:9.16-9.20" *)
  output busy;
  reg busy;
  (* src = "RTL/spi_chip_select.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_chip_select.v:8.16-8.20" *)
  output cs_n;
  reg cs_n;
  (* src = "RTL/spi_chip_select.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_chip_select.v:5.16-5.21" *)
  input start;
  wire start;
  (* src = "RTL/spi_chip_select.v:6.16-6.29" *)
  input transfer_done;
  wire transfer_done;
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cs_n <= 1'h1;
    else if (_02_) cs_n <= _01_;
  (* src = "RTL/spi_chip_select.v:13.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_02_) busy <= _00_;
  assign _02_ = | { transfer_done, start };
  assign _03_ = transfer_done ? (* src = "RTL/spi_chip_select.v:36.17-36.30|RTL/spi_chip_select.v:36.14-42.12" *) 1'h0 : 1'hx;
  assign _00_ = start ? (* full_case = 32'd1 *) (* src = "RTL/spi_chip_select.v:27.12-27.17|RTL/spi_chip_select.v:27.9-42.12" *) 1'h1 : _03_;
  assign _04_ = transfer_done ? (* src = "RTL/spi_chip_select.v:36.17-36.30|RTL/spi_chip_select.v:36.14-42.12" *) 1'h1 : 1'hx;
  assign _01_ = start ? (* full_case = 32'd1 *) (* src = "RTL/spi_chip_select.v:27.12-27.17|RTL/spi_chip_select.v:27.9-42.12" *) 1'h0 : _04_;
endmodule

(* src = "RTL/spi_master_fsm.v:1.1-114.10" *)
module spi_master_fsm(clk, rst, start, shift_done, load, cs_start, shift_enable, transfer_done, busy);
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _00_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _01_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _02_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _03_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire [2:0] _04_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [2:0] _16_;
  wire [2:0] _17_;
  wire _18_;
  (* src = "RTL/spi_master_fsm.v:12.16-12.20" *)
  output busy;
  reg busy;
  (* src = "RTL/spi_master_fsm.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master_fsm.v:9.16-9.24" *)
  output cs_start;
  reg cs_start;
  (* src = "RTL/spi_master_fsm.v:8.16-8.20" *)
  output load;
  reg load;
  (* src = "RTL/spi_master_fsm.v:4.17-4.20" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master_fsm.v:6.17-6.27" *)
  input shift_done;
  wire shift_done;
  (* src = "RTL/spi_master_fsm.v:10.16-10.28" *)
  output shift_enable;
  reg shift_enable;
  (* src = "RTL/spi_master_fsm.v:5.17-5.22" *)
  input start;
  wire start;
  (* src = "RTL/spi_master_fsm.v:22.11-22.16" *)
  reg [2:0] state;
  (* src = "RTL/spi_master_fsm.v:11.16-11.29" *)
  output transfer_done;
  reg transfer_done;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_06_) busy <= _00_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_09_) state <= _04_;
  assign _06_ = | { _11_, _10_ };
  assign _07_ = { _18_, start } != 2'h2;
  assign _08_ = { _13_, shift_done } != 2'h2;
  assign _09_ = & { _07_, _08_ };
  assign _10_ = | { _18_, _12_ };
  assign _11_ = | { _15_, _14_, _13_ };
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) transfer_done <= 1'h0;
    else transfer_done <= _05_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load <= 1'h0;
    else load <= _02_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cs_start <= 1'h0;
    else cs_start <= _01_;
  (* src = "RTL/spi_master_fsm.v:25.1-113.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_enable <= 1'h0;
    else shift_enable <= _03_;
  assign _05_ = _12_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
  assign _03_ = _13_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
  assign _01_ = _14_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
  assign _02_ = _15_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 1'h1 : 1'h0;
  assign _16_ = shift_done ? (* src = "RTL/spi_master_fsm.v:89.16-89.26|RTL/spi_master_fsm.v:89.13-90.35" *) 3'h4 : 3'hx;
  function [2:0] _36_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _36_ = b[2:0];
      4'b??1?:
        _36_ = b[5:3];
      4'b?1??:
        _36_ = b[8:6];
      4'b1???:
        _36_ = b[11:9];
      default:
        _36_ = a;
    endcase
  endfunction
  assign _04_ = _36_(3'h0, { _17_, 6'h13, _16_ }, { _18_, _15_, _14_, _13_ });
  assign _17_ = start ? (* src = "RTL/spi_master_fsm.v:57.16-57.21|RTL/spi_master_fsm.v:57.13-58.33" *) 3'h1 : 3'hx;
  function [0:0] _38_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _38_ = b[0:0];
      2'b1?:
        _38_ = b[1:1];
      default:
        _38_ = a;
    endcase
  endfunction
  assign _00_ = _38_(1'hx, 2'h2, { _11_, _10_ });
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h4;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h3;
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h2;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) 3'h1;
  assign _18_ = ! (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:50.9-111.16" *) state;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/spi_master_top.v:1.1-107.10" *)
module spi_master_top(clk, rst, start, tx_data, miso, mosi, spi_clk, cs_n, rx_data, busy);
  (* src = "RTL/spi_master_top.v:21.13-21.17" *)
  output busy;
  wire busy;
  (* src = "RTL/spi_master_top.v:11.12-11.15" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master_top.v:19.13-19.17" *)
  output cs_n;
  wire cs_n;
  (* src = "RTL/spi_master_top.v:29.6-29.14" *)
  wire cs_start;
  (* src = "RTL/spi_master_top.v:26.6-26.10" *)
  wire load;
  (* src = "RTL/spi_master_top.v:15.12-15.16" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_master_top.v:17.13-17.17" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_master_top.v:12.12-12.15" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master_top.v:20.30-20.37" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "RTL/spi_master_top.v:30.6-30.16" *)
  wire shift_done;
  (* src = "RTL/spi_master_top.v:27.6-27.18" *)
  wire shift_enable;
  (* src = "RTL/spi_master_top.v:18.13-18.20" *)
  output spi_clk;
  wire spi_clk;
  (* src = "RTL/spi_master_top.v:13.12-13.17" *)
  input start;
  wire start;
  (* src = "RTL/spi_master_top.v:28.6-28.19" *)
  wire transfer_done;
  (* src = "RTL/spi_master_top.v:14.29-14.36" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_master_top.v:75.1-86.2" *)
  spi_chip_select chip_select (
    .clk(clk),
    .cs_n(cs_n),
    .rst(rst),
    .start(cs_start),
    .transfer_done(transfer_done)
  );
  (* src = "RTL/spi_master_top.v:40.1-48.2" *)
  \$paramod\spi_clock_generator\DIVIDER=s32'00000000000000000000000000000100  clock_gen (
    .clk(clk),
    .rst(rst),
    .spi_clk(spi_clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_master_top.v:91.1-106.2" *)
  spi_master_fsm fsm (
    .busy(busy),
    .clk(clk),
    .cs_start(cs_start),
    .load(load),
    .rst(rst),
    .shift_done(shift_done),
    .shift_enable(shift_enable),
    .start(start),
    .transfer_done(transfer_done)
  );
  (* src = "RTL/spi_master_top.v:58.1-71.2" *)
  \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000  shift_reg (
    .clk(spi_clk),
    .done(shift_done),
    .load(load),
    .miso(miso),
    .mosi(mosi),
    .rst(rst),
    .rx_data(rx_data),
    .shift(shift_enable),
    .tx_data(tx_data)
  );
endmodule
