/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/spi_clock_generator.v:1.1-48.10" *)
module spi_clock_generator(clk, rst, spi_clk);
  (* src = "RTL/spi_clock_generator.v:21.1-47.4" *)
  wire [31:0] _0_;
  (* src = "RTL/spi_clock_generator.v:44.24-44.35" *)
  wire [31:0] _1_;
  (* src = "RTL/spi_clock_generator.v:34.12-34.36" *)
  wire _2_;
  (* src = "RTL/spi_clock_generator.v:38.24-38.32" *)
  wire _3_;
  (* src = "RTL/spi_clock_generator.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_clock_generator.v:17.12-17.19" *)
  reg [31:0] counter;
  (* src = "RTL/spi_clock_generator.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_clock_generator.v:12.12-12.19" *)
  output spi_clk;
  reg spi_clk;
  assign _1_ = counter + (* src = "RTL/spi_clock_generator.v:44.24-44.35" *) 32'd1;
  (* src = "RTL/spi_clock_generator.v:21.1-47.4" *)
  always @(posedge clk, posedge rst)
    if (rst) spi_clk <= 1'h0;
    else if (_2_) spi_clk <= _3_;
  assign _2_ = counter == (* src = "RTL/spi_clock_generator.v:34.12-34.36" *) 32'd1;
  assign _3_ = ~ (* src = "RTL/spi_clock_generator.v:38.24-38.32" *) spi_clk;
  (* src = "RTL/spi_clock_generator.v:21.1-47.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 32'd0;
    else counter <= _0_;
  assign _0_ = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_clock_generator.v:34.12-34.36|RTL/spi_clock_generator.v:34.9-45.12" *) 32'd0 : _1_;
endmodule
