/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/interrupt_mask_register.v:1.1-35.10" *)
module interrupt_mask_register(clk, rst, mask_write, mask_data, mask_register);
  (* src = "RTL/interrupt_mask_register.v:6.16-6.19" *)
  input clk;
  wire clk;
  (* src = "RTL/interrupt_mask_register.v:9.31-9.40" *)
  input [7:0] mask_data;
  wire [7:0] mask_data;
  (* src = "RTL/interrupt_mask_register.v:11.31-11.44" *)
  output [7:0] mask_register;
  reg [7:0] mask_register;
  (* src = "RTL/interrupt_mask_register.v:8.16-8.26" *)
  input mask_write;
  wire mask_write;
  (* src = "RTL/interrupt_mask_register.v:7.16-7.19" *)
  input rst;
  wire rst;
  (* src = "RTL/interrupt_mask_register.v:14.1-34.4" *)
  always @(posedge clk, posedge rst)
    if (rst) mask_register <= 8'hff;
    else if (mask_write) mask_register <= mask_data;
endmodule
