/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\interrupt_mask_register" *)
(* src = "RTL/interrupt_mask_register.v:1.1-35.10" *)
module \$paramod\interrupt_mask_register\NUM_IRQS=s32'00000000000000000000000000001000 (clk, rst, mask_write, mask_data, mask_register);
  (* src = "RTL/interrupt_mask_register.v:6.16-6.19" *)
  input clk;
  wire clk;
  (* src = "RTL/interrupt_mask_register.v:9.31-9.40" *)
  input [7:0] mask_data;
  wire [7:0] mask_data;
  (* src = "RTL/interrupt_mask_register.v:11.31-11.44" *)
  output [7:0] mask_register;
  reg [7:0] mask_register;
  (* src = "RTL/interrupt_mask_register.v:8.16-8.26" *)
  input mask_write;
  wire mask_write;
  (* src = "RTL/interrupt_mask_register.v:7.16-7.19" *)
  input rst;
  wire rst;
  (* src = "RTL/interrupt_mask_register.v:14.1-34.4" *)
  always @(posedge clk, posedge rst)
    if (rst) mask_register <= 8'hff;
    else if (mask_write) mask_register <= mask_data;
endmodule

(* dynports =  1  *)
(* hdlname = "\\interrupt_priority_encoder" *)
(* src = "RTL/interrupt_priority_encoder.v:1.1-56.10" *)
module \$paramod\interrupt_priority_encoder\NUM_IRQS=s32'00000000000000000000000000001000 (pending_irq, valid, interrupt_id);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "RTL/interrupt_priority_encoder.v:9.22-9.34" *)
  output [2:0] interrupt_id;
  wire [2:0] interrupt_id;
  (* src = "RTL/interrupt_priority_encoder.v:6.31-6.42" *)
  input [7:0] pending_irq;
  wire [7:0] pending_irq;
  (* src = "RTL/interrupt_priority_encoder.v:8.16-8.21" *)
  output valid;
  wire valid;
  assign _00_ = | { _07_, _06_, _05_, _04_, _03_, _02_, _01_, pending_irq[7] };
  function [2:0] _09_;
    input [2:0] a;
    input [20:0] b;
    input [6:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *)
    (* parallel_case *)
    casez (s)
      7'b??????1:
        _09_ = b[2:0];
      7'b?????1?:
        _09_ = b[5:3];
      7'b????1??:
        _09_ = b[8:6];
      7'b???1???:
        _09_ = b[11:9];
      7'b??1????:
        _09_ = b[14:12];
      7'b?1?????:
        _09_ = b[17:15];
      7'b1??????:
        _09_ = b[20:18];
      default:
        _09_ = a;
    endcase
  endfunction
  assign interrupt_id = _09_(3'h0, 21'h1f58d1, { pending_irq[7], _06_, _05_, _04_, _03_, _02_, _01_ });
  assign valid = _00_ ? (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 1'h1 : 1'h0;
  assign _07_ = pending_irq == (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 8'h01;
  assign _01_ = pending_irq[7:1] == (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 7'h01;
  assign _02_ = pending_irq[7:2] == (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 6'h01;
  assign _03_ = pending_irq[7:3] == (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 5'h01;
  assign _04_ = pending_irq[7:4] == (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 4'h1;
  assign _05_ = pending_irq[7:5] == (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 3'h1;
  assign _06_ = pending_irq[7:6] == (* full_case = 32'd1 *) (* src = "RTL/interrupt_priority_encoder.v:0.0-0.0|RTL/interrupt_priority_encoder.v:18.5-53.12" *) 2'h1;
endmodule

(* dynports =  1  *)
(* hdlname = "\\interrupt_request_register" *)
(* src = "RTL/interrupt_request_register.v:1.1-37.10" *)
module \$paramod\interrupt_request_register\NUM_IRQS=s32'00000000000000000000000000001000 (clk, rst, irq, clear, pending_irq);
  (* src = "RTL/interrupt_request_register.v:14.1-36.4" *)
  wire [7:0] _0_;
  (* src = "RTL/interrupt_request_register.v:32.47-32.53" *)
  wire [7:0] _1_;
  (* src = "RTL/interrupt_request_register.v:29.24-29.41" *)
  wire [7:0] _2_;
  (* src = "RTL/interrupt_request_register.v:9.31-9.36" *)
  input [7:0] clear;
  wire [7:0] clear;
  (* src = "RTL/interrupt_request_register.v:6.16-6.19" *)
  input clk;
  wire clk;
  (* src = "RTL/interrupt_request_register.v:8.31-8.34" *)
  input [7:0] irq;
  wire [7:0] irq;
  (* src = "RTL/interrupt_request_register.v:11.31-11.42" *)
  output [7:0] pending_irq;
  reg [7:0] pending_irq;
  (* src = "RTL/interrupt_request_register.v:7.16-7.19" *)
  input rst;
  wire rst;
  assign _0_ = _2_ & (* src = "RTL/interrupt_request_register.v:32.24-32.54" *) _1_;
  assign _1_ = ~ (* src = "RTL/interrupt_request_register.v:32.47-32.53" *) clear;
  assign _2_ = pending_irq | (* src = "RTL/interrupt_request_register.v:32.25-32.42" *) irq;
  (* src = "RTL/interrupt_request_register.v:14.1-36.4" *)
  always @(posedge clk, posedge rst)
    if (rst) pending_irq <= 8'h00;
    else pending_irq <= _0_;
endmodule

(* src = "RTL/interrupt_controller_fsm.v:1.1-93.10" *)
module interrupt_controller_fsm(clk, rst, valid, cpu_ack, cpu_interrupt, clear_interrupt, busy);
  (* src = "RTL/interrupt_controller_fsm.v:22.1-92.4" *)
  wire _00_;
  (* src = "RTL/interrupt_controller_fsm.v:22.1-92.4" *)
  wire _01_;
  (* src = "RTL/interrupt_controller_fsm.v:22.1-92.4" *)
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [1:0] _13_;
  wire [1:0] _14_;
  (* src = "RTL/interrupt_controller_fsm.v:10.16-10.20" *)
  output busy;
  reg busy;
  (* src = "RTL/interrupt_controller_fsm.v:9.16-9.31" *)
  output clear_interrupt;
  reg clear_interrupt;
  (* src = "RTL/interrupt_controller_fsm.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/interrupt_controller_fsm.v:6.16-6.23" *)
  input cpu_ack;
  wire cpu_ack;
  (* src = "RTL/interrupt_controller_fsm.v:8.16-8.29" *)
  output cpu_interrupt;
  wire cpu_interrupt;
  (* src = "RTL/interrupt_controller_fsm.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/interrupt_controller_fsm.v:19.11-19.16" *)
  reg [1:0] state;
  (* src = "RTL/interrupt_controller_fsm.v:5.16-5.21" *)
  input valid;
  wire valid;
  (* src = "RTL/interrupt_controller_fsm.v:22.1-92.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 2'h0;
    else if (_06_) state <= _02_;
  assign _03_ = { _12_, valid } != 2'h2;
  assign _04_ = { _10_, cpu_ack } != 2'h2;
  assign _05_ = | { _12_, _11_, _10_, _09_ };
  assign _06_ = & { _04_, _05_, _03_ };
  assign _07_ = | { _09_, _12_ };
  assign _08_ = | { _10_, _11_ };
  (* src = "RTL/interrupt_controller_fsm.v:22.1-92.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clear_interrupt <= 1'h0;
    else clear_interrupt <= _01_;
  (* src = "RTL/interrupt_controller_fsm.v:22.1-92.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else busy <= _00_;
  function [0:0] _24_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/interrupt_controller_fsm.v:0.0-0.0|RTL/interrupt_controller_fsm.v:43.9-89.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _24_ = b[0:0];
      2'b1?:
        _24_ = b[1:1];
      default:
        _24_ = a;
    endcase
  endfunction
  assign _00_ = _24_(1'hx, 2'h2, { _08_, _07_ });
  assign _01_ = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/interrupt_controller_fsm.v:0.0-0.0|RTL/interrupt_controller_fsm.v:43.9-89.16" *) 1'h1 : 1'h0;
  function [1:0] _26_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/interrupt_controller_fsm.v:0.0-0.0|RTL/interrupt_controller_fsm.v:43.9-89.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _26_ = b[1:0];
      4'b??1?:
        _26_ = b[3:2];
      4'b?1??:
        _26_ = b[5:4];
      4'b1???:
        _26_ = b[7:6];
      default:
        _26_ = a;
    endcase
  endfunction
  assign _02_ = _26_(2'hx, { _14_, 2'h2, _13_, 2'h0 }, { _12_, _11_, _10_, _09_ });
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/interrupt_controller_fsm.v:0.0-0.0|RTL/interrupt_controller_fsm.v:43.9-89.16" *) 2'h3;
  assign _13_ = cpu_ack ? (* src = "RTL/interrupt_controller_fsm.v:71.16-71.23|RTL/interrupt_controller_fsm.v:71.13-72.42" *) 2'h3 : 2'hx;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/interrupt_controller_fsm.v:0.0-0.0|RTL/interrupt_controller_fsm.v:43.9-89.16" *) 2'h2;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/interrupt_controller_fsm.v:0.0-0.0|RTL/interrupt_controller_fsm.v:43.9-89.16" *) 2'h1;
  assign _14_ = valid ? (* src = "RTL/interrupt_controller_fsm.v:51.16-51.21|RTL/interrupt_controller_fsm.v:51.13-52.43" *) 2'h1 : 2'hx;
  assign _12_ = ! (* full_case = 32'd1 *) (* src = "RTL/interrupt_controller_fsm.v:0.0-0.0|RTL/interrupt_controller_fsm.v:43.9-89.16" *) state;
  assign cpu_interrupt = busy;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/interrupt_controller_top.v:1.1-88.10" *)
module interrupt_controller_top(clk, rst, irq, mask_write, mask_data, cpu_ack, cpu_interrupt, busy, interrupt_id);
  (* src = "RTL/interrupt_controller_top.v:29.10-29.37" *)
  wire [7:0] _0_;
  (* src = "RTL/interrupt_controller_top.v:14.17-14.21" *)
  output busy;
  wire busy;
  (* src = "RTL/interrupt_controller_top.v:23.6-23.21" *)
  wire clear_interrupt;
  (* src = "RTL/interrupt_controller_top.v:24.21-24.33" *)
  wire [7:0] clear_vector;
  (* src = "RTL/interrupt_controller_top.v:6.16-6.19" *)
  input clk;
  wire clk;
  (* src = "RTL/interrupt_controller_top.v:11.16-11.23" *)
  input cpu_ack;
  wire cpu_ack;
  (* src = "RTL/interrupt_controller_top.v:13.17-13.30" *)
  output cpu_interrupt;
  wire cpu_interrupt;
  (* src = "RTL/interrupt_controller_top.v:15.23-15.35" *)
  output [2:0] interrupt_id;
  wire [2:0] interrupt_id;
  (* src = "RTL/interrupt_controller_top.v:8.31-8.34" *)
  input [7:0] irq;
  wire [7:0] irq;
  (* src = "RTL/interrupt_controller_top.v:10.31-10.40" *)
  input [7:0] mask_data;
  wire [7:0] mask_data;
  (* src = "RTL/interrupt_controller_top.v:20.21-20.34" *)
  wire [7:0] mask_register;
  (* src = "RTL/interrupt_controller_top.v:9.16-9.26" *)
  input mask_write;
  wire mask_write;
  (* src = "RTL/interrupt_controller_top.v:21.21-21.31" *)
  wire [7:0] masked_irq;
  (* src = "RTL/interrupt_controller_top.v:19.21-19.32" *)
  wire [7:0] pending_irq;
  (* src = "RTL/interrupt_controller_top.v:7.16-7.19" *)
  input rst;
  wire rst;
  (* src = "RTL/interrupt_controller_top.v:22.6-22.11" *)
  wire valid;
  assign masked_irq = pending_irq & (* src = "RTL/interrupt_controller_top.v:62.21-62.48" *) mask_register;
  assign _0_ = 8'h01 << (* src = "RTL/interrupt_controller_top.v:29.10-29.37" *) interrupt_id;
  assign clear_vector = clear_interrupt ? (* src = "RTL/interrupt_controller_top.v:28.9-30.20" *) _0_ : 8'h00;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/interrupt_controller_top.v:78.1-87.2" *)
  interrupt_controller_fsm fsm (
    .busy(busy),
    .clear_interrupt(clear_interrupt),
    .clk(clk),
    .cpu_ack(cpu_ack),
    .cpu_interrupt(cpu_interrupt),
    .rst(rst),
    .valid(valid)
  );
  (* src = "RTL/interrupt_controller_top.v:51.1-59.2" *)
  \$paramod\interrupt_mask_register\NUM_IRQS=s32'00000000000000000000000000001000  mask_reg (
    .clk(clk),
    .mask_data(mask_data),
    .mask_register(mask_register),
    .mask_write(mask_write),
    .rst(rst)
  );
  (* src = "RTL/interrupt_controller_top.v:69.1-74.2" *)
  \$paramod\interrupt_priority_encoder\NUM_IRQS=s32'00000000000000000000000000001000  priority_encoder (
    .interrupt_id(interrupt_id),
    .pending_irq(masked_irq),
    .valid(valid)
  );
  (* src = "RTL/interrupt_controller_top.v:37.1-44.2" *)
  \$paramod\interrupt_request_register\NUM_IRQS=s32'00000000000000000000000000001000  request_reg (
    .clear(clear_vector),
    .clk(clk),
    .irq(irq),
    .pending_irq(pending_irq),
    .rst(rst)
  );
endmodule
