/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/interrupt_request_register.v:1.1-37.10" *)
module interrupt_request_register(clk, rst, irq, clear, pending_irq);
  (* src = "RTL/interrupt_request_register.v:14.1-36.4" *)
  wire [7:0] _0_;
  (* src = "RTL/interrupt_request_register.v:32.47-32.53" *)
  wire [7:0] _1_;
  (* src = "RTL/interrupt_request_register.v:29.24-29.41" *)
  wire [7:0] _2_;
  (* src = "RTL/interrupt_request_register.v:9.31-9.36" *)
  input [7:0] clear;
  wire [7:0] clear;
  (* src = "RTL/interrupt_request_register.v:6.16-6.19" *)
  input clk;
  wire clk;
  (* src = "RTL/interrupt_request_register.v:8.31-8.34" *)
  input [7:0] irq;
  wire [7:0] irq;
  (* src = "RTL/interrupt_request_register.v:11.31-11.42" *)
  output [7:0] pending_irq;
  reg [7:0] pending_irq;
  (* src = "RTL/interrupt_request_register.v:7.16-7.19" *)
  input rst;
  wire rst;
  assign _0_ = _2_ & (* src = "RTL/interrupt_request_register.v:32.24-32.54" *) _1_;
  assign _1_ = ~ (* src = "RTL/interrupt_request_register.v:32.47-32.53" *) clear;
  assign _2_ = pending_irq | (* src = "RTL/interrupt_request_register.v:32.25-32.42" *) irq;
  (* src = "RTL/interrupt_request_register.v:14.1-36.4" *)
  always @(posedge clk, posedge rst)
    if (rst) pending_irq <= 8'h00;
    else pending_irq <= _0_;
endmodule
