/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/cla_4bit.v:1.1-41.10" *)
module cla_4bit(a, b, cin, sum, cout);
  (* src = "RTL/cla_4bit.v:17.21-17.31" *)
  wire _00_;
  (* src = "RTL/cla_4bit.v:20.14-20.25" *)
  wire _01_;
  (* src = "RTL/cla_4bit.v:21.14-21.25" *)
  wire _02_;
  (* src = "RTL/cla_4bit.v:21.14-21.31" *)
  wire _03_;
  (* src = "RTL/cla_4bit.v:24.14-24.25" *)
  wire _04_;
  (* src = "RTL/cla_4bit.v:25.14-25.25" *)
  wire _05_;
  (* src = "RTL/cla_4bit.v:25.14-25.32" *)
  wire _06_;
  (* src = "RTL/cla_4bit.v:26.14-26.32" *)
  wire _07_;
  (* src = "RTL/cla_4bit.v:26.14-26.38" *)
  wire _08_;
  (* src = "RTL/cla_4bit.v:29.14-29.25" *)
  wire _09_;
  (* src = "RTL/cla_4bit.v:30.14-30.25" *)
  wire _10_;
  (* src = "RTL/cla_4bit.v:30.14-30.32" *)
  wire _11_;
  (* src = "RTL/cla_4bit.v:31.14-31.32" *)
  wire _12_;
  (* src = "RTL/cla_4bit.v:31.14-31.39" *)
  wire _13_;
  (* src = "RTL/cla_4bit.v:32.14-32.39" *)
  wire _14_;
  (* src = "RTL/cla_4bit.v:32.14-32.45" *)
  wire _15_;
  (* src = "RTL/cla_4bit.v:19.13-20.26" *)
  wire _16_;
  (* src = "RTL/cla_4bit.v:23.13-24.26" *)
  wire _17_;
  (* src = "RTL/cla_4bit.v:23.13-25.33" *)
  wire _18_;
  (* src = "RTL/cla_4bit.v:28.13-29.26" *)
  wire _19_;
  (* src = "RTL/cla_4bit.v:28.13-30.33" *)
  wire _20_;
  (* src = "RTL/cla_4bit.v:28.13-31.40" *)
  wire _21_;
  (* src = "RTL/cla_4bit.v:2.17-2.18" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "RTL/cla_4bit.v:3.17-3.18" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "RTL/cla_4bit.v:12.6-12.8" *)
  wire c1;
  (* src = "RTL/cla_4bit.v:12.9-12.11" *)
  wire c2;
  (* src = "RTL/cla_4bit.v:12.12-12.14" *)
  wire c3;
  (* src = "RTL/cla_4bit.v:12.15-12.17" *)
  wire c4;
  (* src = "RTL/cla_4bit.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "RTL/cla_4bit.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "RTL/cla_4bit.v:10.12-10.13" *)
  wire [3:0] g;
  (* src = "RTL/cla_4bit.v:9.12-9.13" *)
  wire [3:0] p;
  (* src = "RTL/cla_4bit.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  assign g = a & (* src = "RTL/cla_4bit.v:15.12-15.17" *) b;
  assign _00_ = p[0] & (* src = "RTL/cla_4bit.v:17.21-17.31" *) cin;
  assign _01_ = p[1] & (* src = "RTL/cla_4bit.v:20.14-20.25" *) g[0];
  assign _02_ = p[1] & (* src = "RTL/cla_4bit.v:21.14-21.25" *) p[0];
  assign _03_ = _02_ & (* src = "RTL/cla_4bit.v:21.14-21.31" *) cin;
  assign _04_ = p[2] & (* src = "RTL/cla_4bit.v:24.14-24.25" *) g[1];
  assign _06_ = _05_ & (* src = "RTL/cla_4bit.v:25.14-25.32" *) g[0];
  assign _05_ = p[2] & (* src = "RTL/cla_4bit.v:26.14-26.25" *) p[1];
  assign _07_ = _05_ & (* src = "RTL/cla_4bit.v:26.14-26.32" *) p[0];
  assign _08_ = _07_ & (* src = "RTL/cla_4bit.v:26.14-26.38" *) cin;
  assign _09_ = p[3] & (* src = "RTL/cla_4bit.v:29.14-29.25" *) g[2];
  assign _11_ = _10_ & (* src = "RTL/cla_4bit.v:30.14-30.32" *) g[1];
  assign _13_ = _12_ & (* src = "RTL/cla_4bit.v:31.14-31.39" *) g[0];
  assign _10_ = p[3] & (* src = "RTL/cla_4bit.v:32.14-32.25" *) p[2];
  assign _12_ = _10_ & (* src = "RTL/cla_4bit.v:32.14-32.32" *) p[1];
  assign _14_ = _12_ & (* src = "RTL/cla_4bit.v:32.14-32.39" *) p[0];
  assign _15_ = _14_ & (* src = "RTL/cla_4bit.v:32.14-32.45" *) cin;
  assign c1 = g[0] | (* src = "RTL/cla_4bit.v:17.13-17.32" *) _00_;
  assign _16_ = g[1] | (* src = "RTL/cla_4bit.v:19.13-20.26" *) _01_;
  assign c2 = _16_ | (* src = "RTL/cla_4bit.v:19.13-21.32" *) _03_;
  assign _17_ = g[2] | (* src = "RTL/cla_4bit.v:23.13-24.26" *) _04_;
  assign _18_ = _17_ | (* src = "RTL/cla_4bit.v:23.13-25.33" *) _06_;
  assign c3 = _18_ | (* src = "RTL/cla_4bit.v:23.13-26.39" *) _08_;
  assign _19_ = g[3] | (* src = "RTL/cla_4bit.v:28.13-29.26" *) _09_;
  assign _20_ = _19_ | (* src = "RTL/cla_4bit.v:28.13-30.33" *) _11_;
  assign _21_ = _20_ | (* src = "RTL/cla_4bit.v:28.13-31.40" *) _13_;
  assign cout = _21_ | (* src = "RTL/cla_4bit.v:28.13-32.46" *) _15_;
  assign p = a ^ (* src = "RTL/cla_4bit.v:14.12-14.17" *) b;
  assign sum[0] = p[0] ^ (* src = "RTL/cla_4bit.v:34.17-34.27" *) cin;
  assign sum[1] = p[1] ^ (* src = "RTL/cla_4bit.v:35.17-35.26" *) c1;
  assign sum[2] = p[2] ^ (* src = "RTL/cla_4bit.v:36.17-36.26" *) c2;
  assign sum[3] = p[3] ^ (* src = "RTL/cla_4bit.v:37.17-37.26" *) c3;
  assign c4 = cout;
endmodule
