/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/forwarding_control_logic.v:1.1-41.10" *)
module forwarding_control_logic(ex_mem_match_rs1, mem_wb_match_rs1, ex_mem_match_rs2, mem_wb_match_rs2, forward_a, forward_b);
  (* src = "RTL/forwarding_control_logic.v:16.5-40.8" *)
  wire [1:0] _0_;
  (* src = "RTL/forwarding_control_logic.v:16.5-40.8" *)
  wire [1:0] _1_;
  (* src = "RTL/forwarding_control_logic.v:3.16-3.32" *)
  input ex_mem_match_rs1;
  wire ex_mem_match_rs1;
  (* src = "RTL/forwarding_control_logic.v:5.16-5.32" *)
  input ex_mem_match_rs2;
  wire ex_mem_match_rs2;
  (* src = "RTL/forwarding_control_logic.v:8.22-8.31" *)
  output [1:0] forward_a;
  wire [1:0] forward_a;
  (* src = "RTL/forwarding_control_logic.v:9.22-9.31" *)
  output [1:0] forward_b;
  wire [1:0] forward_b;
  (* src = "RTL/forwarding_control_logic.v:4.16-4.32" *)
  input mem_wb_match_rs1;
  wire mem_wb_match_rs1;
  (* src = "RTL/forwarding_control_logic.v:6.16-6.32" *)
  input mem_wb_match_rs2;
  wire mem_wb_match_rs2;
  assign _0_ = mem_wb_match_rs1 ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_control_logic.v:23.18-23.34|RTL/forwarding_control_logic.v:23.14-27.31" *) 2'h1 : 2'h0;
  assign forward_a = ex_mem_match_rs1 ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_control_logic.v:20.13-20.29|RTL/forwarding_control_logic.v:20.9-27.31" *) 2'h2 : _0_;
  assign _1_ = mem_wb_match_rs2 ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_control_logic.v:34.18-34.34|RTL/forwarding_control_logic.v:34.14-38.31" *) 2'h1 : 2'h0;
  assign forward_b = ex_mem_match_rs2 ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_control_logic.v:31.13-31.29|RTL/forwarding_control_logic.v:31.9-38.31" *) 2'h2 : _1_;
endmodule
