/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/can_bit_timing_generator.v:1.1-32.10" *)
module can_bit_timing_generator(clk, rst, can_clk);
  (* src = "RTL/can_bit_timing_generator.v:12.1-31.4" *)
  wire [7:0] _0_;
  (* src = "RTL/can_bit_timing_generator.v:28.26-28.42" *)
  wire [7:0] _1_;
  (* src = "RTL/can_bit_timing_generator.v:21.12-21.38" *)
  wire _2_;
  (* src = "RTL/can_bit_timing_generator.v:24.26-24.34" *)
  wire _3_;
  (* src = "RTL/can_bit_timing_generator.v:7.16-7.23" *)
  output can_clk;
  reg can_clk;
  (* src = "RTL/can_bit_timing_generator.v:4.16-4.19" *)
  input clk;
  wire clk;
  (* src = "RTL/can_bit_timing_generator.v:10.11-10.20" *)
  reg [7:0] clk_count;
  (* src = "RTL/can_bit_timing_generator.v:5.16-5.19" *)
  input rst;
  wire rst;
  assign _1_ = clk_count + (* src = "RTL/can_bit_timing_generator.v:28.26-28.42" *) 1'h1;
  (* src = "RTL/can_bit_timing_generator.v:12.1-31.4" *)
  always @(posedge clk, posedge rst)
    if (rst) can_clk <= 1'h0;
    else if (_2_) can_clk <= _3_;
  assign _2_ = clk_count == (* src = "RTL/can_bit_timing_generator.v:21.12-21.38" *) 8'h03;
  assign _3_ = ~ (* src = "RTL/can_bit_timing_generator.v:24.26-24.34" *) can_clk;
  (* src = "RTL/can_bit_timing_generator.v:12.1-31.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count <= 8'h00;
    else clk_count <= _0_;
  assign _0_ = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/can_bit_timing_generator.v:21.12-21.38|RTL/can_bit_timing_generator.v:21.9-29.12" *) 8'h00 : _1_;
endmodule
