/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/can_crc_generator.v:1.1-29.10" *)
module can_crc_generator(frame, crc);
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _00_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _01_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _02_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _03_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _04_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _05_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _06_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _07_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _08_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _09_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _10_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _11_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _12_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _13_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _14_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _15_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _16_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _17_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _18_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _19_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _20_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _21_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _22_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _23_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _24_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _25_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _26_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _27_;
  (* src = "RTL/can_crc_generator.v:25.15-25.29" *)
  wire [7:0] _28_;
  (* src = "RTL/can_crc_generator.v:11.18-11.21" *)
  output [7:0] crc;
  wire [7:0] crc;
  (* src = "RTL/can_crc_generator.v:9.25-9.30" *)
  input [30:0] frame;
  wire [30:0] frame;
  (* src = "RTL/can_crc_generator.v:15.9-15.10" *)
  wire [31:0] i;
  assign _00_ = _28_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[7];
  assign _01_ = _00_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[8];
  assign _02_ = _01_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[9];
  assign _03_ = _02_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[10];
  assign _04_ = _03_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[11];
  assign _05_ = _04_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[12];
  assign _06_ = _05_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[13];
  assign _07_ = _06_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[14];
  assign _08_ = _07_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[15];
  assign _09_ = _08_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[16];
  assign _10_ = _09_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[17];
  assign _11_ = _10_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[18];
  assign _12_ = _11_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[19];
  assign _13_ = _12_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[20];
  assign _14_ = _13_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[21];
  assign _15_ = _14_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[22];
  assign _16_ = _15_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[23];
  assign _17_ = _16_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[24];
  assign _18_ = _17_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[25];
  assign _19_ = _18_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[26];
  assign _20_ = _19_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[27];
  assign _21_ = _20_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[28];
  assign _22_ = _21_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[29];
  assign crc = _22_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[30];
  assign _23_ = { 7'h00, frame[0] } ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[1];
  assign _24_ = _23_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[2];
  assign _25_ = _24_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[3];
  assign _26_ = _25_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[4];
  assign _27_ = _26_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[5];
  assign _28_ = _27_ ^ (* src = "RTL/can_crc_generator.v:25.15-25.29" *) frame[6];
  assign i = 32'd31;
endmodule
