/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "RTL/arbiter_fsm.v:1.1-79.10" *)
module arbiter_fsm(clk, rst, request_pending, transfer_done, read_fifo, grant_enable, done);
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  wire _00_;
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  wire _01_;
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  wire _02_;
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  wire [1:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [1:0] _11_;
  wire [1:0] _12_;
  wire _13_;
  (* src = "RTL/arbiter_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/arbiter_fsm.v:10.12-10.16" *)
  output done;
  reg done;
  (* src = "RTL/arbiter_fsm.v:9.12-9.24" *)
  output grant_enable;
  reg grant_enable;
  (* src = "RTL/arbiter_fsm.v:8.12-8.21" *)
  output read_fifo;
  reg read_fifo;
  (* src = "RTL/arbiter_fsm.v:5.12-5.27" *)
  input request_pending;
  wire request_pending;
  (* src = "RTL/arbiter_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/arbiter_fsm.v:13.11-13.16" *)
  reg [1:0] state;
  (* src = "RTL/arbiter_fsm.v:6.12-6.25" *)
  input transfer_done;
  wire transfer_done;
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 2'h0;
    else if (_07_) state <= _03_;
  assign _04_ = { _13_, request_pending } != 2'h2;
  assign _05_ = { _09_, transfer_done } != 2'h2;
  assign _06_ = | { _13_, _10_, _09_, _08_ };
  assign _07_ = & { _06_, _05_, _04_ };
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  always @(posedge clk, posedge rst)
    if (rst) read_fifo <= 1'h0;
    else read_fifo <= _02_;
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  always @(posedge clk, posedge rst)
    if (rst) grant_enable <= 1'h0;
    else grant_enable <= _01_;
  (* src = "RTL/arbiter_fsm.v:20.1-78.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _00_;
  assign _00_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *) 1'h1 : 1'h0;
  assign _01_ = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *) 1'h1 : 1'h0;
  assign _02_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *) 1'h1 : 1'h0;
  function [1:0] _25_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _25_ = b[1:0];
      4'b??1?:
        _25_ = b[3:2];
      4'b?1??:
        _25_ = b[5:4];
      4'b1???:
        _25_ = b[7:6];
      default:
        _25_ = a;
    endcase
  endfunction
  assign _03_ = _25_(2'hx, { _12_, 2'h2, _11_, 2'h0 }, { _13_, _10_, _09_, _08_ });
  assign _08_ = state == (* full_case = 32'd1 *) (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *) 2'h3;
  assign _11_ = transfer_done ? (* src = "RTL/arbiter_fsm.v:63.16-63.29|RTL/arbiter_fsm.v:63.13-64.35" *) 2'h3 : 2'hx;
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *) 2'h2;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *) 2'h1;
  assign _12_ = request_pending ? (* src = "RTL/arbiter_fsm.v:47.16-47.31|RTL/arbiter_fsm.v:47.13-48.36" *) 2'h1 : 2'hx;
  assign _13_ = ! (* full_case = 32'd1 *) (* src = "RTL/arbiter_fsm.v:0.0-0.0|RTL/arbiter_fsm.v:43.9-75.16" *) state;
endmodule

(* top =  1  *)
(* src = "RTL/multi_port_sdram_top.v:1.1-55.10" *)
module multi_port_sdram_top(clk, rst, cpu_req, dma_req, eth_req, gpu_req, grant, done);
  (* src = "RTL/multi_port_sdram_top.v:22.8-23.15" *)
  wire _0_;
  (* src = "RTL/multi_port_sdram_top.v:22.8-24.15" *)
  wire _1_;
  (* src = "RTL/multi_port_sdram_top.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/multi_port_sdram_top.v:5.12-5.19" *)
  input cpu_req;
  wire cpu_req;
  (* src = "RTL/multi_port_sdram_top.v:6.12-6.19" *)
  input dma_req;
  wire dma_req;
  (* src = "RTL/multi_port_sdram_top.v:11.13-11.17" *)
  output done;
  wire done;
  (* src = "RTL/multi_port_sdram_top.v:7.12-7.19" *)
  input eth_req;
  wire eth_req;
  (* src = "RTL/multi_port_sdram_top.v:8.12-8.19" *)
  input gpu_req;
  wire gpu_req;
  (* src = "RTL/multi_port_sdram_top.v:10.19-10.24" *)
  output [1:0] grant;
  wire [1:0] grant;
  (* src = "RTL/multi_port_sdram_top.v:18.6-18.18" *)
  wire grant_enable;
  (* src = "RTL/multi_port_sdram_top.v:17.6-17.15" *)
  (* unused_bits = "0" *)
  wire read_fifo;
  (* src = "RTL/multi_port_sdram_top.v:15.6-15.21" *)
  wire request_pending;
  (* src = "RTL/multi_port_sdram_top.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/multi_port_sdram_top.v:16.6-16.19" *)
  wire transfer_done;
  assign _0_ = cpu_req | (* src = "RTL/multi_port_sdram_top.v:22.8-23.15" *) dma_req;
  assign _1_ = _0_ | (* src = "RTL/multi_port_sdram_top.v:22.8-24.15" *) eth_req;
  assign request_pending = _1_ | (* src = "RTL/multi_port_sdram_top.v:22.8-25.15" *) gpu_req;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/multi_port_sdram_top.v:31.21-42.2" *)
  round_robin_arbiter arbiter (
    .clk(clk),
    .cpu_req(cpu_req),
    .dma_req(dma_req),
    .eth_req(eth_req),
    .gpu_req(gpu_req),
    .grant(grant),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/multi_port_sdram_top.v:45.13-54.2" *)
  arbiter_fsm controller (
    .clk(clk),
    .done(done),
    .grant_enable(grant_enable),
    .read_fifo(read_fifo),
    .request_pending(request_pending),
    .rst(rst),
    .transfer_done(grant_enable)
  );
  assign transfer_done = grant_enable;
endmodule

(* src = "RTL/round_robin_arbiter.v:1.1-214.10" *)
module round_robin_arbiter(clk, rst, cpu_req, dma_req, eth_req, gpu_req, grant, valid);
  (* src = "RTL/round_robin_arbiter.v:17.1-213.4" *)
  wire [1:0] _000_;
  (* src = "RTL/round_robin_arbiter.v:17.1-213.4" *)
  wire [1:0] _001_;
  (* src = "RTL/round_robin_arbiter.v:17.1-213.4" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire _016_;
  wire [1:0] _017_;
  wire [1:0] _018_;
  wire [1:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire [1:0] _022_;
  wire [1:0] _023_;
  wire [1:0] _024_;
  wire [1:0] _025_;
  wire _026_;
  wire [1:0] _027_;
  wire [1:0] _028_;
  wire [1:0] _029_;
  wire [1:0] _030_;
  wire [1:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [1:0] _035_;
  wire [1:0] _036_;
  wire [1:0] _037_;
  wire [1:0] _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire [1:0] _055_;
  wire [1:0] _056_;
  wire [1:0] _057_;
  wire [1:0] _058_;
  wire [1:0] _059_;
  wire [1:0] _060_;
  (* src = "RTL/round_robin_arbiter.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/round_robin_arbiter.v:6.12-6.19" *)
  input cpu_req;
  wire cpu_req;
  (* src = "RTL/round_robin_arbiter.v:7.12-7.19" *)
  input dma_req;
  wire dma_req;
  (* src = "RTL/round_robin_arbiter.v:8.12-8.19" *)
  input eth_req;
  wire eth_req;
  (* src = "RTL/round_robin_arbiter.v:9.12-9.19" *)
  input gpu_req;
  wire gpu_req;
  (* src = "RTL/round_robin_arbiter.v:11.18-11.23" *)
  output [1:0] grant;
  reg [1:0] grant;
  (* src = "RTL/round_robin_arbiter.v:15.11-15.18" *)
  reg [1:0] pointer;
  (* src = "RTL/round_robin_arbiter.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/round_robin_arbiter.v:12.12-12.17" *)
  output valid;
  reg valid;
  (* src = "RTL/round_robin_arbiter.v:17.1-213.4" *)
  always @(posedge clk, posedge rst)
    if (rst) grant <= 2'h0;
    else if (_008_) grant <= _000_;
  (* src = "RTL/round_robin_arbiter.v:17.1-213.4" *)
  always @(posedge clk, posedge rst)
    if (rst) pointer <= 2'h0;
    else if (_008_) pointer <= _001_;
  assign _003_ = { _026_, gpu_req, eth_req, dma_req, cpu_req } != 5'h10;
  assign _004_ = { _011_, gpu_req, eth_req, dma_req, cpu_req } != 5'h10;
  assign _005_ = { _016_, gpu_req, eth_req, dma_req, cpu_req } != 5'h10;
  assign _006_ = { _021_, gpu_req, eth_req, dma_req, cpu_req } != 5'h10;
  assign _007_ = | { _021_, _016_, _011_, _026_ };
  assign _008_ = & { _003_, _007_, _005_, _006_, _004_ };
  (* src = "RTL/round_robin_arbiter.v:17.1-213.4" *)
  always @(posedge clk, posedge rst)
    if (rst) valid <= 1'h0;
    else valid <= _002_;
  assign _009_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:136.21-136.28|RTL/round_robin_arbiter.v:136.18-162.16" *) 2'h0 : _060_;
  assign _010_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:127.16-127.23|RTL/round_robin_arbiter.v:127.13-162.16" *) 2'h3 : _009_;
  assign _012_ = cpu_req ? (* src = "RTL/round_robin_arbiter.v:112.21-112.28|RTL/round_robin_arbiter.v:112.18-119.16" *) 2'h1 : 2'hx;
  assign _013_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:103.21-103.28|RTL/round_robin_arbiter.v:103.18-119.16" *) 2'h0 : _012_;
  assign _014_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:93.21-93.28|RTL/round_robin_arbiter.v:93.18-119.16" *) 2'h3 : _013_;
  assign _015_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:84.16-84.23|RTL/round_robin_arbiter.v:84.13-119.16" *) 2'h2 : _014_;
  assign _017_ = gpu_req ? (* src = "RTL/round_robin_arbiter.v:69.21-69.28|RTL/round_robin_arbiter.v:69.18-76.16" *) 2'h0 : 2'hx;
  assign _018_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:60.21-60.28|RTL/round_robin_arbiter.v:60.18-76.16" *) 2'h3 : _017_;
  assign _019_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:52.21-52.28|RTL/round_robin_arbiter.v:52.18-76.16" *) 2'h2 : _018_;
  assign _020_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:42.16-42.23|RTL/round_robin_arbiter.v:42.13-76.16" *) 2'h1 : _019_;
  assign _022_ = eth_req ? (* src = "RTL/round_robin_arbiter.v:198.21-198.28|RTL/round_robin_arbiter.v:198.18-206.16" *) 2'h2 : 2'hx;
  assign _023_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:189.21-189.28|RTL/round_robin_arbiter.v:189.18-206.16" *) 2'h1 : _022_;
  assign _024_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:179.21-179.28|RTL/round_robin_arbiter.v:179.18-206.16" *) 2'h0 : _023_;
  assign _025_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:170.16-170.23|RTL/round_robin_arbiter.v:170.13-206.16" *) 2'h3 : _024_;
  function [1:0] _084_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/round_robin_arbiter.v:0.0-0.0|RTL/round_robin_arbiter.v:36.9-210.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _084_ = b[1:0];
      4'b??1?:
        _084_ = b[3:2];
      4'b?1??:
        _084_ = b[5:4];
      4'b1???:
        _084_ = b[7:6];
      default:
        _084_ = a;
    endcase
  endfunction
  assign _000_ = _084_(2'hx, { _038_, _034_, _030_, _025_ }, { _021_, _016_, _011_, _026_ });
  assign _026_ = pointer == (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:0.0-0.0|RTL/round_robin_arbiter.v:36.9-210.16" *) 2'h3;
  assign _027_ = dma_req ? (* src = "RTL/round_robin_arbiter.v:155.21-155.28|RTL/round_robin_arbiter.v:155.18-162.16" *) 2'h1 : 2'hx;
  assign _028_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:146.21-146.28|RTL/round_robin_arbiter.v:146.18-162.16" *) 2'h0 : _027_;
  assign _029_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:136.21-136.28|RTL/round_robin_arbiter.v:136.18-162.16" *) 2'h3 : _028_;
  assign _030_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:127.16-127.23|RTL/round_robin_arbiter.v:127.13-162.16" *) 2'h2 : _029_;
  assign _011_ = pointer == (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:0.0-0.0|RTL/round_robin_arbiter.v:36.9-210.16" *) 2'h2;
  assign _031_ = cpu_req ? (* src = "RTL/round_robin_arbiter.v:112.21-112.28|RTL/round_robin_arbiter.v:112.18-119.16" *) 2'h0 : 2'hx;
  assign _032_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:103.21-103.28|RTL/round_robin_arbiter.v:103.18-119.16" *) 2'h3 : _031_;
  assign _033_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:93.21-93.28|RTL/round_robin_arbiter.v:93.18-119.16" *) 2'h2 : _032_;
  assign _034_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:84.16-84.23|RTL/round_robin_arbiter.v:84.13-119.16" *) 2'h1 : _033_;
  assign _016_ = pointer == (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:0.0-0.0|RTL/round_robin_arbiter.v:36.9-210.16" *) 2'h1;
  assign _035_ = gpu_req ? (* src = "RTL/round_robin_arbiter.v:69.21-69.28|RTL/round_robin_arbiter.v:69.18-76.16" *) 2'h3 : 2'hx;
  assign _036_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:60.21-60.28|RTL/round_robin_arbiter.v:60.18-76.16" *) 2'h2 : _035_;
  assign _037_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:52.21-52.28|RTL/round_robin_arbiter.v:52.18-76.16" *) 2'h1 : _036_;
  assign _038_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:42.16-42.23|RTL/round_robin_arbiter.v:42.13-76.16" *) 2'h0 : _037_;
  assign _021_ = ! (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:0.0-0.0|RTL/round_robin_arbiter.v:36.9-210.16" *) pointer;
  assign _039_ = eth_req ? (* src = "RTL/round_robin_arbiter.v:198.21-198.28|RTL/round_robin_arbiter.v:198.18-206.16" *) 1'h1 : 1'h0;
  assign _040_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:189.21-189.28|RTL/round_robin_arbiter.v:189.18-206.16" *) 1'h1 : _039_;
  assign _041_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:179.21-179.28|RTL/round_robin_arbiter.v:179.18-206.16" *) 1'h1 : _040_;
  assign _042_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:170.16-170.23|RTL/round_robin_arbiter.v:170.13-206.16" *) 1'h1 : _041_;
  function [0:0] _105_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/round_robin_arbiter.v:0.0-0.0|RTL/round_robin_arbiter.v:36.9-210.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _105_ = b[0:0];
      4'b??1?:
        _105_ = b[1:1];
      4'b?1??:
        _105_ = b[2:2];
      4'b1???:
        _105_ = b[3:3];
      default:
        _105_ = a;
    endcase
  endfunction
  assign _002_ = _105_(1'h0, { _054_, _050_, _046_, _042_ }, { _021_, _016_, _011_, _026_ });
  assign _043_ = dma_req ? (* src = "RTL/round_robin_arbiter.v:155.21-155.28|RTL/round_robin_arbiter.v:155.18-162.16" *) 1'h1 : 1'h0;
  assign _044_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:146.21-146.28|RTL/round_robin_arbiter.v:146.18-162.16" *) 1'h1 : _043_;
  assign _045_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:136.21-136.28|RTL/round_robin_arbiter.v:136.18-162.16" *) 1'h1 : _044_;
  assign _046_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:127.16-127.23|RTL/round_robin_arbiter.v:127.13-162.16" *) 1'h1 : _045_;
  assign _047_ = cpu_req ? (* src = "RTL/round_robin_arbiter.v:112.21-112.28|RTL/round_robin_arbiter.v:112.18-119.16" *) 1'h1 : 1'h0;
  assign _048_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:103.21-103.28|RTL/round_robin_arbiter.v:103.18-119.16" *) 1'h1 : _047_;
  assign _049_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:93.21-93.28|RTL/round_robin_arbiter.v:93.18-119.16" *) 1'h1 : _048_;
  assign _050_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:84.16-84.23|RTL/round_robin_arbiter.v:84.13-119.16" *) 1'h1 : _049_;
  assign _051_ = gpu_req ? (* src = "RTL/round_robin_arbiter.v:69.21-69.28|RTL/round_robin_arbiter.v:69.18-76.16" *) 1'h1 : 1'h0;
  assign _052_ = eth_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:60.21-60.28|RTL/round_robin_arbiter.v:60.18-76.16" *) 1'h1 : _051_;
  assign _053_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:52.21-52.28|RTL/round_robin_arbiter.v:52.18-76.16" *) 1'h1 : _052_;
  assign _054_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:42.16-42.23|RTL/round_robin_arbiter.v:42.13-76.16" *) 1'h1 : _053_;
  assign _055_ = eth_req ? (* src = "RTL/round_robin_arbiter.v:198.21-198.28|RTL/round_robin_arbiter.v:198.18-206.16" *) 2'h3 : 2'hx;
  assign _056_ = dma_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:189.21-189.28|RTL/round_robin_arbiter.v:189.18-206.16" *) 2'h2 : _055_;
  assign _057_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:179.21-179.28|RTL/round_robin_arbiter.v:179.18-206.16" *) 2'h1 : _056_;
  assign _058_ = gpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:170.16-170.23|RTL/round_robin_arbiter.v:170.13-206.16" *) 2'h0 : _057_;
  function [1:0] _122_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/round_robin_arbiter.v:0.0-0.0|RTL/round_robin_arbiter.v:36.9-210.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _122_ = b[1:0];
      4'b??1?:
        _122_ = b[3:2];
      4'b?1??:
        _122_ = b[5:4];
      4'b1???:
        _122_ = b[7:6];
      default:
        _122_ = a;
    endcase
  endfunction
  assign _001_ = _122_(2'hx, { _020_, _015_, _010_, _058_ }, { _021_, _016_, _011_, _026_ });
  assign _059_ = dma_req ? (* src = "RTL/round_robin_arbiter.v:155.21-155.28|RTL/round_robin_arbiter.v:155.18-162.16" *) 2'h2 : 2'hx;
  assign _060_ = cpu_req ? (* full_case = 32'd1 *) (* src = "RTL/round_robin_arbiter.v:146.21-146.28|RTL/round_robin_arbiter.v:146.18-162.16" *) 2'h1 : _059_;
endmodule
