/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/address_decoder.v:1.1-38.10" *)
module address_decoder(address, reg_select, valid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "RTL/address_decoder.v:3.23-3.30" *)
  input [31:0] address;
  wire [31:0] address;
  (* src = "RTL/address_decoder.v:5.22-5.32" *)
  output [1:0] reg_select;
  wire [1:0] reg_select;
  (* src = "RTL/address_decoder.v:6.16-6.21" *)
  output valid;
  wire valid;
  assign _00_ = | { _03_, _02_, _01_, _04_ };
  assign _01_ = address == (* full_case = 32'd1 *) (* src = "RTL/address_decoder.v:0.0-0.0|RTL/address_decoder.v:14.5-36.12" *) 32'd8;
  assign _02_ = address == (* full_case = 32'd1 *) (* src = "RTL/address_decoder.v:0.0-0.0|RTL/address_decoder.v:14.5-36.12" *) 32'd4;
  assign _03_ = ! (* full_case = 32'd1 *) (* src = "RTL/address_decoder.v:0.0-0.0|RTL/address_decoder.v:14.5-36.12" *) address;
  function [1:0] _09_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/address_decoder.v:0.0-0.0|RTL/address_decoder.v:14.5-36.12" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _09_ = b[1:0];
      3'b?1?:
        _09_ = b[3:2];
      3'b1??:
        _09_ = b[5:4];
      default:
        _09_ = a;
    endcase
  endfunction
  assign reg_select = _09_(2'h0, 6'h1b, { _02_, _01_, _04_ });
  assign valid = _00_ ? (* full_case = 32'd1 *) (* src = "RTL/address_decoder.v:0.0-0.0|RTL/address_decoder.v:14.5-36.12" *) 1'h1 : 1'h0;
  assign _04_ = address == (* full_case = 32'd1 *) (* src = "RTL/address_decoder.v:0.0-0.0|RTL/address_decoder.v:14.5-36.12" *) 32'd12;
endmodule
