/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/axi_read_channel.v:1.1-54.10" *)
module axi_read_channel(clk, rst, arvalid, rready, address_valid, arready, rvalid, read_enable);
  (* src = "RTL/axi_read_channel.v:15.1-53.4" *)
  wire _00_;
  (* src = "RTL/axi_read_channel.v:15.1-53.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_read_channel.v:33.12-33.36" *)
  wire _03_;
  wire _04_;
  (* src = "RTL/axi_read_channel.v:7.16-7.29" *)
  input address_valid;
  wire address_valid;
  (* src = "RTL/axi_read_channel.v:9.16-9.23" *)
  output arready;
  reg arready;
  (* src = "RTL/axi_read_channel.v:5.16-5.23" *)
  input arvalid;
  wire arvalid;
  (* src = "RTL/axi_read_channel.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_read_channel.v:11.16-11.27" *)
  output read_enable;
  reg read_enable;
  (* src = "RTL/axi_read_channel.v:6.16-6.22" *)
  input rready;
  wire rready;
  (* src = "RTL/axi_read_channel.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_read_channel.v:10.16-10.22" *)
  output rvalid;
  wire rvalid;
  (* src = "RTL/axi_read_channel.v:15.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) arready <= 1'h0;
    else if (_02_) arready <= _00_;
  assign _02_ = | { _03_, rready };
  assign _03_ = arvalid && (* src = "RTL/axi_read_channel.v:33.12-33.36" *) address_valid;
  (* src = "RTL/axi_read_channel.v:15.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) read_enable <= 1'h0;
    else read_enable <= _01_;
  assign _04_ = rready ? (* src = "RTL/axi_read_channel.v:43.17-43.23|RTL/axi_read_channel.v:43.14-50.12" *) 1'h0 : 1'hx;
  assign _00_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_read_channel.v:33.12-33.36|RTL/axi_read_channel.v:33.9-50.12" *) 1'h1 : _04_;
  assign _01_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_read_channel.v:33.12-33.36|RTL/axi_read_channel.v:33.9-50.12" *) 1'h1 : 1'h0;
  assign rvalid = arready;
endmodule
