/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/axi_write_channel.v:1.1-59.10" *)
module axi_write_channel(clk, rst, awvalid, wvalid, bready, address_valid, awready, wready, bvalid, write_enable);
  (* src = "RTL/axi_write_channel.v:17.1-58.4" *)
  wire _00_;
  (* src = "RTL/axi_write_channel.v:17.1-58.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_write_channel.v:35.12-35.29" *)
  wire _03_;
  (* src = "RTL/axi_write_channel.v:35.12-35.46" *)
  wire _04_;
  wire _05_;
  (* src = "RTL/axi_write_channel.v:8.16-8.29" *)
  input address_valid;
  wire address_valid;
  (* src = "RTL/axi_write_channel.v:10.16-10.23" *)
  output awready;
  wire awready;
  (* src = "RTL/axi_write_channel.v:5.16-5.23" *)
  input awvalid;
  wire awvalid;
  (* src = "RTL/axi_write_channel.v:7.16-7.22" *)
  input bready;
  wire bready;
  (* src = "RTL/axi_write_channel.v:12.16-12.22" *)
  output bvalid;
  wire bvalid;
  (* src = "RTL/axi_write_channel.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_write_channel.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_write_channel.v:11.16-11.22" *)
  output wready;
  reg wready;
  (* src = "RTL/axi_write_channel.v:13.16-13.28" *)
  output write_enable;
  reg write_enable;
  (* src = "RTL/axi_write_channel.v:6.16-6.22" *)
  input wvalid;
  wire wvalid;
  (* src = "RTL/axi_write_channel.v:17.1-58.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wready <= 1'h0;
    else if (_02_) wready <= _00_;
  assign _02_ = | { _04_, bready };
  assign _03_ = awvalid && (* src = "RTL/axi_write_channel.v:35.12-35.29" *) wvalid;
  assign _04_ = _03_ && (* src = "RTL/axi_write_channel.v:35.12-35.46" *) address_valid;
  (* src = "RTL/axi_write_channel.v:17.1-58.4" *)
  always @(posedge clk, posedge rst)
    if (rst) write_enable <= 1'h0;
    else write_enable <= _01_;
  assign _00_ = _04_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_channel.v:35.12-35.46|RTL/axi_write_channel.v:35.9-55.12" *) 1'h1 : _05_;
  assign _05_ = bready ? (* src = "RTL/axi_write_channel.v:47.17-47.23|RTL/axi_write_channel.v:47.14-55.12" *) 1'h0 : 1'hx;
  assign _01_ = _04_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_channel.v:35.12-35.46|RTL/axi_write_channel.v:35.9-55.12" *) 1'h1 : 1'h0;
  assign awready = wready;
  assign bvalid = wready;
endmodule
