/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/register_file.v:1.1-51.10" *)
module register_file(clk, rst, write_enable, write_addr, write_data, read_addr, read_data);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "RTL/register_file.v:7.16-7.19" *)
  input clk;
  wire clk;
  (* src = "RTL/register_file.v:20.9-20.10" *)
  wire [31:0] i;
  (* src = "RTL/register_file.v:12.22-12.31" *)
  input [1:0] read_addr;
  wire [1:0] read_addr;
  (* src = "RTL/register_file.v:14.33-14.42" *)
  output [31:0] read_data;
  wire [31:0] read_data;
  (* src = "RTL/register_file.v:18.22-18.30" *)
  reg [31:0] \reg_bank[0] ;
  (* src = "RTL/register_file.v:18.22-18.30" *)
  reg [31:0] \reg_bank[1] ;
  (* src = "RTL/register_file.v:18.22-18.30" *)
  reg [31:0] \reg_bank[2] ;
  (* src = "RTL/register_file.v:18.22-18.30" *)
  reg [31:0] \reg_bank[3] ;
  (* src = "RTL/register_file.v:8.16-8.19" *)
  input rst;
  wire rst;
  (* src = "RTL/register_file.v:10.22-10.32" *)
  input [1:0] write_addr;
  wire [1:0] write_addr;
  (* src = "RTL/register_file.v:11.33-11.43" *)
  input [31:0] write_data;
  wire [31:0] write_data;
  (* src = "RTL/register_file.v:9.16-9.28" *)
  input write_enable;
  wire write_enable;
  (* src = "RTL/register_file.v:23.1-42.4" *)
  always @(posedge clk, posedge rst)
    if (rst) \reg_bank[0]  <= 32'd0;
    else if (_00_) \reg_bank[0]  <= write_data;
  (* src = "RTL/register_file.v:23.1-42.4" *)
  always @(posedge clk, posedge rst)
    if (rst) \reg_bank[1]  <= 32'd0;
    else if (_01_) \reg_bank[1]  <= write_data;
  (* src = "RTL/register_file.v:23.1-42.4" *)
  always @(posedge clk, posedge rst)
    if (rst) \reg_bank[2]  <= 32'd0;
    else if (_02_) \reg_bank[2]  <= write_data;
  (* src = "RTL/register_file.v:23.1-42.4" *)
  always @(posedge clk, posedge rst)
    if (rst) \reg_bank[3]  <= 32'd0;
    else if (_03_) \reg_bank[3]  <= write_data;
  assign _00_ = & { _11_, write_enable };
  assign _01_ = & { _10_, write_enable };
  assign _02_ = & { _09_, write_enable };
  assign _03_ = & { _08_, write_enable };
  function [31:0] _20_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/register_file.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _20_ = b[31:0];
      4'b??1?:
        _20_ = b[63:32];
      4'b?1??:
        _20_ = b[95:64];
      4'b1???:
        _20_ = b[127:96];
      default:
        _20_ = a;
    endcase
  endfunction
  assign read_data = _20_(32'hxxxxxxxx, { \reg_bank[0] , \reg_bank[1] , \reg_bank[2] , \reg_bank[3]  }, { _07_, _06_, _05_, _04_ });
  assign _04_ = read_addr == (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) 2'h3;
  assign _05_ = read_addr == (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) 2'h2;
  assign _06_ = read_addr == (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) 2'h1;
  assign _07_ = ! (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) read_addr;
  assign _08_ = write_addr == (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) 2'h3;
  assign _09_ = write_addr == (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) 2'h2;
  assign _10_ = write_addr == (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) 2'h1;
  assign _11_ = ! (* full_case = 32'd1 *) (* src = "RTL/register_file.v:0.0-0.0" *) write_addr;
  assign i = 32'd4;
endmodule
