/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/i2c_address_comparator.v:1.1-12.10" *)
module i2c_address_comparator(received_address, match);
  (* src = "RTL/i2c_address_comparator.v:7.12-7.17" *)
  output match;
  wire match;
  (* src = "RTL/i2c_address_comparator.v:5.31-5.47" *)
  input [6:0] received_address;
  wire [6:0] received_address;
  assign match = received_address == (* src = "RTL/i2c_address_comparator.v:10.17-10.50" *) 7'h42;
endmodule
