/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/i2c_slave_bit_counter.v:1.1-43.10" *)
module i2c_slave_bit_counter(scl, rst, enable, done, bit_count);
  (* src = "RTL/i2c_slave_bit_counter.v:12.1-42.4" *)
  wire _00_;
  (* src = "RTL/i2c_slave_bit_counter.v:32.26-32.39" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _01_;
  (* src = "RTL/i2c_slave_bit_counter.v:24.12-24.37" *)
  wire _02_;
  wire [2:0] _03_;
  wire _04_;
  (* src = "RTL/i2c_slave_bit_counter.v:9.41-9.50" *)
  output [2:0] bit_count;
  reg [2:0] bit_count;
  (* src = "RTL/i2c_slave_bit_counter.v:8.16-8.20" *)
  output done;
  reg done;
  (* src = "RTL/i2c_slave_bit_counter.v:6.11-6.17" *)
  input enable;
  wire enable;
  (* src = "RTL/i2c_slave_bit_counter.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_slave_bit_counter.v:4.11-4.14" *)
  input scl;
  wire scl;
  assign _01_ = bit_count + (* src = "RTL/i2c_slave_bit_counter.v:32.26-32.39" *) 32'd1;
  (* src = "RTL/i2c_slave_bit_counter.v:12.1-42.4" *)
  always @(posedge scl, posedge rst)
    if (rst) bit_count <= 3'h0;
    else if (enable) bit_count <= _03_;
  assign _02_ = bit_count == (* src = "RTL/i2c_slave_bit_counter.v:24.12-24.37" *) 3'h7;
  (* src = "RTL/i2c_slave_bit_counter.v:12.1-42.4" *)
  always @(posedge scl, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _00_;
  assign _03_ = _02_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_slave_bit_counter.v:24.12-24.37|RTL/i2c_slave_bit_counter.v:24.9-34.12" *) 3'h0 : _01_[2:0];
  assign _04_ = _02_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_slave_bit_counter.v:24.12-24.37|RTL/i2c_slave_bit_counter.v:24.9-34.12" *) 1'h1 : 1'h0;
  assign _00_ = enable ? (* full_case = 32'd1 *) (* src = "RTL/i2c_slave_bit_counter.v:21.13-21.19|RTL/i2c_slave_bit_counter.v:21.10-41.8" *) _04_ : 1'h0;
endmodule
