/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/spi_shift_register.v:1.1-41.10" *)
module spi_shift_register(clk, rst, load, shift, data_in, miso, rx_data, mosi, shift_reg);
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  wire [7:0] _00_;
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  wire [7:0] _01_;
  wire _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  (* src = "RTL/spi_shift_register.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_shift_register.v:8.28-8.35" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "RTL/spi_shift_register.v:6.11-6.15" *)
  input load;
  wire load;
  (* src = "RTL/spi_shift_register.v:9.11-9.15" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_shift_register.v:12.12-12.16" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_shift_register.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_shift_register.v:11.33-11.40" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/spi_shift_register.v:7.11-7.16" *)
  input shift;
  wire shift;
  (* src = "RTL/spi_shift_register.v:13.33-13.42" *)
  output [7:0] shift_reg;
  reg [7:0] shift_reg;
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_02_) rx_data <= _00_;
  (* src = "RTL/spi_shift_register.v:19.1-40.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_reg <= 8'h00;
    else if (_02_) shift_reg <= _01_;
  assign _02_ = | { shift, load };
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:28.13-28.17|RTL/spi_shift_register.v:28.10-38.8" *) 8'h00 : _04_;
  assign _03_ = shift ? (* src = "RTL/spi_shift_register.v:34.13-34.18|RTL/spi_shift_register.v:34.10-38.8" *) { shift_reg[6:0], 1'h0 } : 8'hxx;
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:28.13-28.17|RTL/spi_shift_register.v:28.10-38.8" *) data_in : _03_;
  assign _04_ = shift ? (* src = "RTL/spi_shift_register.v:34.13-34.18|RTL/spi_shift_register.v:34.10-38.8" *) { rx_data[6:0], miso } : 8'hxx;
  assign mosi = shift_reg[7];
endmodule
