/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/spi_bit_counter.v:1.1-32.10" *)
module spi_bit_counter(clk, rst, enable, bit_count, done);
  (* src = "RTL/spi_bit_counter.v:28.26-28.39" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0_;
  wire [2:0] _1_;
  (* src = "RTL/spi_bit_counter.v:7.22-7.31" *)
  output [2:0] bit_count;
  reg [2:0] bit_count;
  (* src = "RTL/spi_bit_counter.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_bit_counter.v:8.12-8.16" *)
  output done;
  wire done;
  (* src = "RTL/spi_bit_counter.v:5.11-5.17" *)
  input enable;
  wire enable;
  (* src = "RTL/spi_bit_counter.v:4.11-4.14" *)
  input rst;
  wire rst;
  assign _0_ = bit_count + (* src = "RTL/spi_bit_counter.v:28.26-28.39" *) 32'd1;
  (* src = "RTL/spi_bit_counter.v:13.1-31.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 3'h0;
    else if (enable) bit_count <= _1_;
  assign done = bit_count == (* src = "RTL/spi_bit_counter.v:24.12-24.29" *) 3'h7;
  assign _1_ = done ? (* full_case = 32'd1 *) (* src = "RTL/spi_bit_counter.v:24.12-24.29|RTL/spi_bit_counter.v:24.9-28.40" *) 3'h0 : _0_[2:0];
endmodule
