/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/spi_master_fsm.v:1.1-118.10" *)
module spi_master_fsm(clk, rst, start, done, load, shift, enable, busy, cs);
  (* src = "RTL/spi_master_fsm.v:40.1-75.4" *)
  wire [1:0] _00_;
  (* src = "RTL/spi_master_fsm.v:40.1-75.4" *)
  wire [1:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "RTL/spi_master_fsm.v:11.16-11.20" *)
  output busy;
  wire busy;
  (* src = "RTL/spi_master_fsm.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master_fsm.v:12.16-12.18" *)
  output cs;
  wire cs;
  (* src = "RTL/spi_master_fsm.v:6.11-6.15" *)
  input done;
  wire done;
  (* src = "RTL/spi_master_fsm.v:10.16-10.22" *)
  output enable;
  wire enable;
  (* src = "RTL/spi_master_fsm.v:8.16-8.20" *)
  output load;
  wire load;
  (* src = "RTL/spi_master_fsm.v:23.11-23.21" *)
  wire [1:0] next_state;
  (* src = "RTL/spi_master_fsm.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master_fsm.v:9.16-9.21" *)
  output shift;
  wire shift;
  (* src = "RTL/spi_master_fsm.v:5.11-5.16" *)
  input start;
  wire start;
  (* src = "RTL/spi_master_fsm.v:22.11-22.16" *)
  reg [1:0] state;
  assign _03_ = | { _09_, _07_, _06_ };
  assign _02_ = | { _09_, _08_, _06_ };
  assign _04_ = | { _09_, _06_ };
  assign _05_ = | { _08_, _07_ };
  (* src = "RTL/spi_master_fsm.v:27.1-36.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 2'h0;
    else state <= next_state;
  function [0:0] _15_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:87.5-115.12" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _15_ = b[0:0];
      2'b1?:
        _15_ = b[1:1];
      default:
        _15_ = a;
    endcase
  endfunction
  assign enable = _15_(1'hx, 2'h2, { _07_, _02_ });
  function [0:0] _16_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:87.5-115.12" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _16_ = b[0:0];
      2'b1?:
        _16_ = b[1:1];
      default:
        _16_ = a;
    endcase
  endfunction
  assign load = _16_(1'hx, 2'h2, { _08_, _03_ });
  assign _01_ = done ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:60.16-60.20|RTL/spi_master_fsm.v:60.13-63.36" *) 2'h3 : 2'h2;
  assign _00_ = start ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:47.16-47.21|RTL/spi_master_fsm.v:47.13-50.35" *) 2'h1 : 2'h0;
  function [0:0] _19_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:87.5-115.12" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _19_ = b[0:0];
      2'b1?:
        _19_ = b[1:1];
      default:
        _19_ = a;
    endcase
  endfunction
  assign cs = _19_(1'hx, 2'h1, { _05_, _04_ });
  function [1:0] _20_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:43.5-74.12" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _20_ = b[1:0];
      4'b??1?:
        _20_ = b[3:2];
      4'b?1??:
        _20_ = b[5:4];
      4'b1???:
        _20_ = b[7:6];
      default:
        _20_ = a;
    endcase
  endfunction
  assign next_state = _20_(2'hx, { _00_, 2'h2, _01_, 2'h0 }, { _09_, _08_, _07_, _06_ });
  assign _06_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:43.5-74.12" *) 2'h3;
  assign _07_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:43.5-74.12" *) 2'h2;
  assign _08_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:43.5-74.12" *) 2'h1;
  assign _09_ = ! (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:43.5-74.12" *) state;
  function [0:0] _25_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:87.5-115.12" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _25_ = b[0:0];
      2'b1?:
        _25_ = b[1:1];
      default:
        _25_ = a;
    endcase
  endfunction
  assign busy = _25_(1'hx, 2'h2, { _05_, _04_ });
  assign shift = enable;
endmodule
