/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* hdlname = "\\spi_clock_divider" *)
(* src = "RTL/spi_clock_divider.v:1.1-42.10" *)
module \$paramod\spi_clock_divider\DIVIDER=s32'00000000000000000000000000000100 (clk, rst, spi_clk);
  (* src = "RTL/spi_clock_divider.v:14.1-41.4" *)
  wire [31:0] _0_;
  (* src = "RTL/spi_clock_divider.v:36.24-36.35" *)
  wire [31:0] _1_;
  (* src = "RTL/spi_clock_divider.v:27.12-27.36" *)
  wire _2_;
  (* src = "RTL/spi_clock_divider.v:30.24-30.32" *)
  wire _3_;
  (* src = "RTL/spi_clock_divider.v:6.17-6.20" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_clock_divider.v:12.12-12.19" *)
  reg [31:0] counter;
  (* src = "RTL/spi_clock_divider.v:7.17-7.20" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_clock_divider.v:9.16-9.23" *)
  output spi_clk;
  reg spi_clk;
  assign _1_ = counter + (* src = "RTL/spi_clock_divider.v:36.24-36.35" *) 32'd1;
  (* src = "RTL/spi_clock_divider.v:14.1-41.4" *)
  always @(posedge clk, posedge rst)
    if (rst) spi_clk <= 1'h0;
    else if (_2_) spi_clk <= _3_;
  assign _2_ = counter == (* src = "RTL/spi_clock_divider.v:27.12-27.36" *) 32'd1;
  assign _3_ = ~ (* src = "RTL/spi_clock_divider.v:30.24-30.32" *) spi_clk;
  (* src = "RTL/spi_clock_divider.v:14.1-41.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 32'd0;
    else counter <= _0_;
  assign _0_ = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_clock_divider.v:27.12-27.36|RTL/spi_clock_divider.v:27.9-38.12" *) 32'd0 : _1_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\spi_shift_register" *)
(* src = "RTL/spi_shift_register.v:1.1-66.10" *)
module \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000 (clk, rst, load, shift_enable, tx_data, miso, mosi, rx_data, shift_done);
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire [3:0] _00_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire [7:0] _01_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire _02_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire [7:0] _03_;
  (* src = "RTL/spi_shift_register.v:56.26-56.39" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _04_;
  wire _05_;
  (* src = "RTL/spi_shift_register.v:58.16-58.41" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire [3:0] _09_;
  wire [7:0] _10_;
  wire [7:0] _11_;
  (* src = "RTL/spi_shift_register.v:19.11-19.20" *)
  reg [3:0] bit_count;
  (* src = "RTL/spi_shift_register.v:6.17-6.20" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_shift_register.v:8.17-8.21" *)
  input load;
  wire load;
  (* src = "RTL/spi_shift_register.v:11.17-11.21" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_shift_register.v:13.17-13.21" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_shift_register.v:7.17-7.20" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_shift_register.v:14.33-14.40" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/spi_shift_register.v:15.16-15.26" *)
  output shift_done;
  reg shift_done;
  (* src = "RTL/spi_shift_register.v:9.17-9.29" *)
  input shift_enable;
  wire shift_enable;
  (* src = "RTL/spi_shift_register.v:10.34-10.41" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "RTL/spi_shift_register.v:18.22-18.30" *)
  reg [7:0] tx_shift;
  assign _04_ = bit_count + (* src = "RTL/spi_shift_register.v:56.26-56.39" *) 32'd1;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) tx_shift <= 8'h00;
    else if (_05_) tx_shift <= _03_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 4'h0;
    else if (_05_) bit_count <= _00_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_05_) rx_data <= _01_;
  assign _05_ = | { shift_enable, load };
  assign _06_ = bit_count == (* src = "RTL/spi_shift_register.v:58.16-58.41" *) 4'h7;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_done <= 1'h0;
    else shift_done <= _02_;
  assign _07_ = _06_ ? (* src = "RTL/spi_shift_register.v:58.16-58.41|RTL/spi_shift_register.v:58.13-60.33" *) 1'h1 : 1'h0;
  assign _08_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) _07_ : 1'h0;
  assign _02_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) 1'h0 : _08_;
  assign _09_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) _04_[3:0] : 4'hx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) 4'h0 : _09_;
  assign _10_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) { tx_shift[6:0], 1'h0 } : 8'hxx;
  assign _03_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) tx_data : _10_;
  assign _11_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) { rx_data[6:0], miso } : 8'hxx;
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) 8'h00 : _11_;
  assign mosi = tx_shift[7];
endmodule

(* src = "RTL/spi_chip_select.v:1.1-34.10" *)
module spi_chip_select(clk, rst, cs_enable, cs_n);
  (* src = "RTL/spi_chip_select.v:10.1-33.4" *)
  wire _0_;
  (* src = "RTL/spi_chip_select.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_chip_select.v:5.12-5.21" *)
  input cs_enable;
  wire cs_enable;
  (* src = "RTL/spi_chip_select.v:7.12-7.16" *)
  output cs_n;
  reg cs_n;
  (* src = "RTL/spi_chip_select.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_chip_select.v:10.1-33.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cs_n <= 1'h1;
    else cs_n <= _0_;
  assign _0_ = cs_enable ? (* full_case = 32'd1 *) (* src = "RTL/spi_chip_select.v:25.12-25.21|RTL/spi_chip_select.v:25.9-30.26" *) 1'h0 : 1'h1;
endmodule

(* src = "RTL/spi_master_fsm.v:1.1-84.10" *)
module spi_master_fsm(clk, rst, start, shift_done, load, shift_enable, cs_enable, done);
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  wire _00_;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  wire _01_;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  wire _02_;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  wire _03_;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  wire [1:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [1:0] _15_;
  wire [1:0] _16_;
  (* src = "RTL/spi_master_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master_fsm.v:10.12-10.21" *)
  output cs_enable;
  reg cs_enable;
  (* src = "RTL/spi_master_fsm.v:11.12-11.16" *)
  output done;
  reg done;
  (* src = "RTL/spi_master_fsm.v:8.12-8.16" *)
  output load;
  reg load;
  (* src = "RTL/spi_master_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master_fsm.v:6.12-6.22" *)
  input shift_done;
  wire shift_done;
  (* src = "RTL/spi_master_fsm.v:9.12-9.24" *)
  output shift_enable;
  reg shift_enable;
  (* src = "RTL/spi_master_fsm.v:5.12-5.17" *)
  input start;
  wire start;
  (* src = "RTL/spi_master_fsm.v:14.11-14.16" *)
  reg [1:0] state;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 2'h0;
    else if (_08_) state <= _04_;
  assign _05_ = { _14_, start } != 2'h2;
  assign _06_ = { _12_, shift_done } != 2'h2;
  assign _07_ = | { _14_, _13_, _12_, _11_ };
  assign _08_ = & { _05_, _07_, _06_ };
  assign _09_ = | { _14_, _11_ };
  assign _10_ = | { _12_, _13_ };
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cs_enable <= 1'h0;
    else cs_enable <= _00_;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load <= 1'h0;
    else load <= _02_;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_enable <= 1'h0;
    else shift_enable <= _03_;
  (* src = "RTL/spi_master_fsm.v:21.1-83.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  function [0:0] _28_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _28_ = b[0:0];
      2'b1?:
        _28_ = b[1:1];
      default:
        _28_ = a;
    endcase
  endfunction
  assign _00_ = _28_(1'hx, 2'h2, { _10_, _09_ });
  assign _01_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *) 1'h1 : 1'h0;
  assign _03_ = _12_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *) 1'h1 : 1'h0;
  assign _02_ = _13_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *) 1'h1 : 1'h0;
  function [1:0] _32_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _32_ = b[1:0];
      4'b??1?:
        _32_ = b[3:2];
      4'b?1??:
        _32_ = b[5:4];
      4'b1???:
        _32_ = b[7:6];
      default:
        _32_ = a;
    endcase
  endfunction
  assign _04_ = _32_(2'hx, { _16_, 2'h2, _15_, 2'h0 }, { _14_, _13_, _12_, _11_ });
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *) 2'h3;
  assign _15_ = shift_done ? (* src = "RTL/spi_master_fsm.v:67.16-67.26|RTL/spi_master_fsm.v:67.13-68.35" *) 2'h3 : 2'hx;
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *) 2'h2;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *) 2'h1;
  assign _16_ = start ? (* src = "RTL/spi_master_fsm.v:50.16-50.21|RTL/spi_master_fsm.v:50.13-51.31" *) 2'h1 : 2'hx;
  assign _14_ = ! (* full_case = 32'd1 *) (* src = "RTL/spi_master_fsm.v:0.0-0.0|RTL/spi_master_fsm.v:45.9-80.16" *) state;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/spi_master_top.v:1.1-79.10" *)
module spi_master_top(clk, rst, start, tx_data, miso, spi_clk, mosi, cs_n, rx_data, done);
  (* src = "RTL/spi_master_top.v:7.16-7.19" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_master_top.v:24.6-24.15" *)
  wire cs_enable;
  (* src = "RTL/spi_master_top.v:15.17-15.21" *)
  output cs_n;
  wire cs_n;
  (* src = "RTL/spi_master_top.v:17.17-17.21" *)
  output done;
  wire done;
  (* src = "RTL/spi_master_top.v:21.6-21.10" *)
  wire load;
  (* src = "RTL/spi_master_top.v:11.16-11.20" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_master_top.v:14.17-14.21" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_master_top.v:8.16-8.19" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_master_top.v:16.34-16.41" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "RTL/spi_master_top.v:23.6-23.16" *)
  wire shift_done;
  (* src = "RTL/spi_master_top.v:22.6-22.18" *)
  wire shift_enable;
  (* src = "RTL/spi_master_top.v:13.17-13.24" *)
  output spi_clk;
  wire spi_clk;
  (* src = "RTL/spi_master_top.v:9.16-9.21" *)
  input start;
  wire start;
  (* src = "RTL/spi_master_top.v:10.33-10.40" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_master_top.v:72.1-78.2" *)
  spi_chip_select chip_select (
    .clk(clk),
    .cs_enable(cs_enable),
    .cs_n(cs_n),
    .rst(rst)
  );
  (* src = "RTL/spi_master_top.v:31.1-36.2" *)
  \$paramod\spi_clock_divider\DIVIDER=s32'00000000000000000000000000000100  clock_divider (
    .clk(clk),
    .rst(rst),
    .spi_clk(spi_clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_master_top.v:58.1-68.2" *)
  spi_master_fsm fsm (
    .clk(clk),
    .cs_enable(cs_enable),
    .done(done),
    .load(load),
    .rst(rst),
    .shift_done(shift_done),
    .shift_enable(shift_enable),
    .start(start)
  );
  (* src = "RTL/spi_master_top.v:43.1-54.2" *)
  \$paramod\spi_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000  shift_register (
    .clk(spi_clk),
    .load(load),
    .miso(miso),
    .mosi(mosi),
    .rst(rst),
    .rx_data(rx_data),
    .shift_done(shift_done),
    .shift_enable(shift_enable),
    .tx_data(tx_data)
  );
endmodule
