/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/spi_chip_select.v:1.1-34.10" *)
module spi_chip_select(clk, rst, cs_enable, cs_n);
  (* src = "RTL/spi_chip_select.v:10.1-33.4" *)
  wire _0_;
  (* src = "RTL/spi_chip_select.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_chip_select.v:5.12-5.21" *)
  input cs_enable;
  wire cs_enable;
  (* src = "RTL/spi_chip_select.v:7.12-7.16" *)
  output cs_n;
  reg cs_n;
  (* src = "RTL/spi_chip_select.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_chip_select.v:10.1-33.4" *)
  always @(posedge clk, posedge rst)
    if (rst) cs_n <= 1'h1;
    else cs_n <= _0_;
  assign _0_ = cs_enable ? (* full_case = 32'd1 *) (* src = "RTL/spi_chip_select.v:25.12-25.21|RTL/spi_chip_select.v:25.9-30.26" *) 1'h0 : 1'h1;
endmodule
