/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/spi_shift_register.v:1.1-66.10" *)
module spi_shift_register(clk, rst, load, shift_enable, tx_data, miso, mosi, rx_data, shift_done);
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire [3:0] _00_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire [7:0] _01_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire _02_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  wire [7:0] _03_;
  (* src = "RTL/spi_shift_register.v:56.26-56.39" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _04_;
  wire _05_;
  (* src = "RTL/spi_shift_register.v:58.16-58.41" *)
  wire _06_;
  wire [3:0] _07_;
  wire [7:0] _08_;
  wire [7:0] _09_;
  wire _10_;
  wire _11_;
  (* src = "RTL/spi_shift_register.v:19.11-19.20" *)
  reg [3:0] bit_count;
  (* src = "RTL/spi_shift_register.v:6.17-6.20" *)
  input clk;
  wire clk;
  (* src = "RTL/spi_shift_register.v:8.17-8.21" *)
  input load;
  wire load;
  (* src = "RTL/spi_shift_register.v:11.17-11.21" *)
  input miso;
  wire miso;
  (* src = "RTL/spi_shift_register.v:13.17-13.21" *)
  output mosi;
  wire mosi;
  (* src = "RTL/spi_shift_register.v:7.17-7.20" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_shift_register.v:14.33-14.40" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/spi_shift_register.v:15.16-15.26" *)
  output shift_done;
  reg shift_done;
  (* src = "RTL/spi_shift_register.v:9.17-9.29" *)
  input shift_enable;
  wire shift_enable;
  (* src = "RTL/spi_shift_register.v:10.34-10.41" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "RTL/spi_shift_register.v:18.22-18.30" *)
  reg [7:0] tx_shift;
  assign _04_ = bit_count + (* src = "RTL/spi_shift_register.v:56.26-56.39" *) 32'd1;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_05_) rx_data <= _01_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) tx_shift <= 8'h00;
    else if (_05_) tx_shift <= _03_;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 4'h0;
    else if (_05_) bit_count <= _00_;
  assign _05_ = | { shift_enable, load };
  assign _06_ = bit_count == (* src = "RTL/spi_shift_register.v:58.16-58.41" *) 4'h7;
  (* src = "RTL/spi_shift_register.v:25.1-65.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_done <= 1'h0;
    else shift_done <= _02_;
  assign _07_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) _04_[3:0] : 4'hx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) 4'h0 : _07_;
  assign _08_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) { tx_shift[6:0], 1'h0 } : 8'hxx;
  assign _03_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) tx_data : _08_;
  assign _09_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) { rx_data[6:0], miso } : 8'hxx;
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) 8'h00 : _09_;
  assign _10_ = _06_ ? (* src = "RTL/spi_shift_register.v:58.16-58.41|RTL/spi_shift_register.v:58.13-60.33" *) 1'h1 : 1'h0;
  assign _11_ = shift_enable ? (* src = "RTL/spi_shift_register.v:51.17-51.29|RTL/spi_shift_register.v:51.14-62.12" *) _10_ : 1'h0;
  assign _02_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_shift_register.v:43.12-43.16|RTL/spi_shift_register.v:43.9-62.12" *) 1'h0 : _11_;
  assign mosi = tx_shift[7];
endmodule
