/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/hazard_detection_logic.v:1.1-40.10" *)
module hazard_detection_logic(rs1, rs2, rd, reg_write, stall, pc_write, if_id_write);
  (* src = "RTL/hazard_detection_logic.v:10.17-10.28" *)
  output if_id_write;
  wire if_id_write;
  (* src = "RTL/hazard_detection_logic.v:14.6-14.15" *)
  wire match_rs1;
  (* src = "RTL/hazard_detection_logic.v:15.6-15.15" *)
  wire match_rs2;
  (* src = "RTL/hazard_detection_logic.v:9.17-9.25" *)
  output pc_write;
  wire pc_write;
  (* src = "RTL/hazard_detection_logic.v:5.22-5.24" *)
  input [4:0] rd;
  wire [4:0] rd;
  (* src = "RTL/hazard_detection_logic.v:6.16-6.25" *)
  input reg_write;
  wire reg_write;
  (* src = "RTL/hazard_detection_logic.v:3.22-3.25" *)
  input [4:0] rs1;
  wire [4:0] rs1;
  (* src = "RTL/hazard_detection_logic.v:4.22-4.25" *)
  input [4:0] rs2;
  wire [4:0] rs2;
  (* src = "RTL/hazard_detection_logic.v:8.17-8.22" *)
  output stall;
  wire stall;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/hazard_detection_logic.v:18.21-27.2" *)
  register_comparator comparator (
    .match_rs1(match_rs1),
    .match_rs2(match_rs2),
    .rd(rd),
    .reg_write(reg_write),
    .rs1(rs1),
    .rs2(rs2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/hazard_detection_logic.v:30.26-38.2" *)
  pipeline_stall_generator stall_generator (
    .if_id_write(if_id_write),
    .match_rs1(match_rs1),
    .match_rs2(match_rs2),
    .pc_write(pc_write),
    .stall(stall)
  );
endmodule
