/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\spi_slave_bit_counter" *)
(* src = "RTL/spi_slave_bit_counter.v:1.1-43.10" *)
module \$paramod\spi_slave_bit_counter\DATA_WIDTH=s32'00000000000000000000000000001000 (spi_clk, rst, cs, done, bit_count);
  (* src = "RTL/spi_slave_bit_counter.v:12.1-42.4" *)
  wire [2:0] _00_;
  (* src = "RTL/spi_slave_bit_counter.v:12.1-42.4" *)
  wire _01_;
  (* src = "RTL/spi_slave_bit_counter.v:38.26-38.39" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _02_;
  (* src = "RTL/spi_slave_bit_counter.v:30.12-30.37" *)
  wire _03_;
  wire _04_;
  wire [2:0] _05_;
  (* src = "RTL/spi_slave_bit_counter.v:9.41-9.50" *)
  output [2:0] bit_count;
  reg [2:0] bit_count;
  (* src = "RTL/spi_slave_bit_counter.v:6.11-6.13" *)
  input cs;
  wire cs;
  (* src = "RTL/spi_slave_bit_counter.v:8.16-8.20" *)
  output done;
  reg done;
  (* src = "RTL/spi_slave_bit_counter.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_slave_bit_counter.v:4.11-4.18" *)
  input spi_clk;
  wire spi_clk;
  assign _02_ = bit_count + (* src = "RTL/spi_slave_bit_counter.v:38.26-38.39" *) 32'd1;
  assign _03_ = bit_count == (* src = "RTL/spi_slave_bit_counter.v:30.12-30.37" *) 3'h7;
  (* src = "RTL/spi_slave_bit_counter.v:12.1-42.4" *)
  always @(posedge spi_clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  (* src = "RTL/spi_slave_bit_counter.v:12.1-42.4" *)
  always @(posedge spi_clk, posedge rst)
    if (rst) bit_count <= 3'h0;
    else bit_count <= _00_;
  assign _04_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_slave_bit_counter.v:30.12-30.37|RTL/spi_slave_bit_counter.v:30.9-40.12" *) 1'h1 : 1'h0;
  assign _01_ = cs ? (* full_case = 32'd1 *) (* src = "RTL/spi_slave_bit_counter.v:21.13-21.15|RTL/spi_slave_bit_counter.v:21.10-41.8" *) 1'h0 : _04_;
  assign _05_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/spi_slave_bit_counter.v:30.12-30.37|RTL/spi_slave_bit_counter.v:30.9-40.12" *) 3'h0 : _02_[2:0];
  assign _00_ = cs ? (* full_case = 32'd1 *) (* src = "RTL/spi_slave_bit_counter.v:21.13-21.15|RTL/spi_slave_bit_counter.v:21.10-41.8" *) 3'h0 : _05_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\spi_slave_shift_register" *)
(* src = "RTL/spi_slave_shift_register.v:1.1-42.10" *)
module \$paramod\spi_slave_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000 (spi_clk, rst, cs, load, mosi, tx_data, miso, rx_data);
  (* src = "RTL/spi_slave_shift_register.v:19.1-41.4" *)
  wire [7:0] _00_;
  (* src = "RTL/spi_slave_shift_register.v:19.1-41.4" *)
  wire [7:0] _01_;
  wire _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  (* src = "RTL/spi_slave_shift_register.v:6.11-6.13" *)
  input cs;
  wire cs;
  (* src = "RTL/spi_slave_shift_register.v:7.11-7.15" *)
  input load;
  wire load;
  (* src = "RTL/spi_slave_shift_register.v:11.12-11.16" *)
  output miso;
  wire miso;
  (* src = "RTL/spi_slave_shift_register.v:8.11-8.15" *)
  input mosi;
  wire mosi;
  (* src = "RTL/spi_slave_shift_register.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_slave_shift_register.v:12.33-12.40" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/spi_slave_shift_register.v:4.11-4.18" *)
  input spi_clk;
  wire spi_clk;
  (* src = "RTL/spi_slave_shift_register.v:9.29-9.36" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "RTL/spi_slave_shift_register.v:15.22-15.34" *)
  reg [7:0] tx_shift_reg;
  (* src = "RTL/spi_slave_shift_register.v:19.1-41.4" *)
  always @(posedge spi_clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_02_) rx_data <= _00_;
  (* src = "RTL/spi_slave_shift_register.v:19.1-41.4" *)
  always @(posedge spi_clk, posedge rst)
    if (rst) tx_shift_reg <= 8'h00;
    else if (_02_) tx_shift_reg <= _01_;
  assign _02_ = { load, cs } != 2'h1;
  assign _03_ = cs ? (* src = "RTL/spi_slave_shift_register.v:33.14-33.17|RTL/spi_slave_shift_register.v:33.10-40.8" *) 8'hxx : { tx_shift_reg[6:0], 1'h0 };
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_slave_shift_register.v:27.14-27.18|RTL/spi_slave_shift_register.v:27.10-40.8" *) tx_data : _03_;
  assign _04_ = cs ? (* src = "RTL/spi_slave_shift_register.v:33.14-33.17|RTL/spi_slave_shift_register.v:33.10-40.8" *) 8'hxx : { rx_data[6:0], mosi };
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/spi_slave_shift_register.v:27.14-27.18|RTL/spi_slave_shift_register.v:27.10-40.8" *) 8'h00 : _04_;
  assign miso = tx_shift_reg[7];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/spi_slave.v:1.1-56.10" *)
module spi_slave(spi_clk, rst, cs, mosi, tx_data, miso, busy, rx_data);
  (* src = "RTL/spi_slave.v:17.31-17.40" *)
  (* unused_bits = "0 1 2" *)
  wire [2:0] bit_count;
  (* src = "RTL/spi_slave.v:11.12-11.16" *)
  output busy;
  wire busy;
  (* src = "RTL/spi_slave.v:6.11-6.13" *)
  input cs;
  wire cs;
  (* src = "RTL/spi_slave.v:16.6-16.10" *)
  wire done;
  (* src = "RTL/spi_slave.v:15.6-15.10" *)
  wire load;
  (* src = "RTL/spi_slave.v:10.12-10.16" *)
  output miso;
  wire miso;
  (* src = "RTL/spi_slave.v:7.11-7.15" *)
  input mosi;
  wire mosi;
  (* src = "RTL/spi_slave.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_slave.v:12.29-12.36" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "RTL/spi_slave.v:4.11-4.18" *)
  input spi_clk;
  wire spi_clk;
  (* src = "RTL/spi_slave.v:8.28-8.35" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/spi_slave.v:19.22-28.2" *)
  spi_slave_controller controller (
    .busy(busy),
    .cs(cs),
    .done(done),
    .load(load),
    .rst(rst),
    .spi_clk(spi_clk)
  );
  (* src = "RTL/spi_slave.v:47.3-55.2" *)
  \$paramod\spi_slave_bit_counter\DATA_WIDTH=s32'00000000000000000000000000001000  counter (
    .bit_count(bit_count),
    .cs(cs),
    .done(done),
    .rst(rst),
    .spi_clk(spi_clk)
  );
  (* src = "RTL/spi_slave.v:32.3-43.2" *)
  \$paramod\spi_slave_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000  shift_register (
    .cs(cs),
    .load(load),
    .miso(miso),
    .mosi(mosi),
    .rst(rst),
    .rx_data(rx_data),
    .spi_clk(spi_clk),
    .tx_data(tx_data)
  );
endmodule

(* src = "RTL/spi_slave_controller.v:1.1-94.10" *)
module spi_slave_controller(spi_clk, rst, cs, done, load, busy);
  (* src = "RTL/spi_slave_controller.v:20.1-59.4" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [1:0] _13_;
  wire [1:0] _14_;
  wire [1:0] _15_;
  (* src = "RTL/spi_slave_controller.v:9.16-9.20" *)
  output busy;
  wire busy;
  (* src = "RTL/spi_slave_controller.v:5.11-5.13" *)
  input cs;
  wire cs;
  (* src = "RTL/spi_slave_controller.v:6.11-6.15" *)
  input done;
  wire done;
  (* src = "RTL/spi_slave_controller.v:8.16-8.20" *)
  output load;
  wire load;
  (* src = "RTL/spi_slave_controller.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/spi_slave_controller.v:3.11-3.18" *)
  input spi_clk;
  wire spi_clk;
  (* src = "RTL/spi_slave_controller.v:18.11-18.16" *)
  reg [1:0] state;
  (* src = "RTL/spi_slave_controller.v:20.1-59.4" *)
  always @(posedge spi_clk, posedge rst)
    if (rst) state <= 2'h0;
    else if (_05_) state <= _00_;
  assign _01_ = { _09_, cs } != 2'h2;
  assign _02_ = { _12_, cs } != 2'h3;
  assign _03_ = { _10_, done } != 2'h2;
  assign _04_ = | { _12_, _11_, _10_, _09_ };
  assign _05_ = & { _04_, _01_, _02_, _03_ };
  assign _06_ = | { _12_, _09_, _10_ };
  assign _07_ = | { _12_, _09_ };
  assign _08_ = | { _11_, _10_ };
  function [0:0] _25_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_slave_controller.v:0.0-0.0|RTL/spi_slave_controller.v:67.5-92.12" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _25_ = b[0:0];
      2'b1?:
        _25_ = b[1:1];
      default:
        _25_ = a;
    endcase
  endfunction
  assign busy = _25_(1'hx, 2'h2, { _08_, _07_ });
  function [0:0] _26_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_slave_controller.v:0.0-0.0|RTL/spi_slave_controller.v:67.5-92.12" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _26_ = b[0:0];
      2'b1?:
        _26_ = b[1:1];
      default:
        _26_ = a;
    endcase
  endfunction
  assign load = _26_(1'hx, 2'h2, { _11_, _06_ });
  assign _13_ = cs ? (* src = "RTL/spi_slave_controller.v:50.16-50.18|RTL/spi_slave_controller.v:50.13-51.31" *) 2'h0 : 2'hx;
  function [1:0] _28_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/spi_slave_controller.v:0.0-0.0|RTL/spi_slave_controller.v:29.9-57.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _28_ = b[1:0];
      4'b??1?:
        _28_ = b[3:2];
      4'b?1??:
        _28_ = b[5:4];
      4'b1???:
        _28_ = b[7:6];
      default:
        _28_ = a;
    endcase
  endfunction
  assign _00_ = _28_(2'hx, { _15_, 2'h2, _14_, _13_ }, { _12_, _11_, _10_, _09_ });
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_slave_controller.v:0.0-0.0|RTL/spi_slave_controller.v:29.9-57.16" *) 2'h3;
  assign _14_ = done ? (* src = "RTL/spi_slave_controller.v:44.16-44.20|RTL/spi_slave_controller.v:44.13-45.35" *) 2'h3 : 2'hx;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_slave_controller.v:0.0-0.0|RTL/spi_slave_controller.v:29.9-57.16" *) 2'h2;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/spi_slave_controller.v:0.0-0.0|RTL/spi_slave_controller.v:29.9-57.16" *) 2'h1;
  assign _15_ = cs ? (* src = "RTL/spi_slave_controller.v:33.16-33.19|RTL/spi_slave_controller.v:33.13-34.31" *) 2'hx : 2'h1;
  assign _12_ = ! (* full_case = 32'd1 *) (* src = "RTL/spi_slave_controller.v:0.0-0.0|RTL/spi_slave_controller.v:29.9-57.16" *) state;
endmodule
