/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\axi_read_address" *)
(* src = "RTL/axi_read_address.v:1.1-54.10" *)
module \$paramod\axi_read_address\ADDR_WIDTH=s32'00000000000000000000000000100000 (clk, rst, start, address, arready, araddr, arvalid, done);
  (* src = "RTL/axi_read_address.v:20.1-53.4" *)
  wire _00_;
  (* src = "RTL/axi_read_address.v:20.1-53.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_read_address.v:45.12-45.30" *)
  wire _03_;
  wire _04_;
  (* src = "RTL/axi_read_address.v:12.29-12.36" *)
  input [31:0] address;
  wire [31:0] address;
  (* src = "RTL/axi_read_address.v:15.29-15.35" *)
  output [31:0] araddr;
  reg [31:0] araddr;
  (* src = "RTL/axi_read_address.v:13.12-13.19" *)
  input arready;
  wire arready;
  (* src = "RTL/axi_read_address.v:16.12-16.19" *)
  output arvalid;
  reg arvalid;
  (* src = "RTL/axi_read_address.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_read_address.v:17.12-17.16" *)
  output done;
  reg done;
  (* src = "RTL/axi_read_address.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_read_address.v:11.12-11.17" *)
  input start;
  wire start;
  (* src = "RTL/axi_read_address.v:20.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) araddr <= 32'd0;
    else if (start) araddr <= address;
  (* src = "RTL/axi_read_address.v:20.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) arvalid <= 1'h0;
    else if (_02_) arvalid <= _00_;
  assign _02_ = | { _03_, start };
  assign _03_ = arvalid && (* src = "RTL/axi_read_address.v:45.12-45.30" *) arready;
  (* src = "RTL/axi_read_address.v:20.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _01_ = _03_ ? (* src = "RTL/axi_read_address.v:45.12-45.30|RTL/axi_read_address.v:45.9-51.12" *) 1'h1 : 1'h0;
  assign _04_ = start ? (* src = "RTL/axi_read_address.v:37.12-37.17|RTL/axi_read_address.v:37.9-43.12" *) 1'h1 : 1'hx;
  assign _00_ = _03_ ? (* src = "RTL/axi_read_address.v:45.12-45.30|RTL/axi_read_address.v:45.9-51.12" *) 1'h0 : _04_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\axi_read_data" *)
(* src = "RTL/axi_read_data.v:1.1-54.10" *)
module \$paramod\axi_read_data\DATA_WIDTH=s32'00000000000000000000000000100000 (clk, rst, rdata, rvalid, rready, data_out, done);
  (* src = "RTL/axi_read_data.v:20.1-53.4" *)
  wire _0_;
  (* src = "RTL/axi_read_data.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_read_data.v:15.29-15.37" *)
  output [31:0] data_out;
  reg [31:0] data_out;
  (* src = "RTL/axi_read_data.v:16.12-16.16" *)
  output done;
  wire done;
  (* src = "RTL/axi_read_data.v:11.29-11.34" *)
  input [31:0] rdata;
  wire [31:0] rdata;
  (* src = "RTL/axi_read_data.v:14.12-14.18" *)
  output rready;
  reg rready;
  (* src = "RTL/axi_read_data.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_read_data.v:12.12-12.18" *)
  input rvalid;
  wire rvalid;
  (* src = "RTL/axi_read_data.v:20.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) data_out <= 32'd0;
    else if (rvalid) data_out <= rdata;
  (* src = "RTL/axi_read_data.v:20.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rready <= 1'h0;
    else rready <= _0_;
  assign _0_ = rvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_read_data.v:37.12-37.18|RTL/axi_read_data.v:37.9-51.12" *) 1'h1 : 1'h0;
  assign done = rready;
endmodule

(* dynports =  1  *)
(* hdlname = "\\axi_write_address" *)
(* src = "RTL/axi_write_address.v:1.1-52.10" *)
module \$paramod\axi_write_address\ADDR_WIDTH=s32'00000000000000000000000000100000 (clk, rst, start, address, awready, awaddr, awvalid, done);
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  wire _00_;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_write_address.v:43.12-43.30" *)
  wire _03_;
  wire _04_;
  (* src = "RTL/axi_write_address.v:12.29-12.36" *)
  input [31:0] address;
  wire [31:0] address;
  (* src = "RTL/axi_write_address.v:15.29-15.35" *)
  output [31:0] awaddr;
  reg [31:0] awaddr;
  (* src = "RTL/axi_write_address.v:13.12-13.19" *)
  input awready;
  wire awready;
  (* src = "RTL/axi_write_address.v:16.12-16.19" *)
  output awvalid;
  reg awvalid;
  (* src = "RTL/axi_write_address.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_write_address.v:17.12-17.16" *)
  output done;
  reg done;
  (* src = "RTL/axi_write_address.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_write_address.v:11.12-11.17" *)
  input start;
  wire start;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) awaddr <= 32'd0;
    else if (start) awaddr <= address;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) awvalid <= 1'h0;
    else if (_02_) awvalid <= _00_;
  assign _02_ = | { _03_, start };
  assign _03_ = awvalid && (* src = "RTL/axi_write_address.v:43.12-43.30" *) awready;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _01_ = _03_ ? (* src = "RTL/axi_write_address.v:43.12-43.30|RTL/axi_write_address.v:43.9-49.12" *) 1'h1 : 1'h0;
  assign _04_ = start ? (* src = "RTL/axi_write_address.v:35.12-35.17|RTL/axi_write_address.v:35.9-41.12" *) 1'h1 : 1'hx;
  assign _00_ = _03_ ? (* src = "RTL/axi_write_address.v:43.12-43.30|RTL/axi_write_address.v:43.9-49.12" *) 1'h0 : _04_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\axi_write_data" *)
(* src = "RTL/axi_write_data.v:1.1-55.10" *)
module \$paramod\axi_write_data\DATA_WIDTH=s32'00000000000000000000000000100000 (clk, rst, start, data, wready, wdata, wvalid, done);
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  wire _00_;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_write_data.v:46.12-46.28" *)
  wire _03_;
  wire _04_;
  (* src = "RTL/axi_write_data.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_write_data.v:12.29-12.33" *)
  input [31:0] data;
  wire [31:0] data;
  (* src = "RTL/axi_write_data.v:17.12-17.16" *)
  output done;
  reg done;
  (* src = "RTL/axi_write_data.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_write_data.v:11.12-11.17" *)
  input start;
  wire start;
  (* src = "RTL/axi_write_data.v:15.29-15.34" *)
  output [31:0] wdata;
  reg [31:0] wdata;
  (* src = "RTL/axi_write_data.v:13.12-13.18" *)
  input wready;
  wire wready;
  (* src = "RTL/axi_write_data.v:16.12-16.18" *)
  output wvalid;
  reg wvalid;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wdata <= 32'd0;
    else if (start) wdata <= data;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wvalid <= 1'h0;
    else if (_02_) wvalid <= _01_;
  assign _02_ = | { _03_, start };
  assign _03_ = wvalid && (* src = "RTL/axi_write_data.v:46.12-46.28" *) wready;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _00_;
  assign _00_ = _03_ ? (* src = "RTL/axi_write_data.v:46.12-46.28|RTL/axi_write_data.v:46.9-52.12" *) 1'h1 : 1'h0;
  assign _04_ = start ? (* src = "RTL/axi_write_data.v:38.12-38.17|RTL/axi_write_data.v:38.9-44.12" *) 1'h1 : 1'hx;
  assign _01_ = _03_ ? (* src = "RTL/axi_write_data.v:46.12-46.28|RTL/axi_write_data.v:46.9-52.12" *) 1'h0 : _04_;
endmodule

(* src = "RTL/axi_master_fsm.v:1.1-146.10" *)
module axi_master_fsm(clk, rst, start_write, start_read, aw_done, w_done, b_done, ar_done, r_done, aw_start, w_start, ar_start, done);
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _00_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _01_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _02_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire [2:0] _03_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [2:0] _13_;
  wire _14_;
  wire [2:0] _15_;
  wire _16_;
  wire [2:0] _17_;
  wire [2:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [2:0] _22_;
  wire _23_;
  wire [2:0] _24_;
  wire [2:0] _25_;
  (* src = "RTL/axi_master_fsm.v:10.16-10.23" *)
  input ar_done;
  wire ar_done;
  (* src = "RTL/axi_master_fsm.v:15.16-15.24" *)
  output ar_start;
  reg ar_start;
  (* src = "RTL/axi_master_fsm.v:7.16-7.23" *)
  input aw_done;
  wire aw_done;
  (* src = "RTL/axi_master_fsm.v:13.16-13.24" *)
  output aw_start;
  reg aw_start;
  (* src = "RTL/axi_master_fsm.v:9.16-9.22" *)
  input b_done;
  wire b_done;
  (* src = "RTL/axi_master_fsm.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_master_fsm.v:16.16-16.20" *)
  output done;
  reg done;
  (* src = "RTL/axi_master_fsm.v:11.16-11.22" *)
  input r_done;
  wire r_done;
  (* src = "RTL/axi_master_fsm.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_master_fsm.v:6.16-6.26" *)
  input start_read;
  wire start_read;
  (* src = "RTL/axi_master_fsm.v:5.16-5.27" *)
  input start_write;
  wire start_write;
  (* src = "RTL/axi_master_fsm.v:28.11-28.16" *)
  reg [2:0] state;
  (* src = "RTL/axi_master_fsm.v:8.16-8.22" *)
  input w_done;
  wire w_done;
  (* src = "RTL/axi_master_fsm.v:14.16-14.23" *)
  output w_start;
  reg w_start;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_11_) state <= _03_;
  assign _05_ = { _19_, start_read, start_write } != 3'h4;
  assign _06_ = { _16_, aw_done } != 2'h2;
  assign _07_ = { _14_, w_done } != 2'h2;
  assign _08_ = { _12_, b_done } != 2'h2;
  assign _09_ = { _21_, ar_done } != 2'h2;
  assign _10_ = { _23_, r_done } != 2'h2;
  assign _11_ = & { _10_, _09_, _08_, _07_, _06_, _05_ };
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) aw_start <= 1'h0;
    else aw_start <= _01_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) w_start <= 1'h0;
    else w_start <= _04_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) ar_start <= 1'h0;
    else ar_start <= _00_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _02_;
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h3;
  assign _13_ = w_done ? (* src = "RTL/axi_master_fsm.v:87.16-87.22|RTL/axi_master_fsm.v:87.13-88.34" *) 3'h3 : 3'hx;
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h2;
  assign _15_ = aw_done ? (* src = "RTL/axi_master_fsm.v:75.16-75.23|RTL/axi_master_fsm.v:75.13-76.34" *) 3'h2 : 3'hx;
  assign _16_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h1;
  assign _17_ = start_read ? (* src = "RTL/axi_master_fsm.v:63.21-63.31|RTL/axi_master_fsm.v:63.18-64.34" *) 3'h4 : 3'hx;
  assign _18_ = start_write ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:60.16-60.27|RTL/axi_master_fsm.v:60.13-64.34" *) 3'h1 : _17_;
  assign _19_ = ! (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) state;
  assign _02_ = _20_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
  assign _20_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h6;
  assign _00_ = _21_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
  assign _04_ = _14_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
  assign _01_ = _16_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
  assign _22_ = r_done ? (* src = "RTL/axi_master_fsm.v:119.16-119.22|RTL/axi_master_fsm.v:119.13-120.37" *) 3'h6 : 3'hx;
  function [2:0] _52_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _52_ = b[2:0];
      6'b????1?:
        _52_ = b[5:3];
      6'b???1??:
        _52_ = b[8:6];
      6'b??1???:
        _52_ = b[11:9];
      6'b?1????:
        _52_ = b[14:12];
      6'b1?????:
        _52_ = b[17:15];
      default:
        _52_ = a;
    endcase
  endfunction
  assign _03_ = _52_(3'h0, { _18_, _15_, _13_, _25_, _24_, _22_ }, { _19_, _16_, _14_, _12_, _21_, _23_ });
  assign _23_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h5;
  assign _24_ = ar_done ? (* src = "RTL/axi_master_fsm.v:109.16-109.23|RTL/axi_master_fsm.v:109.13-110.34" *) 3'h5 : 3'hx;
  assign _21_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h4;
  assign _25_ = b_done ? (* src = "RTL/axi_master_fsm.v:97.16-97.22|RTL/axi_master_fsm.v:97.13-98.37" *) 3'h6 : 3'hx;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/axi_master_top.v:1.1-185.10" *)
module axi_master_top(clk, rst, start_write, start_read, write_address, read_address, write_data, awready, wready, bresp, bvalid, arready, rdata, rvalid, awaddr, awvalid, wdata, wvalid, bready, araddr, arvalid
, rready, data_out, done);
  (* src = "RTL/axi_master_top.v:52.6-52.13" *)
  wire ar_done;
  (* src = "RTL/axi_master_top.v:48.6-48.14" *)
  wire ar_start;
  (* src = "RTL/axi_master_top.v:36.30-36.36" *)
  output [31:0] araddr;
  wire [31:0] araddr;
  (* src = "RTL/axi_master_top.v:25.12-25.19" *)
  input arready;
  wire arready;
  (* src = "RTL/axi_master_top.v:37.13-37.20" *)
  output arvalid;
  wire arvalid;
  (* src = "RTL/axi_master_top.v:49.6-49.13" *)
  wire aw_done;
  (* src = "RTL/axi_master_top.v:46.6-46.14" *)
  wire aw_start;
  (* src = "RTL/axi_master_top.v:31.30-31.36" *)
  output [31:0] awaddr;
  wire [31:0] awaddr;
  (* src = "RTL/axi_master_top.v:21.12-21.19" *)
  input awready;
  wire awready;
  (* src = "RTL/axi_master_top.v:32.13-32.20" *)
  output awvalid;
  wire awvalid;
  (* src = "RTL/axi_master_top.v:51.6-51.12" *)
  wire b_done;
  (* src = "RTL/axi_master_top.v:35.13-35.19" *)
  output bready;
  wire bready;
  (* src = "RTL/axi_master_top.v:23.18-23.23" *)
  input [1:0] bresp;
  wire [1:0] bresp;
  (* src = "RTL/axi_master_top.v:24.12-24.18" *)
  input bvalid;
  wire bvalid;
  (* src = "RTL/axi_master_top.v:11.12-11.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_master_top.v:39.30-39.38" *)
  output [31:0] data_out;
  wire [31:0] data_out;
  (* src = "RTL/axi_master_top.v:40.13-40.17" *)
  output done;
  wire done;
  (* src = "RTL/axi_master_top.v:54.6-54.11" *)
  (* unused_bits = "0" *)
  wire error;
  (* src = "RTL/axi_master_top.v:53.6-53.12" *)
  wire r_done;
  (* src = "RTL/axi_master_top.v:26.29-26.34" *)
  input [31:0] rdata;
  wire [31:0] rdata;
  (* src = "RTL/axi_master_top.v:16.29-16.41" *)
  input [31:0] read_address;
  wire [31:0] read_address;
  (* src = "RTL/axi_master_top.v:38.13-38.19" *)
  output rready;
  wire rready;
  (* src = "RTL/axi_master_top.v:12.12-12.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_master_top.v:27.12-27.18" *)
  input rvalid;
  wire rvalid;
  (* src = "RTL/axi_master_top.v:14.12-14.22" *)
  input start_read;
  wire start_read;
  (* src = "RTL/axi_master_top.v:13.12-13.23" *)
  input start_write;
  wire start_write;
  (* src = "RTL/axi_master_top.v:50.6-50.12" *)
  wire w_done;
  (* src = "RTL/axi_master_top.v:47.6-47.13" *)
  wire w_start;
  (* src = "RTL/axi_master_top.v:33.30-33.35" *)
  output [31:0] wdata;
  wire [31:0] wdata;
  (* src = "RTL/axi_master_top.v:22.12-22.18" *)
  input wready;
  wire wready;
  (* src = "RTL/axi_master_top.v:15.29-15.42" *)
  input [31:0] write_address;
  wire [31:0] write_address;
  (* src = "RTL/axi_master_top.v:17.29-17.39" *)
  input [31:0] write_data;
  wire [31:0] write_data;
  (* src = "RTL/axi_master_top.v:34.13-34.19" *)
  output wvalid;
  wire wvalid;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/axi_master_top.v:58.16-75.2" *)
  axi_master_fsm fsm (
    .ar_done(ar_done),
    .ar_start(ar_start),
    .aw_done(aw_done),
    .aw_start(aw_start),
    .b_done(b_done),
    .clk(clk),
    .done(done),
    .r_done(r_done),
    .rst(rst),
    .start_read(start_read),
    .start_write(start_write),
    .w_done(w_done),
    .w_start(w_start)
  );
  (* src = "RTL/axi_master_top.v:150.1-161.2" *)
  \$paramod\axi_read_address\ADDR_WIDTH=s32'00000000000000000000000000100000  read_address_inst (
    .address(read_address),
    .araddr(araddr),
    .arready(arready),
    .arvalid(arvalid),
    .clk(clk),
    .done(ar_done),
    .rst(rst),
    .start(ar_start)
  );
  (* src = "RTL/axi_master_top.v:173.1-183.2" *)
  \$paramod\axi_read_data\DATA_WIDTH=s32'00000000000000000000000000100000  read_data_inst (
    .clk(clk),
    .data_out(data_out),
    .done(r_done),
    .rdata(rdata),
    .rready(rready),
    .rst(rst),
    .rvalid(rvalid)
  );
  (* src = "RTL/axi_master_top.v:86.1-98.2" *)
  \$paramod\axi_write_address\ADDR_WIDTH=s32'00000000000000000000000000100000  write_address_inst (
    .address(write_address),
    .awaddr(awaddr),
    .awready(awready),
    .awvalid(awvalid),
    .clk(clk),
    .done(aw_done),
    .rst(rst),
    .start(aw_start)
  );
  (* src = "RTL/axi_master_top.v:110.1-122.2" *)
  \$paramod\axi_write_data\DATA_WIDTH=s32'00000000000000000000000000100000  write_data_inst (
    .clk(clk),
    .data(write_data),
    .done(w_done),
    .rst(rst),
    .start(w_start),
    .wdata(wdata),
    .wready(wready),
    .wvalid(wvalid)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/axi_master_top.v:127.20-138.2" *)
  axi_write_response write_response_inst (
    .bready(bready),
    .bresp(bresp),
    .bvalid(bvalid),
    .clk(clk),
    .done(b_done),
    .error(error),
    .rst(rst)
  );
endmodule

(* src = "RTL/axi_write_response.v:1.1-52.10" *)
module axi_write_response(clk, rst, bresp, bvalid, bready, done, error);
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  wire _00_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  wire _01_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  wire _02_;
  (* src = "RTL/axi_write_response.v:37.16-37.30" *)
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "RTL/axi_write_response.v:8.12-8.18" *)
  output bready;
  reg bready;
  (* src = "RTL/axi_write_response.v:5.18-5.23" *)
  input [1:0] bresp;
  wire [1:0] bresp;
  (* src = "RTL/axi_write_response.v:6.12-6.18" *)
  input bvalid;
  wire bvalid;
  (* src = "RTL/axi_write_response.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_write_response.v:9.12-9.16" *)
  output done;
  reg done;
  (* src = "RTL/axi_write_response.v:10.12-10.17" *)
  output error;
  reg error;
  (* src = "RTL/axi_write_response.v:4.12-4.15" *)
  input rst;
  wire rst;
  assign _03_ = ! (* src = "RTL/axi_write_response.v:37.16-37.30" *) bresp;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bready <= 1'h0;
    else bready <= _00_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) error <= 1'h0;
    else error <= _02_;
  assign _00_ = bvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:32.12-32.18|RTL/axi_write_response.v:32.9-49.12" *) 1'h1 : 1'h0;
  assign _04_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:37.16-37.30|RTL/axi_write_response.v:37.13-40.31" *) 1'h0 : 1'h1;
  assign _02_ = bvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:32.12-32.18|RTL/axi_write_response.v:32.9-49.12" *) _04_ : 1'h0;
  assign _05_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:37.16-37.30|RTL/axi_write_response.v:37.13-40.31" *) 1'h1 : 1'h0;
  assign _01_ = bvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:32.12-32.18|RTL/axi_write_response.v:32.9-49.12" *) _05_ : 1'h0;
endmodule
