/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/axi_write_address.v:1.1-52.10" *)
module axi_write_address(clk, rst, start, address, awready, awaddr, awvalid, done);
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  wire _00_;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_write_address.v:43.12-43.30" *)
  wire _03_;
  wire _04_;
  (* src = "RTL/axi_write_address.v:12.29-12.36" *)
  input [31:0] address;
  wire [31:0] address;
  (* src = "RTL/axi_write_address.v:15.29-15.35" *)
  output [31:0] awaddr;
  reg [31:0] awaddr;
  (* src = "RTL/axi_write_address.v:13.12-13.19" *)
  input awready;
  wire awready;
  (* src = "RTL/axi_write_address.v:16.12-16.19" *)
  output awvalid;
  reg awvalid;
  (* src = "RTL/axi_write_address.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_write_address.v:17.12-17.16" *)
  output done;
  reg done;
  (* src = "RTL/axi_write_address.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_write_address.v:11.12-11.17" *)
  input start;
  wire start;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) awaddr <= 32'd0;
    else if (start) awaddr <= address;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) awvalid <= 1'h0;
    else if (_02_) awvalid <= _00_;
  assign _02_ = | { _03_, start };
  assign _03_ = awvalid && (* src = "RTL/axi_write_address.v:43.12-43.30" *) awready;
  (* src = "RTL/axi_write_address.v:21.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _01_ = _03_ ? (* src = "RTL/axi_write_address.v:43.12-43.30|RTL/axi_write_address.v:43.9-49.12" *) 1'h1 : 1'h0;
  assign _04_ = start ? (* src = "RTL/axi_write_address.v:35.12-35.17|RTL/axi_write_address.v:35.9-41.12" *) 1'h1 : 1'hx;
  assign _00_ = _03_ ? (* src = "RTL/axi_write_address.v:43.12-43.30|RTL/axi_write_address.v:43.9-49.12" *) 1'h0 : _04_;
endmodule
