/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/axi_write_response.v:1.1-52.10" *)
module axi_write_response(clk, rst, bresp, bvalid, bready, done, error);
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  wire _00_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  wire _01_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  wire _02_;
  (* src = "RTL/axi_write_response.v:37.16-37.30" *)
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "RTL/axi_write_response.v:8.12-8.18" *)
  output bready;
  reg bready;
  (* src = "RTL/axi_write_response.v:5.18-5.23" *)
  input [1:0] bresp;
  wire [1:0] bresp;
  (* src = "RTL/axi_write_response.v:6.12-6.18" *)
  input bvalid;
  wire bvalid;
  (* src = "RTL/axi_write_response.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_write_response.v:9.12-9.16" *)
  output done;
  reg done;
  (* src = "RTL/axi_write_response.v:10.12-10.17" *)
  output error;
  reg error;
  (* src = "RTL/axi_write_response.v:4.12-4.15" *)
  input rst;
  wire rst;
  assign _03_ = ! (* src = "RTL/axi_write_response.v:37.16-37.30" *) bresp;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bready <= 1'h0;
    else bready <= _00_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  (* src = "RTL/axi_write_response.v:14.1-51.4" *)
  always @(posedge clk, posedge rst)
    if (rst) error <= 1'h0;
    else error <= _02_;
  assign _02_ = bvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:32.12-32.18|RTL/axi_write_response.v:32.9-49.12" *) _05_ : 1'h0;
  assign _04_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:37.16-37.30|RTL/axi_write_response.v:37.13-40.31" *) 1'h1 : 1'h0;
  assign _01_ = bvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:32.12-32.18|RTL/axi_write_response.v:32.9-49.12" *) _04_ : 1'h0;
  assign _00_ = bvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:32.12-32.18|RTL/axi_write_response.v:32.9-49.12" *) 1'h1 : 1'h0;
  assign _05_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_write_response.v:37.16-37.30|RTL/axi_write_response.v:37.13-40.31" *) 1'h0 : 1'h1;
endmodule
