/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/axi_master_fsm.v:1.1-146.10" *)
module axi_master_fsm(clk, rst, start_write, start_read, aw_done, w_done, b_done, ar_done, r_done, aw_start, w_start, ar_start, done);
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _00_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _01_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _02_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire [2:0] _03_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [2:0] _14_;
  wire _15_;
  wire [2:0] _16_;
  wire _17_;
  wire [2:0] _18_;
  wire _19_;
  wire [2:0] _20_;
  wire [2:0] _21_;
  wire [2:0] _22_;
  wire [2:0] _23_;
  wire _24_;
  wire _25_;
  (* src = "RTL/axi_master_fsm.v:10.16-10.23" *)
  input ar_done;
  wire ar_done;
  (* src = "RTL/axi_master_fsm.v:15.16-15.24" *)
  output ar_start;
  reg ar_start;
  (* src = "RTL/axi_master_fsm.v:7.16-7.23" *)
  input aw_done;
  wire aw_done;
  (* src = "RTL/axi_master_fsm.v:13.16-13.24" *)
  output aw_start;
  reg aw_start;
  (* src = "RTL/axi_master_fsm.v:9.16-9.22" *)
  input b_done;
  wire b_done;
  (* src = "RTL/axi_master_fsm.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_master_fsm.v:16.16-16.20" *)
  output done;
  reg done;
  (* src = "RTL/axi_master_fsm.v:11.16-11.22" *)
  input r_done;
  wire r_done;
  (* src = "RTL/axi_master_fsm.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_master_fsm.v:6.16-6.26" *)
  input start_read;
  wire start_read;
  (* src = "RTL/axi_master_fsm.v:5.16-5.27" *)
  input start_write;
  wire start_write;
  (* src = "RTL/axi_master_fsm.v:28.11-28.16" *)
  reg [2:0] state;
  (* src = "RTL/axi_master_fsm.v:8.16-8.22" *)
  input w_done;
  wire w_done;
  (* src = "RTL/axi_master_fsm.v:14.16-14.23" *)
  output w_start;
  reg w_start;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_11_) state <= _03_;
  assign _05_ = { _24_, start_read, start_write } != 3'h4;
  assign _06_ = { _13_, aw_done } != 2'h2;
  assign _07_ = { _12_, w_done } != 2'h2;
  assign _08_ = { _19_, b_done } != 2'h2;
  assign _09_ = { _17_, ar_done } != 2'h2;
  assign _10_ = { _15_, r_done } != 2'h2;
  assign _11_ = & { _10_, _09_, _08_, _07_, _05_, _06_ };
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) aw_start <= 1'h0;
    else aw_start <= _01_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) w_start <= 1'h0;
    else w_start <= _04_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) ar_start <= 1'h0;
    else ar_start <= _00_;
  (* src = "RTL/axi_master_fsm.v:30.1-145.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _02_;
  assign _04_ = _12_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
  assign _01_ = _13_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
  assign _14_ = r_done ? (* src = "RTL/axi_master_fsm.v:119.16-119.22|RTL/axi_master_fsm.v:119.13-120.37" *) 3'h6 : 3'hx;
  function [2:0] _41_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _41_ = b[2:0];
      6'b????1?:
        _41_ = b[5:3];
      6'b???1??:
        _41_ = b[8:6];
      6'b??1???:
        _41_ = b[11:9];
      6'b?1????:
        _41_ = b[14:12];
      6'b1?????:
        _41_ = b[17:15];
      default:
        _41_ = a;
    endcase
  endfunction
  assign _03_ = _41_(3'h0, { _23_, _21_, _20_, _18_, _16_, _14_ }, { _24_, _13_, _12_, _19_, _17_, _15_ });
  assign _02_ = _25_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h5;
  assign _16_ = ar_done ? (* src = "RTL/axi_master_fsm.v:109.16-109.23|RTL/axi_master_fsm.v:109.13-110.34" *) 3'h5 : 3'hx;
  assign _17_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h4;
  assign _18_ = b_done ? (* src = "RTL/axi_master_fsm.v:97.16-97.22|RTL/axi_master_fsm.v:97.13-98.37" *) 3'h6 : 3'hx;
  assign _19_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h3;
  assign _20_ = w_done ? (* src = "RTL/axi_master_fsm.v:87.16-87.22|RTL/axi_master_fsm.v:87.13-88.34" *) 3'h3 : 3'hx;
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h2;
  assign _21_ = aw_done ? (* src = "RTL/axi_master_fsm.v:75.16-75.23|RTL/axi_master_fsm.v:75.13-76.34" *) 3'h2 : 3'hx;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h1;
  assign _22_ = start_read ? (* src = "RTL/axi_master_fsm.v:63.21-63.31|RTL/axi_master_fsm.v:63.18-64.34" *) 3'h4 : 3'hx;
  assign _23_ = start_write ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:60.16-60.27|RTL/axi_master_fsm.v:60.13-64.34" *) 3'h1 : _22_;
  assign _24_ = ! (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) state;
  assign _25_ = state == (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 3'h6;
  assign _00_ = _17_ ? (* full_case = 32'd1 *) (* src = "RTL/axi_master_fsm.v:0.0-0.0|RTL/axi_master_fsm.v:53.9-143.16" *) 1'h1 : 1'h0;
endmodule
