/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/axi_write_data.v:1.1-55.10" *)
module axi_write_data(clk, rst, start, data, wready, wdata, wvalid, done);
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  wire _00_;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_write_data.v:46.12-46.28" *)
  wire _03_;
  wire _04_;
  (* src = "RTL/axi_write_data.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_write_data.v:12.29-12.33" *)
  input [31:0] data;
  wire [31:0] data;
  (* src = "RTL/axi_write_data.v:17.12-17.16" *)
  output done;
  reg done;
  (* src = "RTL/axi_write_data.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_write_data.v:11.12-11.17" *)
  input start;
  wire start;
  (* src = "RTL/axi_write_data.v:15.29-15.34" *)
  output [31:0] wdata;
  reg [31:0] wdata;
  (* src = "RTL/axi_write_data.v:13.12-13.18" *)
  input wready;
  wire wready;
  (* src = "RTL/axi_write_data.v:16.12-16.18" *)
  output wvalid;
  reg wvalid;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wdata <= 32'd0;
    else if (start) wdata <= data;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) wvalid <= 1'h0;
    else if (_02_) wvalid <= _01_;
  assign _02_ = | { _03_, start };
  assign _03_ = wvalid && (* src = "RTL/axi_write_data.v:46.12-46.28" *) wready;
  (* src = "RTL/axi_write_data.v:21.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _00_;
  assign _00_ = _03_ ? (* src = "RTL/axi_write_data.v:46.12-46.28|RTL/axi_write_data.v:46.9-52.12" *) 1'h1 : 1'h0;
  assign _04_ = start ? (* src = "RTL/axi_write_data.v:38.12-38.17|RTL/axi_write_data.v:38.9-44.12" *) 1'h1 : 1'hx;
  assign _01_ = _03_ ? (* src = "RTL/axi_write_data.v:46.12-46.28|RTL/axi_write_data.v:46.9-52.12" *) 1'h0 : _04_;
endmodule
