/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/axi_read_data.v:1.1-54.10" *)
module axi_read_data(clk, rst, rdata, rvalid, rready, data_out, done);
  (* src = "RTL/axi_read_data.v:20.1-53.4" *)
  wire _0_;
  (* src = "RTL/axi_read_data.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_read_data.v:15.29-15.37" *)
  output [31:0] data_out;
  reg [31:0] data_out;
  (* src = "RTL/axi_read_data.v:16.12-16.16" *)
  output done;
  wire done;
  (* src = "RTL/axi_read_data.v:11.29-11.34" *)
  input [31:0] rdata;
  wire [31:0] rdata;
  (* src = "RTL/axi_read_data.v:14.12-14.18" *)
  output rready;
  reg rready;
  (* src = "RTL/axi_read_data.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_read_data.v:12.12-12.18" *)
  input rvalid;
  wire rvalid;
  (* src = "RTL/axi_read_data.v:20.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) data_out <= 32'd0;
    else if (rvalid) data_out <= rdata;
  (* src = "RTL/axi_read_data.v:20.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rready <= 1'h0;
    else rready <= _0_;
  assign _0_ = rvalid ? (* full_case = 32'd1 *) (* src = "RTL/axi_read_data.v:37.12-37.18|RTL/axi_read_data.v:37.9-51.12" *) 1'h1 : 1'h0;
  assign done = rready;
endmodule
