/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/alu_control.v:1.1-45.10" *)
module alu_control(opcode, alu_control);
  (* src = "RTL/alu_control.v:5.23-5.34" *)
  output [3:0] alu_control;
  wire [3:0] alu_control;
  (* src = "RTL/alu_control.v:3.23-3.29" *)
  input [2:0] opcode;
  wire [2:0] opcode;
  (* full_case = 32'd1 *)
  (* src = "RTL/alu_control.v:12.5-41.12" *)
  reg [3:0] \$auto$proc_rom.cc:150:do_switch$3  [7:0];
  initial begin
    \$auto$proc_rom.cc:150:do_switch$3 [0] = 4'h0;
    \$auto$proc_rom.cc:150:do_switch$3 [1] = 4'h1;
    \$auto$proc_rom.cc:150:do_switch$3 [2] = 4'h2;
    \$auto$proc_rom.cc:150:do_switch$3 [3] = 4'h3;
    \$auto$proc_rom.cc:150:do_switch$3 [4] = 4'h4;
    \$auto$proc_rom.cc:150:do_switch$3 [5] = 4'h5;
    \$auto$proc_rom.cc:150:do_switch$3 [6] = 4'h6;
    \$auto$proc_rom.cc:150:do_switch$3 [7] = 4'h7;
  end
  assign alu_control = \$auto$proc_rom.cc:150:do_switch$3 [opcode];
endmodule
