/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/alu_pipeline_register.v:1.1-53.10" *)
module alu_pipeline_register(clk, rst, result_in, zero_in, carry_in, negative_in, overflow_in, result_out, zero_out, carry_out, negative_out, overflow_out);
  (* src = "RTL/alu_pipeline_register.v:12.16-12.24" *)
  input carry_in;
  wire carry_in;
  (* src = "RTL/alu_pipeline_register.v:18.16-18.25" *)
  output carry_out;
  reg carry_out;
  (* src = "RTL/alu_pipeline_register.v:7.16-7.19" *)
  input clk;
  wire clk;
  (* src = "RTL/alu_pipeline_register.v:13.16-13.27" *)
  input negative_in;
  wire negative_in;
  (* src = "RTL/alu_pipeline_register.v:19.16-19.28" *)
  output negative_out;
  reg negative_out;
  (* src = "RTL/alu_pipeline_register.v:14.16-14.27" *)
  input overflow_in;
  wire overflow_in;
  (* src = "RTL/alu_pipeline_register.v:20.16-20.28" *)
  output overflow_out;
  reg overflow_out;
  (* src = "RTL/alu_pipeline_register.v:10.33-10.42" *)
  input [31:0] result_in;
  wire [31:0] result_in;
  (* src = "RTL/alu_pipeline_register.v:16.33-16.43" *)
  output [31:0] result_out;
  reg [31:0] result_out;
  (* src = "RTL/alu_pipeline_register.v:8.16-8.19" *)
  input rst;
  wire rst;
  (* src = "RTL/alu_pipeline_register.v:11.16-11.23" *)
  input zero_in;
  wire zero_in;
  (* src = "RTL/alu_pipeline_register.v:17.16-17.24" *)
  output zero_out;
  reg zero_out;
  (* src = "RTL/alu_pipeline_register.v:24.1-51.4" *)
  always @(posedge clk)
    if (rst) result_out <= 32'd0;
    else result_out <= result_in;
  (* src = "RTL/alu_pipeline_register.v:24.1-51.4" *)
  always @(posedge clk)
    if (rst) zero_out <= 1'h0;
    else zero_out <= zero_in;
  (* src = "RTL/alu_pipeline_register.v:24.1-51.4" *)
  always @(posedge clk)
    if (rst) carry_out <= 1'h0;
    else carry_out <= carry_in;
  (* src = "RTL/alu_pipeline_register.v:24.1-51.4" *)
  always @(posedge clk)
    if (rst) negative_out <= 1'h0;
    else negative_out <= negative_in;
  (* src = "RTL/alu_pipeline_register.v:24.1-51.4" *)
  always @(posedge clk)
    if (rst) overflow_out <= 1'h0;
    else overflow_out <= overflow_in;
endmodule
