/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/alu_execute.v:1.1-66.10" *)
module alu_execute(operand_a, operand_b, alu_control, result);
  (* src = "RTL/alu_execute.v:23.22-23.43" *)
  wire [31:0] _00_;
  (* src = "RTL/alu_execute.v:33.22-33.43" *)
  wire [31:0] _01_;
  (* src = "RTL/alu_execute.v:58.23-58.45" *)
  wire [31:0] _02_;
  (* src = "RTL/alu_execute.v:38.22-38.43" *)
  wire [31:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "RTL/alu_execute.v:28.22-28.43" *)
  wire [31:0] _12_;
  (* src = "RTL/alu_execute.v:43.22-43.43" *)
  wire [31:0] _13_;
  (* src = "RTL/alu_execute.v:9.22-9.33" *)
  input [3:0] alu_control;
  wire [3:0] alu_control;
  (* src = "RTL/alu_execute.v:7.33-7.42" *)
  input [31:0] operand_a;
  wire [31:0] operand_a;
  (* src = "RTL/alu_execute.v:8.33-8.42" *)
  input [31:0] operand_b;
  wire [31:0] operand_b;
  (* src = "RTL/alu_execute.v:11.33-11.39" *)
  output [31:0] result;
  wire [31:0] result;
  assign _00_ = operand_a + (* src = "RTL/alu_execute.v:23.22-23.43" *) operand_b;
  assign _01_ = operand_a & (* src = "RTL/alu_execute.v:33.22-33.43" *) operand_b;
  assign _02_ = operand_a == (* src = "RTL/alu_execute.v:58.23-58.45" *) operand_b;
  assign _03_ = operand_a | (* src = "RTL/alu_execute.v:38.22-38.43" *) operand_b;
  function [31:0] _18_;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _18_ = b[31:0];
      8'b??????1?:
        _18_ = b[63:32];
      8'b?????1??:
        _18_ = b[95:64];
      8'b????1???:
        _18_ = b[127:96];
      8'b???1????:
        _18_ = b[159:128];
      8'b??1?????:
        _18_ = b[191:160];
      8'b?1??????:
        _18_ = b[223:192];
      8'b1???????:
        _18_ = b[255:224];
      default:
        _18_ = a;
    endcase
  endfunction
  assign result = _18_(32'd0, { _00_, _12_, _01_, _03_, _13_, operand_a[30:0], 2'h0, operand_a[31:1], _02_ }, { _11_, _10_, _09_, _08_, _07_, _06_, _05_, _04_ });
  assign _04_ = alu_control == (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) 4'h7;
  assign _05_ = alu_control == (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) 4'h6;
  assign _06_ = alu_control == (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) 4'h5;
  assign _07_ = alu_control == (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) 4'h4;
  assign _08_ = alu_control == (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) 4'h3;
  assign _09_ = alu_control == (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) 4'h2;
  assign _10_ = alu_control == (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) 4'h1;
  assign _11_ = ! (* full_case = 32'd1 *) (* src = "RTL/alu_execute.v:0.0-0.0|RTL/alu_execute.v:18.5-63.12" *) alu_control;
  assign _12_ = operand_a - (* src = "RTL/alu_execute.v:28.22-28.43" *) operand_b;
  assign _13_ = operand_a ^ (* src = "RTL/alu_execute.v:43.22-43.43" *) operand_b;
endmodule
