/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/sdram_write_controller.v:1.1-98.10" *)
module sdram_write_controller(clk, rst, write_request, delay_done, start_delay, activate, write_cmd, write_done);
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _00_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _01_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire [2:0] _02_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _03_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [2:0] _12_;
  wire _13_;
  wire [2:0] _14_;
  wire _15_;
  (* src = "RTL/sdram_write_controller.v:9.12-9.20" *)
  output activate;
  reg activate;
  (* src = "RTL/sdram_write_controller.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_write_controller.v:6.12-6.22" *)
  input delay_done;
  wire delay_done;
  (* src = "RTL/sdram_write_controller.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_write_controller.v:8.12-8.23" *)
  output start_delay;
  reg start_delay;
  (* src = "RTL/sdram_write_controller.v:21.11-21.16" *)
  reg [2:0] state;
  (* src = "RTL/sdram_write_controller.v:10.12-10.21" *)
  output write_cmd;
  reg write_cmd;
  (* src = "RTL/sdram_write_controller.v:11.12-11.22" *)
  output write_done;
  reg write_done;
  (* src = "RTL/sdram_write_controller.v:5.12-5.25" *)
  input write_request;
  wire write_request;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_07_) state <= _02_;
  assign _05_ = { _15_, write_request } != 2'h2;
  assign _06_ = { _13_, delay_done } != 2'h2;
  assign _07_ = & { _06_, _05_ };
  assign _08_ = | { _13_, _11_ };
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_delay <= 1'h0;
    else start_delay <= _01_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) activate <= 1'h0;
    else activate <= _00_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) write_cmd <= 1'h0;
    else write_cmd <= _03_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) write_done <= 1'h0;
    else write_done <= _04_;
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h4;
  assign _03_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
  assign _00_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
  function [2:0] _28_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _28_ = b[2:0];
      4'b??1?:
        _28_ = b[5:3];
      4'b?1??:
        _28_ = b[8:6];
      4'b1???:
        _28_ = b[11:9];
      default:
        _28_ = a;
    endcase
  endfunction
  assign _02_ = _28_(3'h0, { _14_, 3'h2, _12_, 3'h4 }, { _15_, _11_, _13_, _10_ });
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h3;
  assign _12_ = delay_done ? (* src = "RTL/sdram_write_controller.v:71.16-71.26|RTL/sdram_write_controller.v:71.13-72.32" *) 3'h3 : 3'hx;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h2;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h1;
  assign _14_ = write_request ? (* src = "RTL/sdram_write_controller.v:53.16-53.29|RTL/sdram_write_controller.v:53.13-54.35" *) 3'h1 : 3'hx;
  assign _15_ = ! (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) state;
  assign _01_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
  assign _04_ = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
endmodule
