/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\sdram_timing_generator" *)
(* src = "RTL/sdram_timing_generator.v:1.1-60.10" *)
module \$paramod\sdram_timing_generator\WAIT_CYCLES=s32'00000000000000000000000000001000 (clk, rst, start, done);
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  wire [3:0] _00_;
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  wire _01_;
  (* src = "RTL/sdram_timing_generator.v:47.28-47.39" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _02_;
  (* src = "RTL/sdram_timing_generator.v:36.16-36.40" *)
  wire _03_;
  wire _04_;
  wire [3:0] _05_;
  (* src = "RTL/sdram_timing_generator.v:8.12-8.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_timing_generator.v:15.29-15.36" *)
  reg [3:0] counter;
  (* src = "RTL/sdram_timing_generator.v:12.12-12.16" *)
  output done;
  reg done;
  (* src = "RTL/sdram_timing_generator.v:9.12-9.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_timing_generator.v:10.12-10.17" *)
  input start;
  wire start;
  assign _02_ = counter + (* src = "RTL/sdram_timing_generator.v:47.28-47.39" *) 32'd1;
  assign _03_ = counter == (* src = "RTL/sdram_timing_generator.v:36.16-36.40" *) 4'h7;
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 4'h0;
    else counter <= _00_;
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _04_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:36.16-36.40|RTL/sdram_timing_generator.v:36.13-49.16" *) 1'h1 : 1'h0;
  assign _01_ = start ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:32.12-32.17|RTL/sdram_timing_generator.v:32.9-57.12" *) _04_ : 1'h0;
  assign _05_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:36.16-36.40|RTL/sdram_timing_generator.v:36.13-49.16" *) 4'h0 : _02_[3:0];
  assign _00_ = start ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:32.12-32.17|RTL/sdram_timing_generator.v:32.9-57.12" *) _05_ : 4'h0;
endmodule

(* src = "RTL/sdram_command_generator.v:1.1-88.10" *)
module sdram_command_generator(precharge, refresh, load_mode, read_cmd, write_cmd, activate, cs_n, ras_n, cas_n, we_n);
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _00_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _01_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _02_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _03_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _04_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _05_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _06_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _07_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _08_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _09_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _10_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _11_;
  (* src = "RTL/sdram_command_generator.v:8.12-8.20" *)
  input activate;
  wire activate;
  (* src = "RTL/sdram_command_generator.v:12.12-12.17" *)
  output cas_n;
  wire cas_n;
  (* src = "RTL/sdram_command_generator.v:10.12-10.16" *)
  output cs_n;
  wire cs_n;
  (* src = "RTL/sdram_command_generator.v:5.12-5.21" *)
  input load_mode;
  wire load_mode;
  (* src = "RTL/sdram_command_generator.v:3.12-3.21" *)
  input precharge;
  wire precharge;
  (* src = "RTL/sdram_command_generator.v:11.12-11.17" *)
  output ras_n;
  wire ras_n;
  (* src = "RTL/sdram_command_generator.v:6.12-6.20" *)
  input read_cmd;
  wire read_cmd;
  (* src = "RTL/sdram_command_generator.v:4.12-4.19" *)
  input refresh;
  wire refresh;
  (* src = "RTL/sdram_command_generator.v:13.12-13.16" *)
  output we_n;
  wire we_n;
  (* src = "RTL/sdram_command_generator.v:7.12-7.21" *)
  input write_cmd;
  wire write_cmd;
  assign _11_ = load_mode ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:77.13-77.22|RTL/sdram_command_generator.v:77.10-85.8" *) 1'h0 : 1'h1;
  assign _10_ = refresh ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:67.13-67.20|RTL/sdram_command_generator.v:67.10-85.8" *) 1'h1 : _11_;
  assign _09_ = refresh ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:67.13-67.20|RTL/sdram_command_generator.v:67.10-85.8" *) 1'h0 : _11_;
  assign _08_ = precharge ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:57.13-57.22|RTL/sdram_command_generator.v:57.10-85.8" *) 1'h0 : _10_;
  assign _06_ = precharge ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:57.13-57.22|RTL/sdram_command_generator.v:57.10-85.8" *) 1'h1 : _09_;
  assign _07_ = precharge ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:57.13-57.22|RTL/sdram_command_generator.v:57.10-85.8" *) 1'h0 : _09_;
  assign _05_ = write_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:47.13-47.22|RTL/sdram_command_generator.v:47.10-85.8" *) 1'h0 : _08_;
  assign _03_ = write_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:47.13-47.22|RTL/sdram_command_generator.v:47.10-85.8" *) 1'h0 : _06_;
  assign _04_ = write_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:47.13-47.22|RTL/sdram_command_generator.v:47.10-85.8" *) 1'h1 : _07_;
  assign _02_ = read_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:36.13-36.21|RTL/sdram_command_generator.v:36.10-85.8" *) 1'h1 : _05_;
  assign _00_ = read_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:36.13-36.21|RTL/sdram_command_generator.v:36.10-85.8" *) 1'h0 : _03_;
  assign _01_ = read_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:36.13-36.21|RTL/sdram_command_generator.v:36.10-85.8" *) 1'h1 : _04_;
  assign we_n = activate ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:26.8-26.16|RTL/sdram_command_generator.v:26.5-85.8" *) 1'h1 : _02_;
  assign cas_n = activate ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:26.8-26.16|RTL/sdram_command_generator.v:26.5-85.8" *) 1'h1 : _00_;
  assign ras_n = activate ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:26.8-26.16|RTL/sdram_command_generator.v:26.5-85.8" *) 1'h0 : _01_;
  assign cs_n = 1'h0;
endmodule

(* src = "RTL/sdram_init_fsm.v:1.1-108.10" *)
module sdram_init_fsm(clk, rst, delay_done, start_delay, precharge, refresh, load_mode, init_done);
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _00_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _01_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _02_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _03_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire [2:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [2:0] _15_;
  (* src = "RTL/sdram_init_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_init_fsm.v:5.12-5.22" *)
  input delay_done;
  wire delay_done;
  (* src = "RTL/sdram_init_fsm.v:11.12-11.21" *)
  output init_done;
  reg init_done;
  (* src = "RTL/sdram_init_fsm.v:10.12-10.21" *)
  output load_mode;
  reg load_mode;
  (* src = "RTL/sdram_init_fsm.v:8.12-8.21" *)
  output precharge;
  reg precharge;
  (* src = "RTL/sdram_init_fsm.v:9.12-9.19" *)
  output refresh;
  reg refresh;
  (* src = "RTL/sdram_init_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_init_fsm.v:7.12-7.23" *)
  output start_delay;
  reg start_delay;
  (* src = "RTL/sdram_init_fsm.v:21.11-21.16" *)
  reg [2:0] state;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) init_done <= 1'h0;
    else if (_14_) init_done <= 1'h1;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_07_) state <= _04_;
  assign _05_ = { _12_, delay_done } != 2'h2;
  assign _06_ = ~ _14_;
  assign _07_ = & { _06_, _05_ };
  assign _08_ = | { _13_, _12_ };
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) precharge <= 1'h0;
    else precharge <= _01_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) refresh <= 1'h0;
    else refresh <= _02_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load_mode <= 1'h0;
    else load_mode <= _00_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_delay <= 1'h0;
    else start_delay <= _03_;
  assign _00_ = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
  assign _02_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
  assign _01_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
  assign _03_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
  function [2:0] _30_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _30_ = b[2:0];
      6'b????1?:
        _30_ = b[5:3];
      6'b???1??:
        _30_ = b[8:6];
      6'b??1???:
        _30_ = b[11:9];
      6'b?1????:
        _30_ = b[14:12];
      6'b1?????:
        _30_ = b[17:15];
      default:
        _30_ = a;
    endcase
  endfunction
  assign _04_ = _30_(3'h0, { 3'h1, _15_, 12'b011100101xxx }, { _13_, _12_, _11_, _10_, _09_, _14_ });
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h4;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h3;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h2;
  assign _15_ = delay_done ? (* src = "RTL/sdram_init_fsm.v:63.16-63.26|RTL/sdram_init_fsm.v:63.13-64.36" *) 3'h2 : 3'hx;
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h1;
  assign _13_ = ! (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) state;
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h5;
endmodule

(* src = "RTL/sdram_main_fsm.v:1.1-116.10" *)
module sdram_main_fsm(clk, rst, init_done, refresh_request, read_request, write_request, read_done, write_done, start_init, start_refresh, start_read, start_write);
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  wire _00_;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  wire _01_;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  wire _02_;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  wire _03_;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  wire [2:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [2:0] _14_;
  wire _15_;
  wire [2:0] _16_;
  wire _17_;
  wire [2:0] _18_;
  wire [2:0] _19_;
  wire [2:0] _20_;
  wire _21_;
  wire [2:0] _22_;
  (* src = "RTL/sdram_main_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_main_fsm.v:5.12-5.21" *)
  input init_done;
  wire init_done;
  (* src = "RTL/sdram_main_fsm.v:9.12-9.21" *)
  input read_done;
  wire read_done;
  (* src = "RTL/sdram_main_fsm.v:7.12-7.24" *)
  input read_request;
  wire read_request;
  (* src = "RTL/sdram_main_fsm.v:6.12-6.27" *)
  input refresh_request;
  wire refresh_request;
  (* src = "RTL/sdram_main_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_main_fsm.v:12.12-12.22" *)
  output start_init;
  reg start_init;
  (* src = "RTL/sdram_main_fsm.v:14.12-14.22" *)
  output start_read;
  reg start_read;
  (* src = "RTL/sdram_main_fsm.v:13.12-13.25" *)
  output start_refresh;
  reg start_refresh;
  (* src = "RTL/sdram_main_fsm.v:15.12-15.23" *)
  output start_write;
  reg start_write;
  (* src = "RTL/sdram_main_fsm.v:26.11-26.16" *)
  reg [2:0] state;
  (* src = "RTL/sdram_main_fsm.v:10.12-10.22" *)
  input write_done;
  wire write_done;
  (* src = "RTL/sdram_main_fsm.v:8.12-8.25" *)
  input write_request;
  wire write_request;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_09_) state <= _04_;
  assign _05_ = { _12_, init_done } != 2'h2;
  assign _06_ = { _21_, write_request, read_request, refresh_request } != 4'h8;
  assign _07_ = { _17_, read_done } != 2'h2;
  assign _08_ = { _15_, write_done } != 2'h2;
  assign _09_ = & { _08_, _07_, _06_, _05_ };
  assign _10_ = | { _13_, _12_ };
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_init <= 1'h0;
    else start_init <= _00_;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_refresh <= 1'h0;
    else start_refresh <= _02_;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_read <= 1'h0;
    else start_read <= _01_;
  (* src = "RTL/sdram_main_fsm.v:28.1-115.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_write <= 1'h0;
    else start_write <= _03_;
  assign _02_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 1'h1 : 1'h0;
  assign _00_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 1'h1 : 1'h0;
  assign _14_ = write_done ? (* src = "RTL/sdram_main_fsm.v:104.16-104.26|RTL/sdram_main_fsm.v:104.13-105.31" *) 3'h2 : 3'hx;
  function [2:0] _37_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _37_ = b[2:0];
      6'b????1?:
        _37_ = b[5:3];
      6'b???1??:
        _37_ = b[8:6];
      6'b??1???:
        _37_ = b[11:9];
      6'b?1????:
        _37_ = b[14:12];
      6'b1?????:
        _37_ = b[17:15];
      default:
        _37_ = a;
    endcase
  endfunction
  assign _04_ = _37_(3'h0, { 3'h1, _22_, _20_, 3'h2, _16_, _14_ }, { _13_, _12_, _21_, _11_, _17_, _15_ });
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 3'h5;
  assign _16_ = read_done ? (* src = "RTL/sdram_main_fsm.v:95.16-95.25|RTL/sdram_main_fsm.v:95.13-96.31" *) 3'h2 : 3'hx;
  assign _17_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 3'h4;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 3'h3;
  assign _18_ = write_request ? (* src = "RTL/sdram_main_fsm.v:78.21-78.34|RTL/sdram_main_fsm.v:78.18-79.32" *) 3'h5 : 3'hx;
  assign _19_ = read_request ? (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:76.21-76.33|RTL/sdram_main_fsm.v:76.18-79.32" *) 3'h4 : _18_;
  assign _20_ = refresh_request ? (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:74.16-74.31|RTL/sdram_main_fsm.v:74.13-79.32" *) 3'h3 : _19_;
  assign _21_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 3'h2;
  assign _22_ = init_done ? (* src = "RTL/sdram_main_fsm.v:66.16-66.25|RTL/sdram_main_fsm.v:66.13-67.31" *) 3'h2 : 3'hx;
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 3'h1;
  assign _13_ = ! (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) state;
  assign _03_ = _15_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 1'h1 : 1'h0;
  assign _01_ = _17_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_main_fsm.v:0.0-0.0|RTL/sdram_main_fsm.v:52.9-112.16" *) 1'h1 : 1'h0;
endmodule

(* src = "RTL/sdram_read_controller.v:1.1-97.10" *)
module sdram_read_controller(clk, rst, read_request, delay_done, start_delay, activate, read_cmd, read_done);
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _00_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _01_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _02_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _03_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire [2:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [2:0] _13_;
  wire [2:0] _14_;
  wire _15_;
  (* src = "RTL/sdram_read_controller.v:9.12-9.20" *)
  output activate;
  reg activate;
  (* src = "RTL/sdram_read_controller.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_read_controller.v:6.12-6.22" *)
  input delay_done;
  wire delay_done;
  (* src = "RTL/sdram_read_controller.v:10.12-10.20" *)
  output read_cmd;
  reg read_cmd;
  (* src = "RTL/sdram_read_controller.v:11.12-11.21" *)
  output read_done;
  reg read_done;
  (* src = "RTL/sdram_read_controller.v:5.12-5.24" *)
  input read_request;
  wire read_request;
  (* src = "RTL/sdram_read_controller.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_read_controller.v:8.12-8.23" *)
  output start_delay;
  reg start_delay;
  (* src = "RTL/sdram_read_controller.v:20.11-20.16" *)
  reg [2:0] state;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_07_) state <= _04_;
  assign _05_ = { _09_, delay_done } != 2'h2;
  assign _06_ = { _15_, read_request } != 2'h2;
  assign _07_ = & { _06_, _05_ };
  assign _08_ = | { _10_, _09_ };
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) read_cmd <= 1'h0;
    else read_cmd <= _01_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) activate <= 1'h0;
    else activate <= _00_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_delay <= 1'h0;
    else start_delay <= _03_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) read_done <= 1'h0;
    else read_done <= _02_;
  assign _03_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
  assign _02_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h4;
  assign _01_ = _12_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
  assign _00_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
  function [2:0] _30_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _30_ = b[2:0];
      4'b??1?:
        _30_ = b[5:3];
      4'b?1??:
        _30_ = b[8:6];
      4'b1???:
        _30_ = b[11:9];
      default:
        _30_ = a;
    endcase
  endfunction
  assign _04_ = _30_(3'h0, { _14_, 3'h2, _13_, 3'h4 }, { _15_, _10_, _09_, _12_ });
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h3;
  assign _13_ = delay_done ? (* src = "RTL/sdram_read_controller.v:68.16-68.26|RTL/sdram_read_controller.v:68.13-69.31" *) 3'h3 : 3'hx;
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h2;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h1;
  assign _14_ = read_request ? (* src = "RTL/sdram_read_controller.v:50.16-50.28|RTL/sdram_read_controller.v:50.13-51.35" *) 3'h1 : 3'hx;
  assign _15_ = ! (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) state;
endmodule

(* dynports =  1  *)
(* src = "RTL/sdram_refresh_controller.v:1.1-50.10" *)
module sdram_refresh_controller(clk, rst, refresh_request);
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  wire [4:0] _0_;
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  wire _1_;
  (* src = "RTL/sdram_refresh_controller.v:45.24-45.35" *)
  (* unused_bits = "5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _2_;
  (* src = "RTL/sdram_refresh_controller.v:33.12-33.39" *)
  wire _3_;
  (* src = "RTL/sdram_refresh_controller.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_refresh_controller.v:15.32-15.39" *)
  reg [4:0] counter;
  (* src = "RTL/sdram_refresh_controller.v:12.12-12.27" *)
  output refresh_request;
  reg refresh_request;
  (* src = "RTL/sdram_refresh_controller.v:10.12-10.15" *)
  input rst;
  wire rst;
  assign _2_ = counter + (* src = "RTL/sdram_refresh_controller.v:45.24-45.35" *) 32'd1;
  assign _3_ = counter == (* src = "RTL/sdram_refresh_controller.v:33.12-33.39" *) 5'h0f;
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) refresh_request <= 1'h0;
    else refresh_request <= _1_;
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 5'h00;
    else counter <= _0_;
  assign _1_ = _3_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_refresh_controller.v:33.12-33.39|RTL/sdram_refresh_controller.v:33.9-47.12" *) 1'h1 : 1'h0;
  assign _0_ = _3_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_refresh_controller.v:33.12-33.39|RTL/sdram_refresh_controller.v:33.9-47.12" *) 5'h00 : _2_[4:0];
endmodule

(* top =  1  *)
(* src = "RTL/sdram_top.v:1.1-139.10" *)
module sdram_top(clk, rst, read_request, write_request, cs_n, ras_n, cas_n, we_n);
  (* src = "RTL/sdram_top.v:27.6-27.14" *)
  wire activate;
  (* src = "RTL/sdram_top.v:16.13-16.18" *)
  output cas_n;
  wire cas_n;
  (* src = "RTL/sdram_top.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_top.v:14.13-14.17" *)
  output cs_n;
  wire cs_n;
  (* src = "RTL/sdram_top.v:21.6-21.16" *)
  wire delay_done;
  (* src = "RTL/sdram_top.v:23.6-23.15" *)
  wire init_done;
  (* src = "RTL/sdram_top.v:15.13-15.18" *)
  output ras_n;
  wire ras_n;
  (* src = "RTL/sdram_top.v:28.6-28.14" *)
  wire read_cmd;
  (* src = "RTL/sdram_top.v:30.6-30.15" *)
  wire read_done;
  (* src = "RTL/sdram_top.v:11.12-11.24" *)
  input read_request;
  wire read_request;
  (* src = "RTL/sdram_top.v:25.6-25.21" *)
  wire refresh_request;
  (* src = "RTL/sdram_top.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_top.v:22.6-22.17" *)
  wire start_delay;
  (* src = "RTL/sdram_top.v:32.6-32.16" *)
  wire start_read;
  (* src = "RTL/sdram_top.v:26.6-26.19" *)
  wire start_refresh;
  (* src = "RTL/sdram_top.v:33.6-33.17" *)
  wire start_write;
  (* src = "RTL/sdram_top.v:17.13-17.17" *)
  output we_n;
  wire we_n;
  (* src = "RTL/sdram_top.v:29.6-29.15" *)
  wire write_cmd;
  (* src = "RTL/sdram_top.v:31.6-31.16" *)
  wire write_done;
  (* src = "RTL/sdram_top.v:12.12-12.25" *)
  input write_request;
  wire write_request;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/sdram_top.v:124.25-138.2" *)
  sdram_command_generator command_generator (
    .activate(activate),
    .cas_n(cas_n),
    .cs_n(cs_n),
    .load_mode(1'h0),
    .precharge(1'h0),
    .ras_n(ras_n),
    .read_cmd(read_cmd),
    .refresh(start_refresh),
    .we_n(we_n),
    .write_cmd(write_cmd)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/sdram_top.v:53.16-64.2" *)
  sdram_init_fsm init_fsm (
    .clk(clk),
    .delay_done(delay_done),
    .init_done(init_done),
    .rst(rst),
    .start_delay(start_delay)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/sdram_top.v:106.16-121.2" *)
  sdram_main_fsm main_fsm (
    .clk(clk),
    .init_done(init_done),
    .read_done(read_done),
    .read_request(read_request),
    .refresh_request(refresh_request),
    .rst(rst),
    .start_read(start_read),
    .start_write(start_write),
    .write_done(write_done),
    .write_request(write_request)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/sdram_top.v:77.23-89.2" *)
  sdram_read_controller read_controller (
    .activate(activate),
    .clk(clk),
    .delay_done(delay_done),
    .read_cmd(read_cmd),
    .read_done(read_done),
    .read_request(start_read),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/sdram_top.v:67.26-74.2" *)
  sdram_refresh_controller refresh_controller (
    .clk(clk),
    .refresh_request(refresh_request),
    .rst(rst)
  );
  (* src = "RTL/sdram_top.v:42.1-50.2" *)
  \$paramod\sdram_timing_generator\WAIT_CYCLES=s32'00000000000000000000000000001000  timing_generator (
    .clk(clk),
    .done(delay_done),
    .rst(rst),
    .start(start_delay)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/sdram_top.v:92.24-103.2" *)
  sdram_write_controller write_controller (
    .clk(clk),
    .delay_done(delay_done),
    .rst(rst),
    .write_cmd(write_cmd),
    .write_done(write_done),
    .write_request(start_write)
  );
endmodule

(* src = "RTL/sdram_write_controller.v:1.1-98.10" *)
module sdram_write_controller(clk, rst, write_request, delay_done, start_delay, activate, write_cmd, write_done);
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _00_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _01_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire [2:0] _02_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _03_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [2:0] _13_;
  wire [2:0] _14_;
  wire _15_;
  (* src = "RTL/sdram_write_controller.v:9.12-9.20" *)
  output activate;
  reg activate;
  (* src = "RTL/sdram_write_controller.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_write_controller.v:6.12-6.22" *)
  input delay_done;
  wire delay_done;
  (* src = "RTL/sdram_write_controller.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_write_controller.v:8.12-8.23" *)
  output start_delay;
  reg start_delay;
  (* src = "RTL/sdram_write_controller.v:21.11-21.16" *)
  reg [2:0] state;
  (* src = "RTL/sdram_write_controller.v:10.12-10.21" *)
  output write_cmd;
  reg write_cmd;
  (* src = "RTL/sdram_write_controller.v:11.12-11.22" *)
  output write_done;
  reg write_done;
  (* src = "RTL/sdram_write_controller.v:5.12-5.25" *)
  input write_request;
  wire write_request;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_07_) state <= _02_;
  assign _05_ = { _09_, delay_done } != 2'h2;
  assign _06_ = { _15_, write_request } != 2'h2;
  assign _07_ = & { _06_, _05_ };
  assign _08_ = | { _09_, _10_ };
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) write_cmd <= 1'h0;
    else write_cmd <= _03_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) activate <= 1'h0;
    else activate <= _00_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_delay <= 1'h0;
    else start_delay <= _01_;
  (* src = "RTL/sdram_write_controller.v:23.1-97.4" *)
  always @(posedge clk, posedge rst)
    if (rst) write_done <= 1'h0;
    else write_done <= _04_;
  assign _01_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
  assign _04_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h4;
  assign _03_ = _12_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
  assign _00_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 1'h1 : 1'h0;
  function [2:0] _30_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _30_ = b[2:0];
      4'b??1?:
        _30_ = b[5:3];
      4'b?1??:
        _30_ = b[8:6];
      4'b1???:
        _30_ = b[11:9];
      default:
        _30_ = a;
    endcase
  endfunction
  assign _02_ = _30_(3'h0, { _14_, 3'h2, _13_, 3'h4 }, { _15_, _10_, _09_, _12_ });
  assign _12_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h3;
  assign _13_ = delay_done ? (* src = "RTL/sdram_write_controller.v:71.16-71.26|RTL/sdram_write_controller.v:71.13-72.32" *) 3'h3 : 3'hx;
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h2;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) 3'h1;
  assign _14_ = write_request ? (* src = "RTL/sdram_write_controller.v:53.16-53.29|RTL/sdram_write_controller.v:53.13-54.35" *) 3'h1 : 3'hx;
  assign _15_ = ! (* full_case = 32'd1 *) (* src = "RTL/sdram_write_controller.v:0.0-0.0|RTL/sdram_write_controller.v:47.9-94.16" *) state;
endmodule
