/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/sdram_timing_generator.v:1.1-60.10" *)
module sdram_timing_generator(clk, rst, start, done);
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  wire [3:0] _00_;
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  wire _01_;
  (* src = "RTL/sdram_timing_generator.v:47.28-47.39" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _02_;
  (* src = "RTL/sdram_timing_generator.v:36.16-36.40" *)
  wire _03_;
  wire [3:0] _04_;
  wire _05_;
  (* src = "RTL/sdram_timing_generator.v:8.12-8.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_timing_generator.v:15.29-15.36" *)
  reg [3:0] counter;
  (* src = "RTL/sdram_timing_generator.v:12.12-12.16" *)
  output done;
  reg done;
  (* src = "RTL/sdram_timing_generator.v:9.12-9.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_timing_generator.v:10.12-10.17" *)
  input start;
  wire start;
  assign _02_ = counter + (* src = "RTL/sdram_timing_generator.v:47.28-47.39" *) 32'd1;
  assign _03_ = counter == (* src = "RTL/sdram_timing_generator.v:36.16-36.40" *) 4'h7;
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  (* src = "RTL/sdram_timing_generator.v:17.1-59.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 4'h0;
    else counter <= _00_;
  assign _04_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:36.16-36.40|RTL/sdram_timing_generator.v:36.13-49.16" *) 4'h0 : _02_[3:0];
  assign _00_ = start ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:32.12-32.17|RTL/sdram_timing_generator.v:32.9-57.12" *) _04_ : 4'h0;
  assign _05_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:36.16-36.40|RTL/sdram_timing_generator.v:36.13-49.16" *) 1'h1 : 1'h0;
  assign _01_ = start ? (* full_case = 32'd1 *) (* src = "RTL/sdram_timing_generator.v:32.12-32.17|RTL/sdram_timing_generator.v:32.9-57.12" *) _05_ : 1'h0;
endmodule
