/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/sdram_command_generator.v:1.1-88.10" *)
module sdram_command_generator(precharge, refresh, load_mode, read_cmd, write_cmd, activate, cs_n, ras_n, cas_n, we_n);
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _00_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _01_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _02_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _03_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _04_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _05_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _06_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _07_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _08_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _09_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _10_;
  (* src = "RTL/sdram_command_generator.v:16.1-87.4" *)
  wire _11_;
  (* src = "RTL/sdram_command_generator.v:8.12-8.20" *)
  input activate;
  wire activate;
  (* src = "RTL/sdram_command_generator.v:12.12-12.17" *)
  output cas_n;
  wire cas_n;
  (* src = "RTL/sdram_command_generator.v:10.12-10.16" *)
  output cs_n;
  wire cs_n;
  (* src = "RTL/sdram_command_generator.v:5.12-5.21" *)
  input load_mode;
  wire load_mode;
  (* src = "RTL/sdram_command_generator.v:3.12-3.21" *)
  input precharge;
  wire precharge;
  (* src = "RTL/sdram_command_generator.v:11.12-11.17" *)
  output ras_n;
  wire ras_n;
  (* src = "RTL/sdram_command_generator.v:6.12-6.20" *)
  input read_cmd;
  wire read_cmd;
  (* src = "RTL/sdram_command_generator.v:4.12-4.19" *)
  input refresh;
  wire refresh;
  (* src = "RTL/sdram_command_generator.v:13.12-13.16" *)
  output we_n;
  wire we_n;
  (* src = "RTL/sdram_command_generator.v:7.12-7.21" *)
  input write_cmd;
  wire write_cmd;
  assign _08_ = precharge ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:57.13-57.22|RTL/sdram_command_generator.v:57.10-85.8" *) 1'h0 : _10_;
  assign _06_ = precharge ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:57.13-57.22|RTL/sdram_command_generator.v:57.10-85.8" *) 1'h1 : _09_;
  assign _07_ = precharge ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:57.13-57.22|RTL/sdram_command_generator.v:57.10-85.8" *) 1'h0 : _09_;
  assign _05_ = write_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:47.13-47.22|RTL/sdram_command_generator.v:47.10-85.8" *) 1'h0 : _08_;
  assign _03_ = write_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:47.13-47.22|RTL/sdram_command_generator.v:47.10-85.8" *) 1'h0 : _06_;
  assign _04_ = write_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:47.13-47.22|RTL/sdram_command_generator.v:47.10-85.8" *) 1'h1 : _07_;
  assign _02_ = read_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:36.13-36.21|RTL/sdram_command_generator.v:36.10-85.8" *) 1'h1 : _05_;
  assign _00_ = read_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:36.13-36.21|RTL/sdram_command_generator.v:36.10-85.8" *) 1'h0 : _03_;
  assign _01_ = read_cmd ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:36.13-36.21|RTL/sdram_command_generator.v:36.10-85.8" *) 1'h1 : _04_;
  assign we_n = activate ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:26.8-26.16|RTL/sdram_command_generator.v:26.5-85.8" *) 1'h1 : _02_;
  assign cas_n = activate ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:26.8-26.16|RTL/sdram_command_generator.v:26.5-85.8" *) 1'h1 : _00_;
  assign ras_n = activate ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:26.8-26.16|RTL/sdram_command_generator.v:26.5-85.8" *) 1'h0 : _01_;
  assign _11_ = load_mode ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:77.13-77.22|RTL/sdram_command_generator.v:77.10-85.8" *) 1'h0 : 1'h1;
  assign _10_ = refresh ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:67.13-67.20|RTL/sdram_command_generator.v:67.10-85.8" *) 1'h1 : _11_;
  assign _09_ = refresh ? (* full_case = 32'd1 *) (* src = "RTL/sdram_command_generator.v:67.13-67.20|RTL/sdram_command_generator.v:67.10-85.8" *) 1'h0 : _11_;
  assign cs_n = 1'h0;
endmodule
