/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/sdram_refresh_controller.v:1.1-50.10" *)
module sdram_refresh_controller(clk, rst, refresh_request);
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  wire [4:0] _0_;
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  wire _1_;
  (* src = "RTL/sdram_refresh_controller.v:45.24-45.35" *)
  (* unused_bits = "5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _2_;
  (* src = "RTL/sdram_refresh_controller.v:33.12-33.39" *)
  wire _3_;
  (* src = "RTL/sdram_refresh_controller.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_refresh_controller.v:15.32-15.39" *)
  reg [4:0] counter;
  (* src = "RTL/sdram_refresh_controller.v:12.12-12.27" *)
  output refresh_request;
  reg refresh_request;
  (* src = "RTL/sdram_refresh_controller.v:10.12-10.15" *)
  input rst;
  wire rst;
  assign _2_ = counter + (* src = "RTL/sdram_refresh_controller.v:45.24-45.35" *) 32'd1;
  assign _3_ = counter == (* src = "RTL/sdram_refresh_controller.v:33.12-33.39" *) 5'h0f;
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) refresh_request <= 1'h0;
    else refresh_request <= _1_;
  (* src = "RTL/sdram_refresh_controller.v:17.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 5'h00;
    else counter <= _0_;
  assign _1_ = _3_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_refresh_controller.v:33.12-33.39|RTL/sdram_refresh_controller.v:33.9-47.12" *) 1'h1 : 1'h0;
  assign _0_ = _3_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_refresh_controller.v:33.12-33.39|RTL/sdram_refresh_controller.v:33.9-47.12" *) 5'h00 : _2_[4:0];
endmodule
