/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/sdram_read_controller.v:1.1-97.10" *)
module sdram_read_controller(clk, rst, read_request, delay_done, start_delay, activate, read_cmd, read_done);
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _00_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _01_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _02_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire _03_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  wire [2:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [2:0] _12_;
  wire _13_;
  wire [2:0] _14_;
  wire _15_;
  (* src = "RTL/sdram_read_controller.v:9.12-9.20" *)
  output activate;
  reg activate;
  (* src = "RTL/sdram_read_controller.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_read_controller.v:6.12-6.22" *)
  input delay_done;
  wire delay_done;
  (* src = "RTL/sdram_read_controller.v:10.12-10.20" *)
  output read_cmd;
  reg read_cmd;
  (* src = "RTL/sdram_read_controller.v:11.12-11.21" *)
  output read_done;
  reg read_done;
  (* src = "RTL/sdram_read_controller.v:5.12-5.24" *)
  input read_request;
  wire read_request;
  (* src = "RTL/sdram_read_controller.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_read_controller.v:8.12-8.23" *)
  output start_delay;
  reg start_delay;
  (* src = "RTL/sdram_read_controller.v:20.11-20.16" *)
  reg [2:0] state;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_07_) state <= _04_;
  assign _05_ = { _15_, read_request } != 2'h2;
  assign _06_ = { _13_, delay_done } != 2'h2;
  assign _07_ = & { _06_, _05_ };
  assign _08_ = | { _13_, _11_ };
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_delay <= 1'h0;
    else start_delay <= _03_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) activate <= 1'h0;
    else activate <= _00_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) read_cmd <= 1'h0;
    else read_cmd <= _01_;
  (* src = "RTL/sdram_read_controller.v:22.1-96.4" *)
  always @(posedge clk, posedge rst)
    if (rst) read_done <= 1'h0;
    else read_done <= _02_;
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h4;
  assign _01_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
  assign _00_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
  function [2:0] _28_;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _28_ = b[2:0];
      4'b??1?:
        _28_ = b[5:3];
      4'b?1??:
        _28_ = b[8:6];
      4'b1???:
        _28_ = b[11:9];
      default:
        _28_ = a;
    endcase
  endfunction
  assign _04_ = _28_(3'h0, { _14_, 3'h2, _12_, 3'h4 }, { _15_, _11_, _13_, _10_ });
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h3;
  assign _12_ = delay_done ? (* src = "RTL/sdram_read_controller.v:68.16-68.26|RTL/sdram_read_controller.v:68.13-69.31" *) 3'h3 : 3'hx;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h2;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 3'h1;
  assign _14_ = read_request ? (* src = "RTL/sdram_read_controller.v:50.16-50.28|RTL/sdram_read_controller.v:50.13-51.35" *) 3'h1 : 3'hx;
  assign _15_ = ! (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) state;
  assign _03_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
  assign _02_ = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_read_controller.v:0.0-0.0|RTL/sdram_read_controller.v:45.9-93.16" *) 1'h1 : 1'h0;
endmodule
