/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/sdram_init_fsm.v:1.1-108.10" *)
module sdram_init_fsm(clk, rst, delay_done, start_delay, precharge, refresh, load_mode, init_done);
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _00_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _01_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _02_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire _03_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  wire [2:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [2:0] _15_;
  (* src = "RTL/sdram_init_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/sdram_init_fsm.v:5.12-5.22" *)
  input delay_done;
  wire delay_done;
  (* src = "RTL/sdram_init_fsm.v:11.12-11.21" *)
  output init_done;
  reg init_done;
  (* src = "RTL/sdram_init_fsm.v:10.12-10.21" *)
  output load_mode;
  reg load_mode;
  (* src = "RTL/sdram_init_fsm.v:8.12-8.21" *)
  output precharge;
  reg precharge;
  (* src = "RTL/sdram_init_fsm.v:9.12-9.19" *)
  output refresh;
  reg refresh;
  (* src = "RTL/sdram_init_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/sdram_init_fsm.v:7.12-7.23" *)
  output start_delay;
  reg start_delay;
  (* src = "RTL/sdram_init_fsm.v:21.11-21.16" *)
  reg [2:0] state;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) init_done <= 1'h0;
    else if (_13_) init_done <= 1'h1;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_07_) state <= _04_;
  assign _05_ = { _11_, delay_done } != 2'h2;
  assign _06_ = ~ _13_;
  assign _07_ = & { _06_, _05_ };
  assign _08_ = | { _12_, _11_ };
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_delay <= 1'h0;
    else start_delay <= _03_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) precharge <= 1'h0;
    else precharge <= _01_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) refresh <= 1'h0;
    else refresh <= _02_;
  (* src = "RTL/sdram_init_fsm.v:23.1-107.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load_mode <= 1'h0;
    else load_mode <= _00_;
  assign _01_ = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
  assign _03_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
  function [2:0] _28_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _28_ = b[2:0];
      6'b????1?:
        _28_ = b[5:3];
      6'b???1??:
        _28_ = b[8:6];
      6'b??1???:
        _28_ = b[11:9];
      6'b?1????:
        _28_ = b[14:12];
      6'b1?????:
        _28_ = b[17:15];
      default:
        _28_ = a;
    endcase
  endfunction
  assign _04_ = _28_(3'h0, { 3'h1, _15_, 12'b011100101xxx }, { _12_, _11_, _10_, _09_, _14_, _13_ });
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h4;
  assign _09_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h3;
  assign _10_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h2;
  assign _15_ = delay_done ? (* src = "RTL/sdram_init_fsm.v:63.16-63.26|RTL/sdram_init_fsm.v:63.13-64.36" *) 3'h2 : 3'hx;
  assign _11_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h1;
  assign _12_ = ! (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) state;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 3'h5;
  assign _00_ = _14_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
  assign _02_ = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/sdram_init_fsm.v:0.0-0.0|RTL/sdram_init_fsm.v:48.9-104.16" *) 1'h1 : 1'h0;
endmodule
