/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/uart_tx_fsm.v:1.1-112.10" *)
module uart_tx_fsm(clk, rst, start, baud_tick, shift_done, load, start_bit, shift_enable, stop_bit, busy, done);
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  wire _00_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  wire _01_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  wire _02_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  wire _03_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  wire _04_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  wire [2:0] _05_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [2:0] _17_;
  wire _18_;
  wire [2:0] _19_;
  wire [2:0] _20_;
  wire [2:0] _21_;
  wire _22_;
  wire _23_;
  (* src = "RTL/uart_tx_fsm.v:6.12-6.21" *)
  input baud_tick;
  wire baud_tick;
  (* src = "RTL/uart_tx_fsm.v:13.12-13.16" *)
  output busy;
  reg busy;
  (* src = "RTL/uart_tx_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/uart_tx_fsm.v:14.12-14.16" *)
  output done;
  reg done;
  (* src = "RTL/uart_tx_fsm.v:9.12-9.16" *)
  output load;
  reg load;
  (* src = "RTL/uart_tx_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/uart_tx_fsm.v:7.12-7.22" *)
  input shift_done;
  wire shift_done;
  (* src = "RTL/uart_tx_fsm.v:11.12-11.24" *)
  output shift_enable;
  reg shift_enable;
  (* src = "RTL/uart_tx_fsm.v:5.12-5.17" *)
  input start;
  wire start;
  (* src = "RTL/uart_tx_fsm.v:10.12-10.21" *)
  output start_bit;
  reg start_bit;
  (* src = "RTL/uart_tx_fsm.v:25.11-25.16" *)
  reg [2:0] state;
  (* src = "RTL/uart_tx_fsm.v:12.12-12.20" *)
  output stop_bit;
  reg stop_bit;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_07_) busy <= _00_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_12_) state <= _05_;
  assign _07_ = | { _16_, _13_ };
  assign _08_ = { _22_, start } != 2'h2;
  assign _09_ = { _18_, baud_tick } != 2'h2;
  assign _10_ = { _15_, baud_tick } != 2'h2;
  assign _11_ = { _14_, shift_done } != 2'h2;
  assign _12_ = & { _11_, _10_, _08_, _09_ };
  assign _13_ = | { _23_, _22_ };
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load <= 1'h0;
    else load <= _02_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_bit <= 1'h0;
    else start_bit <= _04_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift_enable <= 1'h0;
    else shift_enable <= _03_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  always @(posedge clk, posedge rst)
    if (rst) stop_bit <= 1'h0;
    else stop_bit <= _06_;
  (* src = "RTL/uart_tx_fsm.v:28.1-111.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _03_ = _14_ ? (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 1'h1 : 1'h0;
  assign _04_ = _15_ ? (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 1'h1 : 1'h0;
  assign _02_ = _16_ ? (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 1'h1 : 1'h0;
  assign _17_ = baud_tick ? (* src = "RTL/uart_tx_fsm.v:92.16-92.25|RTL/uart_tx_fsm.v:92.13-93.31" *) 3'h5 : 3'hx;
  assign _01_ = _23_ ? (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 1'h1 : 1'h0;
  function [2:0] _43_;
    input [2:0] a;
    input [14:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _43_ = b[2:0];
      5'b???1?:
        _43_ = b[5:3];
      5'b??1??:
        _43_ = b[8:6];
      5'b?1???:
        _43_ = b[11:9];
      5'b1????:
        _43_ = b[14:12];
      default:
        _43_ = a;
    endcase
  endfunction
  assign _05_ = _43_(3'h0, { _21_, 3'h2, _20_, _19_, _17_ }, { _22_, _16_, _15_, _14_, _18_ });
  assign _18_ = state == (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 3'h4;
  assign _19_ = shift_done ? (* src = "RTL/uart_tx_fsm.v:84.16-84.26|RTL/uart_tx_fsm.v:84.13-85.31" *) 3'h4 : 3'hx;
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 3'h3;
  assign _20_ = baud_tick ? (* src = "RTL/uart_tx_fsm.v:76.16-76.25|RTL/uart_tx_fsm.v:76.13-77.32" *) 3'h3 : 3'hx;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 3'h2;
  assign _21_ = start ? (* src = "RTL/uart_tx_fsm.v:60.16-60.21|RTL/uart_tx_fsm.v:60.13-61.31" *) 3'h1 : 3'hx;
  function [0:0] _50_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _50_ = b[0:0];
      2'b1?:
        _50_ = b[1:1];
      default:
        _50_ = a;
    endcase
  endfunction
  assign _00_ = _50_(1'hx, 2'h2, { _16_, _13_ });
  assign _23_ = state == (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 3'h5;
  assign _16_ = state == (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 3'h1;
  assign _22_ = ! (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) state;
  assign _06_ = _18_ ? (* full_case = 32'd1 *) (* src = "RTL/uart_tx_fsm.v:0.0-0.0|RTL/uart_tx_fsm.v:55.9-108.16" *) 1'h1 : 1'h0;
endmodule
