/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/axi_slave_read_data.v:1.1-50.10" *)
module axi_slave_read_data(clk, rst, register_data, data_available, rready, rdata, rvalid);
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "RTL/axi_slave_read_data.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_slave_read_data.v:12.12-12.26" *)
  input data_available;
  wire data_available;
  (* src = "RTL/axi_slave_read_data.v:15.29-15.34" *)
  output [31:0] rdata;
  reg [31:0] rdata;
  (* src = "RTL/axi_slave_read_data.v:11.29-11.42" *)
  input [31:0] register_data;
  wire [31:0] register_data;
  (* src = "RTL/axi_slave_read_data.v:13.12-13.18" *)
  input rready;
  wire rready;
  (* src = "RTL/axi_slave_read_data.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_slave_read_data.v:16.12-16.18" *)
  output rvalid;
  reg rvalid;
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[7] <= 1'h0;
    else if (data_available) rdata[7] <= register_data[7];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[8] <= 1'h0;
    else if (data_available) rdata[8] <= register_data[8];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[9] <= 1'h0;
    else if (data_available) rdata[9] <= register_data[9];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[10] <= 1'h0;
    else if (data_available) rdata[10] <= register_data[10];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[11] <= 1'h0;
    else if (data_available) rdata[11] <= register_data[11];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[12] <= 1'h0;
    else if (data_available) rdata[12] <= register_data[12];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[13] <= 1'h0;
    else if (data_available) rdata[13] <= register_data[13];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[14] <= 1'h0;
    else if (data_available) rdata[14] <= register_data[14];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[15] <= 1'h0;
    else if (data_available) rdata[15] <= register_data[15];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[16] <= 1'h0;
    else if (data_available) rdata[16] <= register_data[16];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[17] <= 1'h0;
    else if (data_available) rdata[17] <= register_data[17];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[18] <= 1'h0;
    else if (data_available) rdata[18] <= register_data[18];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[19] <= 1'h0;
    else if (data_available) rdata[19] <= register_data[19];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[20] <= 1'h0;
    else if (data_available) rdata[20] <= register_data[20];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[21] <= 1'h0;
    else if (data_available) rdata[21] <= register_data[21];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[22] <= 1'h0;
    else if (data_available) rdata[22] <= register_data[22];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[23] <= 1'h0;
    else if (data_available) rdata[23] <= register_data[23];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[24] <= 1'h0;
    else if (data_available) rdata[24] <= register_data[24];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[25] <= 1'h0;
    else if (data_available) rdata[25] <= register_data[25];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[26] <= 1'h0;
    else if (data_available) rdata[26] <= register_data[26];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[27] <= 1'h0;
    else if (data_available) rdata[27] <= register_data[27];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[28] <= 1'h0;
    else if (data_available) rdata[28] <= register_data[28];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[29] <= 1'h0;
    else if (data_available) rdata[29] <= register_data[29];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[30] <= 1'h0;
    else if (data_available) rdata[30] <= register_data[30];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[31] <= 1'h0;
    else if (data_available) rdata[31] <= register_data[31];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rvalid <= 1'h0;
    else if (_01_) rvalid <= _00_;
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[0] <= 1'h0;
    else if (data_available) rdata[0] <= register_data[0];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[1] <= 1'h0;
    else if (data_available) rdata[1] <= register_data[1];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[2] <= 1'h0;
    else if (data_available) rdata[2] <= register_data[2];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[3] <= 1'h0;
    else if (data_available) rdata[3] <= register_data[3];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[4] <= 1'h0;
    else if (data_available) rdata[4] <= register_data[4];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[5] <= 1'h0;
    else if (data_available) rdata[5] <= register_data[5];
  (* src = "RTL/axi_slave_read_data.v:19.1-49.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rdata[6] <= 1'h0;
    else if (data_available) rdata[6] <= register_data[6];
  assign _01_ = data_available | rready;
  assign _02_ = rready ? (* src = "RTL/axi_slave_read_data.v:42.17-42.23|RTL/axi_slave_read_data.v:42.14-47.12" *) 1'h0 : 1'hx;
  assign _00_ = data_available ? (* src = "RTL/axi_slave_read_data.v:33.12-33.26|RTL/axi_slave_read_data.v:33.9-47.12" *) 1'h1 : _02_;
endmodule
