/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* hdlname = "\\axi_register_file" *)
(* src = "RTL/axi_register_file.v:1.1-99.10" *)
module \$paramod$f18b761da11611e98d184a4065d2327c3caa05d1\axi_register_file (clk, rst, write_address, write_data, write_enable, read_address, read_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [1:0] _008_;
  wire [15:0] _009_;
  wire [7:0] _010_;
  wire [3:0] _011_;
  wire [1:0] _012_;
  wire [15:0] _013_;
  wire [7:0] _014_;
  wire [3:0] _015_;
  wire [1:0] _016_;
  wire [15:0] _017_;
  wire [7:0] _018_;
  wire [3:0] _019_;
  wire [1:0] _020_;
  wire [15:0] _021_;
  wire [7:0] _022_;
  wire [3:0] _023_;
  wire [1:0] _024_;
  wire [15:0] _025_;
  wire [7:0] _026_;
  wire [3:0] _027_;
  wire [1:0] _028_;
  wire [15:0] _029_;
  wire [7:0] _030_;
  wire [3:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [1:0] _035_;
  wire [1:0] _036_;
  wire [1:0] _037_;
  wire [1:0] _038_;
  wire [1:0] _039_;
  wire [1:0] _040_;
  wire [1:0] _041_;
  wire [1:0] _042_;
  wire [1:0] _043_;
  wire [1:0] _044_;
  wire [1:0] _045_;
  wire [1:0] _046_;
  wire [1:0] _047_;
  wire [1:0] _048_;
  wire [1:0] _049_;
  wire [1:0] _050_;
  wire [1:0] _051_;
  wire [1:0] _052_;
  wire [1:0] _053_;
  wire [1:0] _054_;
  wire [1:0] _055_;
  wire [1:0] _056_;
  wire [1:0] _057_;
  wire [1:0] _058_;
  wire [1:0] _059_;
  wire [1:0] _060_;
  wire [1:0] _061_;
  wire [1:0] _062_;
  wire [1:0] _063_;
  wire [1:0] _064_;
  wire [15:0] _065_;
  wire [7:0] _066_;
  wire [3:0] _067_;
  wire [1:0] _068_;
  wire _069_;
  wire [15:0] _070_;
  wire [7:0] _071_;
  wire [3:0] _072_;
  wire [1:0] _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  (* force_downto = 32'd1 *)
  (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [127:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _082_;
  (* force_downto = 32'd1 *)
  (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [31:0] _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _088_;
  (* src = "RTL/axi_register_file.v:11.12-11.15" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_register_file.v:22.29-22.41" *)
  input [31:0] read_address;
  wire [31:0] read_address;
  (* src = "RTL/axi_register_file.v:24.29-24.38" *)
  output [31:0] read_data;
  wire [31:0] read_data;
  (* src = "RTL/axi_register_file.v:30.22-30.26" *)
  reg [31:0] reg0;
  (* src = "RTL/axi_register_file.v:31.22-31.26" *)
  reg [31:0] reg1;
  (* src = "RTL/axi_register_file.v:32.22-32.26" *)
  reg [31:0] reg2;
  (* src = "RTL/axi_register_file.v:33.22-33.26" *)
  reg [31:0] reg3;
  (* src = "RTL/axi_register_file.v:12.12-12.15" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_register_file.v:16.29-16.42" *)
  input [31:0] write_address;
  wire [31:0] write_address;
  (* src = "RTL/axi_register_file.v:17.29-17.39" *)
  input [31:0] write_data;
  wire [31:0] write_data;
  (* src = "RTL/axi_register_file.v:18.12-18.24" *)
  input write_enable;
  wire write_enable;
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[0] <= 1'h0;
    else if (_003_) reg3[0] <= write_data[0];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[1] <= 1'h0;
    else if (_003_) reg3[1] <= write_data[1];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[2] <= 1'h0;
    else if (_003_) reg3[2] <= write_data[2];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[3] <= 1'h0;
    else if (_003_) reg3[3] <= write_data[3];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[4] <= 1'h0;
    else if (_003_) reg3[4] <= write_data[4];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[5] <= 1'h0;
    else if (_003_) reg3[5] <= write_data[5];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[6] <= 1'h0;
    else if (_003_) reg3[6] <= write_data[6];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[7] <= 1'h0;
    else if (_003_) reg3[7] <= write_data[7];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[8] <= 1'h0;
    else if (_003_) reg3[8] <= write_data[8];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[9] <= 1'h0;
    else if (_003_) reg3[9] <= write_data[9];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[10] <= 1'h0;
    else if (_003_) reg3[10] <= write_data[10];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[11] <= 1'h0;
    else if (_003_) reg3[11] <= write_data[11];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[12] <= 1'h0;
    else if (_003_) reg3[12] <= write_data[12];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[13] <= 1'h0;
    else if (_003_) reg3[13] <= write_data[13];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[14] <= 1'h0;
    else if (_003_) reg3[14] <= write_data[14];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[15] <= 1'h0;
    else if (_003_) reg3[15] <= write_data[15];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[16] <= 1'h0;
    else if (_003_) reg3[16] <= write_data[16];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[17] <= 1'h0;
    else if (_003_) reg3[17] <= write_data[17];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[18] <= 1'h0;
    else if (_003_) reg3[18] <= write_data[18];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[19] <= 1'h0;
    else if (_003_) reg3[19] <= write_data[19];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[20] <= 1'h0;
    else if (_003_) reg3[20] <= write_data[20];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[21] <= 1'h0;
    else if (_003_) reg3[21] <= write_data[21];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[22] <= 1'h0;
    else if (_003_) reg3[22] <= write_data[22];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[23] <= 1'h0;
    else if (_003_) reg3[23] <= write_data[23];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[24] <= 1'h0;
    else if (_003_) reg3[24] <= write_data[24];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[25] <= 1'h0;
    else if (_003_) reg3[25] <= write_data[25];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[26] <= 1'h0;
    else if (_003_) reg3[26] <= write_data[26];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[27] <= 1'h0;
    else if (_003_) reg3[27] <= write_data[27];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[28] <= 1'h0;
    else if (_003_) reg3[28] <= write_data[28];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[29] <= 1'h0;
    else if (_003_) reg3[29] <= write_data[29];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[30] <= 1'h0;
    else if (_003_) reg3[30] <= write_data[30];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg3[31] <= 1'h0;
    else if (_003_) reg3[31] <= write_data[31];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[0] <= 1'h0;
    else if (_002_) reg2[0] <= write_data[0];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[1] <= 1'h0;
    else if (_002_) reg2[1] <= write_data[1];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[2] <= 1'h0;
    else if (_002_) reg2[2] <= write_data[2];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[3] <= 1'h0;
    else if (_002_) reg2[3] <= write_data[3];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[4] <= 1'h0;
    else if (_002_) reg2[4] <= write_data[4];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[5] <= 1'h0;
    else if (_002_) reg2[5] <= write_data[5];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[6] <= 1'h0;
    else if (_002_) reg2[6] <= write_data[6];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[7] <= 1'h0;
    else if (_002_) reg2[7] <= write_data[7];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[8] <= 1'h0;
    else if (_002_) reg2[8] <= write_data[8];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[9] <= 1'h0;
    else if (_002_) reg2[9] <= write_data[9];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[10] <= 1'h0;
    else if (_002_) reg2[10] <= write_data[10];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[11] <= 1'h0;
    else if (_002_) reg2[11] <= write_data[11];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[12] <= 1'h0;
    else if (_002_) reg2[12] <= write_data[12];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[13] <= 1'h0;
    else if (_002_) reg2[13] <= write_data[13];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[14] <= 1'h0;
    else if (_002_) reg2[14] <= write_data[14];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[15] <= 1'h0;
    else if (_002_) reg2[15] <= write_data[15];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[16] <= 1'h0;
    else if (_002_) reg2[16] <= write_data[16];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[17] <= 1'h0;
    else if (_002_) reg2[17] <= write_data[17];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[18] <= 1'h0;
    else if (_002_) reg2[18] <= write_data[18];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[19] <= 1'h0;
    else if (_002_) reg2[19] <= write_data[19];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[20] <= 1'h0;
    else if (_002_) reg2[20] <= write_data[20];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[21] <= 1'h0;
    else if (_002_) reg2[21] <= write_data[21];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[22] <= 1'h0;
    else if (_002_) reg2[22] <= write_data[22];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[23] <= 1'h0;
    else if (_002_) reg2[23] <= write_data[23];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[24] <= 1'h0;
    else if (_002_) reg2[24] <= write_data[24];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[25] <= 1'h0;
    else if (_002_) reg2[25] <= write_data[25];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[26] <= 1'h0;
    else if (_002_) reg2[26] <= write_data[26];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[27] <= 1'h0;
    else if (_002_) reg2[27] <= write_data[27];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[28] <= 1'h0;
    else if (_002_) reg2[28] <= write_data[28];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[29] <= 1'h0;
    else if (_002_) reg2[29] <= write_data[29];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[30] <= 1'h0;
    else if (_002_) reg2[30] <= write_data[30];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg2[31] <= 1'h0;
    else if (_002_) reg2[31] <= write_data[31];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[0] <= 1'h0;
    else if (_001_) reg1[0] <= write_data[0];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[1] <= 1'h0;
    else if (_001_) reg1[1] <= write_data[1];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[2] <= 1'h0;
    else if (_001_) reg1[2] <= write_data[2];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[3] <= 1'h0;
    else if (_001_) reg1[3] <= write_data[3];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[4] <= 1'h0;
    else if (_001_) reg1[4] <= write_data[4];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[5] <= 1'h0;
    else if (_001_) reg1[5] <= write_data[5];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[6] <= 1'h0;
    else if (_001_) reg1[6] <= write_data[6];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[7] <= 1'h0;
    else if (_001_) reg1[7] <= write_data[7];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[8] <= 1'h0;
    else if (_001_) reg1[8] <= write_data[8];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[9] <= 1'h0;
    else if (_001_) reg1[9] <= write_data[9];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[10] <= 1'h0;
    else if (_001_) reg1[10] <= write_data[10];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[11] <= 1'h0;
    else if (_001_) reg1[11] <= write_data[11];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[12] <= 1'h0;
    else if (_001_) reg1[12] <= write_data[12];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[13] <= 1'h0;
    else if (_001_) reg1[13] <= write_data[13];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[14] <= 1'h0;
    else if (_001_) reg1[14] <= write_data[14];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[15] <= 1'h0;
    else if (_001_) reg1[15] <= write_data[15];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[16] <= 1'h0;
    else if (_001_) reg1[16] <= write_data[16];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[17] <= 1'h0;
    else if (_001_) reg1[17] <= write_data[17];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[18] <= 1'h0;
    else if (_001_) reg1[18] <= write_data[18];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[19] <= 1'h0;
    else if (_001_) reg1[19] <= write_data[19];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[20] <= 1'h0;
    else if (_001_) reg1[20] <= write_data[20];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[21] <= 1'h0;
    else if (_001_) reg1[21] <= write_data[21];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[22] <= 1'h0;
    else if (_001_) reg1[22] <= write_data[22];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[23] <= 1'h0;
    else if (_001_) reg1[23] <= write_data[23];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[24] <= 1'h0;
    else if (_001_) reg1[24] <= write_data[24];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[25] <= 1'h0;
    else if (_001_) reg1[25] <= write_data[25];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[26] <= 1'h0;
    else if (_001_) reg1[26] <= write_data[26];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[27] <= 1'h0;
    else if (_001_) reg1[27] <= write_data[27];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[28] <= 1'h0;
    else if (_001_) reg1[28] <= write_data[28];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[29] <= 1'h0;
    else if (_001_) reg1[29] <= write_data[29];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[30] <= 1'h0;
    else if (_001_) reg1[30] <= write_data[30];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg1[31] <= 1'h0;
    else if (_001_) reg1[31] <= write_data[31];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[0] <= 1'h0;
    else if (_000_) reg0[0] <= write_data[0];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[1] <= 1'h0;
    else if (_000_) reg0[1] <= write_data[1];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[2] <= 1'h0;
    else if (_000_) reg0[2] <= write_data[2];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[3] <= 1'h0;
    else if (_000_) reg0[3] <= write_data[3];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[4] <= 1'h0;
    else if (_000_) reg0[4] <= write_data[4];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[5] <= 1'h0;
    else if (_000_) reg0[5] <= write_data[5];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[6] <= 1'h0;
    else if (_000_) reg0[6] <= write_data[6];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[7] <= 1'h0;
    else if (_000_) reg0[7] <= write_data[7];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[8] <= 1'h0;
    else if (_000_) reg0[8] <= write_data[8];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[9] <= 1'h0;
    else if (_000_) reg0[9] <= write_data[9];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[10] <= 1'h0;
    else if (_000_) reg0[10] <= write_data[10];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[11] <= 1'h0;
    else if (_000_) reg0[11] <= write_data[11];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[12] <= 1'h0;
    else if (_000_) reg0[12] <= write_data[12];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[13] <= 1'h0;
    else if (_000_) reg0[13] <= write_data[13];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[14] <= 1'h0;
    else if (_000_) reg0[14] <= write_data[14];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[15] <= 1'h0;
    else if (_000_) reg0[15] <= write_data[15];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[16] <= 1'h0;
    else if (_000_) reg0[16] <= write_data[16];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[17] <= 1'h0;
    else if (_000_) reg0[17] <= write_data[17];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[18] <= 1'h0;
    else if (_000_) reg0[18] <= write_data[18];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[19] <= 1'h0;
    else if (_000_) reg0[19] <= write_data[19];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[20] <= 1'h0;
    else if (_000_) reg0[20] <= write_data[20];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[21] <= 1'h0;
    else if (_000_) reg0[21] <= write_data[21];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[22] <= 1'h0;
    else if (_000_) reg0[22] <= write_data[22];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[23] <= 1'h0;
    else if (_000_) reg0[23] <= write_data[23];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[24] <= 1'h0;
    else if (_000_) reg0[24] <= write_data[24];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[25] <= 1'h0;
    else if (_000_) reg0[25] <= write_data[25];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[26] <= 1'h0;
    else if (_000_) reg0[26] <= write_data[26];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[27] <= 1'h0;
    else if (_000_) reg0[27] <= write_data[27];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[28] <= 1'h0;
    else if (_000_) reg0[28] <= write_data[28];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[29] <= 1'h0;
    else if (_000_) reg0[29] <= write_data[29];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[30] <= 1'h0;
    else if (_000_) reg0[30] <= write_data[30];
  (* src = "RTL/axi_register_file.v:37.1-73.4" *)
  always @(posedge clk, posedge rst)
    if (rst) reg0[31] <= 1'h0;
    else if (_000_) reg0[31] <= write_data[31];
  assign _004_ = ~read_address[2];
  assign _005_ = ~read_address[3];
  assign _007_ = ~write_address[3];
  assign _006_ = ~write_address[2];
  assign _008_[0] = _082_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _082_[1];
  assign _008_[1] = _082_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _082_[3];
  assign _088_ = _008_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _008_[1];
  assign _009_[1] = _004_ |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _005_;
  assign _010_[0] = _009_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[1];
  assign _011_[0] = _010_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _010_[1];
  assign _012_[0] = _011_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _011_[1];
  assign _075_ = _012_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _012_[1];
  assign _013_[1] = _006_ |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _007_;
  assign _014_[0] = _013_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[1];
  assign _015_[0] = _014_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _014_[1];
  assign _016_[0] = _015_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _015_[1];
  assign _076_ = _016_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _016_[1];
  assign _017_[1] = _004_ |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[3];
  assign _018_[0] = _009_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _017_[1];
  assign _019_[0] = _018_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _010_[1];
  assign _020_[0] = _019_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _011_[1];
  assign _077_ = _020_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _012_[1];
  assign _009_[0] = read_address[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[1];
  assign _021_[1] = read_address[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _005_;
  assign _009_[2] = read_address[4] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[5];
  assign _009_[3] = read_address[6] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[7];
  assign _009_[4] = read_address[8] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[9];
  assign _009_[5] = read_address[10] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[11];
  assign _009_[6] = read_address[12] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[13];
  assign _009_[7] = read_address[14] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[15];
  assign _009_[8] = read_address[16] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[17];
  assign _009_[9] = read_address[18] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[19];
  assign _009_[10] = read_address[20] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[21];
  assign _009_[11] = read_address[22] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[23];
  assign _009_[12] = read_address[24] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[25];
  assign _009_[13] = read_address[26] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[27];
  assign _009_[14] = read_address[28] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[29];
  assign _009_[15] = read_address[30] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[31];
  assign _022_[0] = _009_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _021_[1];
  assign _010_[1] = _009_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[3];
  assign _010_[2] = _009_[4] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[5];
  assign _010_[3] = _009_[6] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[7];
  assign _010_[4] = _009_[8] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[9];
  assign _010_[5] = _009_[10] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[11];
  assign _010_[6] = _009_[12] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[13];
  assign _010_[7] = _009_[14] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _009_[15];
  assign _023_[0] = _022_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _010_[1];
  assign _011_[1] = _010_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _010_[3];
  assign _011_[2] = _010_[4] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _010_[5];
  assign _011_[3] = _010_[6] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _010_[7];
  assign _024_[0] = _023_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _011_[1];
  assign _012_[1] = _011_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _011_[3];
  assign _078_ = _024_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _012_[1];
  assign _025_[1] = write_address[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _007_;
  assign _026_[0] = _013_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _025_[1];
  assign _027_[0] = _026_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _014_[1];
  assign _028_[0] = _027_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _015_[1];
  assign _079_ = _028_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _016_[1];
  assign _029_[1] = _006_ |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[3];
  assign _030_[0] = _013_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _029_[1];
  assign _031_[0] = _030_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _014_[1];
  assign _032_[0] = _031_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _015_[1];
  assign _080_ = _032_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _016_[1];
  assign _001_ = write_enable & _086_;
  assign _000_ = write_enable & _087_;
  assign _003_ = write_enable & _084_;
  assign _002_ = write_enable & _085_;
  assign _033_[0] = _081_[31] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[63];
  assign _033_[1] = _081_[95] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[127];
  assign _083_[31] = _033_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _033_[1];
  assign _034_[0] = _081_[30] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[62];
  assign _034_[1] = _081_[94] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[126];
  assign _083_[30] = _034_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _034_[1];
  assign _035_[0] = _081_[29] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[61];
  assign _035_[1] = _081_[93] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[125];
  assign _083_[29] = _035_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _035_[1];
  assign _036_[0] = _081_[28] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[60];
  assign _036_[1] = _081_[92] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[124];
  assign _083_[28] = _036_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _036_[1];
  assign _037_[0] = _081_[27] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[59];
  assign _037_[1] = _081_[91] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[123];
  assign _083_[27] = _037_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _037_[1];
  assign _038_[0] = _081_[26] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[58];
  assign _038_[1] = _081_[90] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[122];
  assign _083_[26] = _038_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _038_[1];
  assign _039_[0] = _081_[25] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[57];
  assign _039_[1] = _081_[89] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[121];
  assign _083_[25] = _039_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _039_[1];
  assign _040_[0] = _081_[24] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[56];
  assign _040_[1] = _081_[88] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[120];
  assign _083_[24] = _040_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _040_[1];
  assign _041_[0] = _081_[23] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[55];
  assign _041_[1] = _081_[87] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[119];
  assign _083_[23] = _041_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _041_[1];
  assign _042_[0] = _081_[22] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[54];
  assign _042_[1] = _081_[86] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[118];
  assign _083_[22] = _042_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _042_[1];
  assign _043_[0] = _081_[21] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[53];
  assign _043_[1] = _081_[85] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[117];
  assign _083_[21] = _043_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _043_[1];
  assign _044_[0] = _081_[20] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[52];
  assign _044_[1] = _081_[84] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[116];
  assign _083_[20] = _044_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _044_[1];
  assign _045_[0] = _081_[19] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[51];
  assign _045_[1] = _081_[83] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[115];
  assign _083_[19] = _045_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _045_[1];
  assign _046_[0] = _081_[18] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[50];
  assign _046_[1] = _081_[82] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[114];
  assign _083_[18] = _046_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _046_[1];
  assign _047_[0] = _081_[17] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[49];
  assign _047_[1] = _081_[81] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[113];
  assign _083_[17] = _047_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _047_[1];
  assign _048_[0] = _081_[16] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[48];
  assign _048_[1] = _081_[80] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[112];
  assign _083_[16] = _048_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _048_[1];
  assign _049_[0] = _081_[15] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[47];
  assign _049_[1] = _081_[79] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[111];
  assign _083_[15] = _049_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[1];
  assign _050_[0] = _081_[14] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[46];
  assign _050_[1] = _081_[78] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[110];
  assign _083_[14] = _050_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _050_[1];
  assign _051_[0] = _081_[13] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[45];
  assign _051_[1] = _081_[77] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[109];
  assign _083_[13] = _051_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _051_[1];
  assign _052_[0] = _081_[12] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[44];
  assign _052_[1] = _081_[76] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[108];
  assign _083_[12] = _052_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _052_[1];
  assign _053_[0] = _081_[11] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[43];
  assign _053_[1] = _081_[75] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[107];
  assign _083_[11] = _053_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _053_[1];
  assign _054_[0] = _081_[10] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[42];
  assign _054_[1] = _081_[74] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[106];
  assign _083_[10] = _054_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _054_[1];
  assign _055_[0] = _081_[9] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[41];
  assign _055_[1] = _081_[73] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[105];
  assign _083_[9] = _055_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _055_[1];
  assign _056_[0] = _081_[8] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[40];
  assign _056_[1] = _081_[72] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[104];
  assign _083_[8] = _056_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _056_[1];
  assign _057_[0] = _081_[7] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[39];
  assign _057_[1] = _081_[71] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[103];
  assign _083_[7] = _057_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _057_[1];
  assign _058_[0] = _081_[6] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[38];
  assign _058_[1] = _081_[70] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[102];
  assign _083_[6] = _058_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _058_[1];
  assign _059_[0] = _081_[5] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[37];
  assign _059_[1] = _081_[69] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[101];
  assign _083_[5] = _059_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _059_[1];
  assign _060_[0] = _081_[4] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[36];
  assign _060_[1] = _081_[68] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[100];
  assign _083_[4] = _060_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _060_[1];
  assign _061_[0] = _081_[3] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[35];
  assign _061_[1] = _081_[67] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[99];
  assign _083_[3] = _061_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _061_[1];
  assign _062_[0] = _081_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[34];
  assign _062_[1] = _081_[66] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[98];
  assign _083_[2] = _062_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _062_[1];
  assign _063_[0] = _081_[1] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[33];
  assign _063_[1] = _081_[65] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[97];
  assign _083_[1] = _063_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _063_[1];
  assign _064_[0] = _081_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[32];
  assign _064_[1] = _081_[64] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _081_[96];
  assign _083_[0] = _064_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _064_[1];
  assign _065_[1] = read_address[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  read_address[3];
  assign _066_[0] = _009_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _065_[1];
  assign _067_[0] = _066_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _010_[1];
  assign _068_[0] = _067_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _011_[1];
  assign _069_ = _068_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *)  _012_[1];
  assign _013_[0] = write_address[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[1];
  assign _070_[1] = write_address[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[3];
  assign _013_[2] = write_address[4] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[5];
  assign _013_[3] = write_address[6] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[7];
  assign _013_[4] = write_address[8] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[9];
  assign _013_[5] = write_address[10] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[11];
  assign _013_[6] = write_address[12] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[13];
  assign _013_[7] = write_address[14] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[15];
  assign _013_[8] = write_address[16] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[17];
  assign _013_[9] = write_address[18] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[19];
  assign _013_[10] = write_address[20] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[21];
  assign _013_[11] = write_address[22] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[23];
  assign _013_[12] = write_address[24] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[25];
  assign _013_[13] = write_address[26] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[27];
  assign _013_[14] = write_address[28] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[29];
  assign _013_[15] = write_address[30] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  write_address[31];
  assign _071_[0] = _013_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _070_[1];
  assign _014_[1] = _013_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[3];
  assign _014_[2] = _013_[4] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[5];
  assign _014_[3] = _013_[6] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[7];
  assign _014_[4] = _013_[8] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[9];
  assign _014_[5] = _013_[10] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[11];
  assign _014_[6] = _013_[12] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[13];
  assign _014_[7] = _013_[14] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _013_[15];
  assign _072_[0] = _071_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _014_[1];
  assign _015_[1] = _014_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _014_[3];
  assign _015_[2] = _014_[4] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _014_[5];
  assign _015_[3] = _014_[6] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _014_[7];
  assign _073_[0] = _072_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _015_[1];
  assign _016_[1] = _015_[2] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _015_[3];
  assign _074_ = _073_[0] |(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *)  _016_[1];
  assign _082_[0] = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *) _075_;
  assign _084_ = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *) _076_;
  assign _082_[3] = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *) _069_;
  assign _082_[2] = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *) _077_;
  assign _082_[1] = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12" *) _078_;
  assign _085_ = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *) _079_;
  assign _086_ = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *) _080_;
  assign _087_ = ~(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:56.13-70.20" *) _074_;
  assign read_data[0] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[0] : 1'h0;
  assign read_data[1] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[1] : 1'h0;
  assign read_data[2] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[2] : 1'h0;
  assign read_data[3] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[3] : 1'h0;
  assign read_data[4] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[4] : 1'h0;
  assign read_data[5] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[5] : 1'h0;
  assign read_data[6] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[6] : 1'h0;
  assign read_data[7] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[7] : 1'h0;
  assign read_data[8] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[8] : 1'h0;
  assign read_data[9] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[9] : 1'h0;
  assign read_data[10] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[10] : 1'h0;
  assign read_data[11] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[11] : 1'h0;
  assign read_data[12] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[12] : 1'h0;
  assign read_data[13] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[13] : 1'h0;
  assign read_data[14] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[14] : 1'h0;
  assign read_data[15] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[15] : 1'h0;
  assign read_data[16] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[16] : 1'h0;
  assign read_data[17] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[17] : 1'h0;
  assign read_data[18] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[18] : 1'h0;
  assign read_data[19] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[19] : 1'h0;
  assign read_data[20] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[20] : 1'h0;
  assign read_data[21] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[21] : 1'h0;
  assign read_data[22] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[22] : 1'h0;
  assign read_data[23] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[23] : 1'h0;
  assign read_data[24] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[24] : 1'h0;
  assign read_data[25] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[25] : 1'h0;
  assign read_data[26] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[26] : 1'h0;
  assign read_data[27] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[27] : 1'h0;
  assign read_data[28] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[28] : 1'h0;
  assign read_data[29] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[29] : 1'h0;
  assign read_data[30] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[30] : 1'h0;
  assign read_data[31] = _088_ ? (* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _083_[31] : 1'h0;
  assign _081_[112] = reg0[16] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[113] = reg0[17] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[114] = reg0[18] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[115] = reg0[19] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[116] = reg0[20] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[117] = reg0[21] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[118] = reg0[22] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[119] = reg0[23] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[120] = reg0[24] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[121] = reg0[25] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[122] = reg0[26] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[123] = reg0[27] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[124] = reg0[28] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[125] = reg0[29] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[126] = reg0[30] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[127] = reg0[31] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[64] = reg1[0] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[65] = reg1[1] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[66] = reg1[2] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[67] = reg1[3] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[68] = reg1[4] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[69] = reg1[5] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[70] = reg1[6] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[71] = reg1[7] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[72] = reg1[8] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[73] = reg1[9] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[74] = reg1[10] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[75] = reg1[11] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[76] = reg1[12] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[77] = reg1[13] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[78] = reg1[14] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[79] = reg1[15] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[80] = reg1[16] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[81] = reg1[17] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[82] = reg1[18] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[83] = reg1[19] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[84] = reg1[20] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[85] = reg1[21] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[86] = reg1[22] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[87] = reg1[23] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[88] = reg1[24] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[89] = reg1[25] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[90] = reg1[26] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[91] = reg1[27] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[92] = reg1[28] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[93] = reg1[29] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[94] = reg1[30] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[95] = reg1[31] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[2];
  assign _081_[32] = reg2[0] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[33] = reg2[1] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[34] = reg2[2] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[35] = reg2[3] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[36] = reg2[4] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[37] = reg2[5] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[38] = reg2[6] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[39] = reg2[7] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[40] = reg2[8] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[41] = reg2[9] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[42] = reg2[10] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[43] = reg2[11] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[44] = reg2[12] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[45] = reg2[13] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[46] = reg2[14] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[47] = reg2[15] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[48] = reg2[16] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[49] = reg2[17] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[50] = reg2[18] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[51] = reg2[19] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[52] = reg2[20] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[53] = reg2[21] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[54] = reg2[22] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[55] = reg2[23] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[56] = reg2[24] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[57] = reg2[25] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[58] = reg2[26] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[59] = reg2[27] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[60] = reg2[28] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[61] = reg2[29] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[62] = reg2[30] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[63] = reg2[31] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[1];
  assign _081_[0] = reg3[0] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[1] = reg3[1] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[2] = reg3[2] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[3] = reg3[3] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[4] = reg3[4] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[5] = reg3[5] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[6] = reg3[6] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[7] = reg3[7] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[8] = reg3[8] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[9] = reg3[9] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[10] = reg3[10] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[11] = reg3[11] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[12] = reg3[12] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[13] = reg3[13] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[14] = reg3[14] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[15] = reg3[15] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[16] = reg3[16] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[17] = reg3[17] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[18] = reg3[18] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[19] = reg3[19] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[20] = reg3[20] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[21] = reg3[21] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[22] = reg3[22] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[23] = reg3[23] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[24] = reg3[24] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[25] = reg3[25] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[26] = reg3[26] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[27] = reg3[27] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[28] = reg3[28] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[29] = reg3[29] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[30] = reg3[30] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[31] = reg3[31] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[0];
  assign _081_[96] = reg0[0] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[97] = reg0[1] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[98] = reg0[2] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[99] = reg0[3] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[100] = reg0[4] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[101] = reg0[5] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[102] = reg0[6] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[103] = reg0[7] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[104] = reg0[8] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[105] = reg0[9] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[106] = reg0[10] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[107] = reg0[11] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[108] = reg0[12] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[109] = reg0[13] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[110] = reg0[14] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign _081_[111] = reg0[15] &(* src = "RTL/axi_register_file.v:0.0-0.0|RTL/axi_register_file.v:80.5-97.12|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _082_[3];
  assign { _017_[15:2], _017_[0] } = { _009_[15:2], _009_[0] };
  assign _018_[7:1] = _010_[7:1];
  assign _019_[3:1] = _011_[3:1];
  assign _020_[1] = _012_[1];
  assign { _021_[15:2], _021_[0] } = { _009_[15:2], _009_[0] };
  assign _022_[7:1] = _010_[7:1];
  assign _023_[3:1] = _011_[3:1];
  assign _024_[1] = _012_[1];
  assign { _025_[15:2], _025_[0] } = { _013_[15:2], _013_[0] };
  assign _026_[7:1] = _014_[7:1];
  assign _027_[3:1] = _015_[3:1];
  assign _028_[1] = _016_[1];
  assign { _029_[15:2], _029_[0] } = { _013_[15:2], _013_[0] };
  assign _030_[7:1] = _014_[7:1];
  assign _031_[3:1] = _015_[3:1];
  assign _032_[1] = _016_[1];
  assign { _065_[15:2], _065_[0] } = { _009_[15:2], _009_[0] };
  assign _066_[7:1] = _010_[7:1];
  assign _067_[3:1] = _011_[3:1];
  assign _068_[1] = _012_[1];
  assign { _070_[15:2], _070_[0] } = { _013_[15:2], _013_[0] };
  assign _071_[7:1] = _014_[7:1];
  assign _072_[3:1] = _015_[3:1];
  assign _073_[1] = _016_[1];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/axi_slave_top.v:1.1-49.10" *)
module axi_slave_top(clk, rst, write_address, write_data, write_enable, read_address, read_data);
  (* src = "RTL/axi_slave_top.v:9.16-9.19" *)
  input clk;
  wire clk;
  (* src = "RTL/axi_slave_top.v:20.33-20.45" *)
  input [31:0] read_address;
  wire [31:0] read_address;
  (* src = "RTL/axi_slave_top.v:22.34-22.43" *)
  output [31:0] read_data;
  wire [31:0] read_data;
  (* src = "RTL/axi_slave_top.v:10.16-10.19" *)
  input rst;
  wire rst;
  (* src = "RTL/axi_slave_top.v:14.33-14.46" *)
  input [31:0] write_address;
  wire [31:0] write_address;
  (* src = "RTL/axi_slave_top.v:15.33-15.43" *)
  input [31:0] write_data;
  wire [31:0] write_data;
  (* src = "RTL/axi_slave_top.v:16.16-16.28" *)
  input write_enable;
  wire write_enable;
  (* src = "RTL/axi_slave_top.v:34.1-47.2" *)
  \$paramod$f18b761da11611e98d184a4065d2327c3caa05d1\axi_register_file  register_file_inst (
    .clk(clk),
    .read_address(read_address),
    .read_data(read_data),
    .rst(rst),
    .write_address(write_address),
    .write_data(write_data),
    .write_enable(write_enable)
  );
endmodule
