/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/i2c_clock_generator.v:1.1-49.10" *)
module i2c_clock_generator(clk, rst, scl);
  (* src = "RTL/i2c_clock_generator.v:19.1-48.4" *)
  wire [15:0] _0_;
  (* src = "RTL/i2c_clock_generator.v:44.24-44.38" *)
  wire [15:0] _1_;
  (* src = "RTL/i2c_clock_generator.v:33.12-33.32" *)
  wire _2_;
  (* src = "RTL/i2c_clock_generator.v:37.20-37.24" *)
  wire _3_;
  (* src = "RTL/i2c_clock_generator.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_clock_generator.v:16.12-16.19" *)
  reg [15:0] counter;
  (* src = "RTL/i2c_clock_generator.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_clock_generator.v:12.12-12.15" *)
  output scl;
  reg scl;
  assign _1_ = counter + (* src = "RTL/i2c_clock_generator.v:44.24-44.38" *) 1'h1;
  (* src = "RTL/i2c_clock_generator.v:19.1-48.4" *)
  always @(posedge clk, posedge rst)
    if (rst) scl <= 1'h1;
    else if (_2_) scl <= _3_;
  assign _2_ = counter == (* src = "RTL/i2c_clock_generator.v:33.12-33.32" *) 16'h00f9;
  assign _3_ = ~ (* src = "RTL/i2c_clock_generator.v:37.20-37.24" *) scl;
  (* src = "RTL/i2c_clock_generator.v:19.1-48.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 16'h0000;
    else counter <= _0_;
  assign _0_ = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_clock_generator.v:33.12-33.32|RTL/i2c_clock_generator.v:33.9-45.12" *) 16'h0000 : _1_;
endmodule
