/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/i2c_master_fsm.v:1.1-152.10" *)
module i2c_master_fsm(clk, rst, start, shift_done, ack, error, start_cmd, load, shift, check_ack, stop_cmd, busy, done);
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _00_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _01_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _02_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _03_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _04_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _05_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire [2:0] _06_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [2:0] _18_;
  wire [2:0] _19_;
  wire [2:0] _20_;
  wire _21_;
  wire [2:0] _22_;
  wire _23_;
  wire _24_;
  (* src = "RTL/i2c_master_fsm.v:7.12-7.15" *)
  input ack;
  wire ack;
  (* src = "RTL/i2c_master_fsm.v:15.12-15.16" *)
  output busy;
  reg busy;
  (* src = "RTL/i2c_master_fsm.v:13.12-13.21" *)
  output check_ack;
  reg check_ack;
  (* src = "RTL/i2c_master_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_master_fsm.v:16.12-16.16" *)
  output done;
  reg done;
  (* src = "RTL/i2c_master_fsm.v:8.12-8.17" *)
  input error;
  wire error;
  (* src = "RTL/i2c_master_fsm.v:11.12-11.16" *)
  output load;
  reg load;
  (* src = "RTL/i2c_master_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_master_fsm.v:12.12-12.17" *)
  output shift;
  reg shift;
  (* src = "RTL/i2c_master_fsm.v:6.12-6.22" *)
  input shift_done;
  wire shift_done;
  (* src = "RTL/i2c_master_fsm.v:5.12-5.17" *)
  input start;
  wire start;
  (* src = "RTL/i2c_master_fsm.v:10.12-10.21" *)
  output start_cmd;
  reg start_cmd;
  (* src = "RTL/i2c_master_fsm.v:28.11-28.16" *)
  reg [2:0] state;
  (* src = "RTL/i2c_master_fsm.v:14.12-14.20" *)
  output stop_cmd;
  reg stop_cmd;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_08_) busy <= _00_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_12_) state <= _06_;
  assign _08_ = | { _23_, _21_ };
  assign _09_ = { _23_, start } != 2'h2;
  assign _10_ = { _14_, shift_done } != 2'h2;
  assign _11_ = { _13_, error, ack } != 3'h4;
  assign _12_ = & { _10_, _09_, _11_ };
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_cmd <= 1'h0;
    else start_cmd <= _05_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load <= 1'h0;
    else load <= _03_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift <= 1'h0;
    else shift <= _04_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) check_ack <= 1'h0;
    else check_ack <= _01_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) stop_cmd <= 1'h0;
    else stop_cmd <= _07_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _02_;
  assign _01_ = _13_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _04_ = _14_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _03_ = _15_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _02_ = _21_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _05_ = _16_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  function [2:0] _43_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _43_ = b[2:0];
      6'b????1?:
        _43_ = b[5:3];
      6'b???1??:
        _43_ = b[8:6];
      6'b??1???:
        _43_ = b[11:9];
      6'b?1????:
        _43_ = b[14:12];
      6'b1?????:
        _43_ = b[17:15];
      default:
        _43_ = a;
    endcase
  endfunction
  assign _06_ = _43_(3'h0, { _22_, 6'h13, _20_, _19_, 3'h6 }, { _23_, _16_, _15_, _14_, _13_, _17_ });
  assign _17_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h5;
  assign _18_ = error ? (* src = "RTL/i2c_master_fsm.v:115.21-115.26|RTL/i2c_master_fsm.v:115.18-117.33" *) 3'h5 : 3'hx;
  assign _19_ = ack ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:111.16-111.19|RTL/i2c_master_fsm.v:111.13-117.33" *) 3'h5 : _18_;
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h4;
  assign _20_ = shift_done ? (* src = "RTL/i2c_master_fsm.v:100.16-100.26|RTL/i2c_master_fsm.v:100.13-102.32" *) 3'h4 : 3'hx;
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h3;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h2;
  assign _16_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h1;
  assign _22_ = start ? (* src = "RTL/i2c_master_fsm.v:68.16-68.21|RTL/i2c_master_fsm.v:68.13-74.16" *) 3'h1 : 3'hx;
  function [0:0] _53_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _53_ = b[0:0];
      2'b1?:
        _53_ = b[1:1];
      default:
        _53_ = a;
    endcase
  endfunction
  assign _00_ = _53_(1'hx, { _24_, 1'h0 }, { _23_, _21_ });
  assign _21_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h6;
  assign _24_ = start ? (* src = "RTL/i2c_master_fsm.v:68.16-68.21|RTL/i2c_master_fsm.v:68.13-74.16" *) 1'h1 : 1'h0;
  assign _23_ = ! (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) state;
  assign _07_ = _17_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
endmodule
