/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/i2c_ack_detector.v:1.1-55.10" *)
module i2c_ack_detector(clk, rst, check_ack, sda, ack, error);
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  wire _0_;
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "RTL/i2c_ack_detector.v:8.12-8.15" *)
  output ack;
  reg ack;
  (* src = "RTL/i2c_ack_detector.v:5.12-5.21" *)
  input check_ack;
  wire check_ack;
  (* src = "RTL/i2c_ack_detector.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_ack_detector.v:9.12-9.17" *)
  output error;
  reg error;
  (* src = "RTL/i2c_ack_detector.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_ack_detector.v:6.12-6.15" *)
  input sda;
  wire sda;
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) ack <= 1'h0;
    else ack <= _0_;
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) error <= 1'h0;
    else error <= _1_;
  assign _0_ = check_ack ? (* src = "RTL/i2c_ack_detector.v:33.12-33.21|RTL/i2c_ack_detector.v:33.9-51.12" *) _3_ : 1'h0;
  assign _2_ = sda ? (* full_case = 32'd1 *) (* src = "RTL/i2c_ack_detector.v:37.16-37.27|RTL/i2c_ack_detector.v:37.13-49.16" *) 1'h1 : 1'h0;
  assign _1_ = check_ack ? (* src = "RTL/i2c_ack_detector.v:33.12-33.21|RTL/i2c_ack_detector.v:33.9-51.12" *) _2_ : 1'h0;
  assign _3_ = sda ? (* full_case = 32'd1 *) (* src = "RTL/i2c_ack_detector.v:37.16-37.27|RTL/i2c_ack_detector.v:37.13-49.16" *) 1'h0 : 1'h1;
endmodule
