/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/i2c_shift_register.v:1.1-92.10" *)
module i2c_shift_register(clk, rst, load, shift, tx_data, sda_in, sda_out, rx_data, done);
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire [3:0] _00_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire _01_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire [7:0] _02_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire [7:0] _03_;
  (* src = "RTL/i2c_shift_register.v:84.30-84.46" *)
  wire [3:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "RTL/i2c_shift_register.v:71.16-71.41" *)
  wire _08_;
  wire [3:0] _09_;
  wire [3:0] _10_;
  wire [7:0] _11_;
  wire [7:0] _12_;
  wire _13_;
  wire _14_;
  (* src = "RTL/i2c_shift_register.v:24.11-24.20" *)
  reg [3:0] bit_count;
  (* src = "RTL/i2c_shift_register.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_shift_register.v:18.12-18.16" *)
  output done;
  reg done;
  (* src = "RTL/i2c_shift_register.v:11.12-11.16" *)
  input load;
  wire load;
  (* src = "RTL/i2c_shift_register.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_shift_register.v:17.29-17.36" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/i2c_shift_register.v:23.22-23.30" *)
  (* unused_bits = "7" *)
  reg [7:0] rx_shift;
  (* src = "RTL/i2c_shift_register.v:14.12-14.18" *)
  input sda_in;
  wire sda_in;
  (* src = "RTL/i2c_shift_register.v:16.13-16.20" *)
  output sda_out;
  wire sda_out;
  (* src = "RTL/i2c_shift_register.v:12.12-12.17" *)
  input shift;
  wire shift;
  (* src = "RTL/i2c_shift_register.v:13.29-13.36" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "RTL/i2c_shift_register.v:22.22-22.30" *)
  reg [7:0] tx_shift;
  assign _04_ = bit_count + (* src = "RTL/i2c_shift_register.v:84.30-84.46" *) 1'h1;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_06_) rx_data <= { rx_shift[6:0], sda_in };
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) tx_shift <= 8'h00;
    else if (_05_) tx_shift <= _03_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_shift <= 8'h00;
    else if (_05_) rx_shift <= _02_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 4'h0;
    else if (_05_) bit_count <= _00_;
  assign _05_ = | { shift, load };
  assign _07_ = ~ load;
  assign _06_ = & { _07_, _08_, shift };
  assign _08_ = bit_count == (* src = "RTL/i2c_shift_register.v:71.16-71.41" *) 4'h7;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) 1'h0 : _14_;
  assign _09_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:71.16-71.41|RTL/i2c_shift_register.v:71.13-86.16" *) 4'h0 : _04_;
  assign _10_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) _09_ : 4'hx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) 4'h0 : _10_;
  assign _11_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) { rx_shift[6:0], sda_in } : 8'hxx;
  assign _02_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) 8'h00 : _11_;
  assign _12_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) { tx_shift[6:0], 1'h0 } : 8'hxx;
  assign _03_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) tx_data : _12_;
  assign _13_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:71.16-71.41|RTL/i2c_shift_register.v:71.13-86.16" *) 1'h1 : 1'h0;
  assign _14_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) _13_ : 1'h0;
  assign sda_out = tx_shift[7];
endmodule
