/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* hdlname = "\\i2c_clock_generator" *)
(* src = "RTL/i2c_clock_generator.v:1.1-49.10" *)
module \$paramod\i2c_clock_generator\DIVIDER=s32'00000000000000000000000000000100 (clk, rst, scl);
  (* src = "RTL/i2c_clock_generator.v:19.1-48.4" *)
  wire [15:0] _0_;
  (* src = "RTL/i2c_clock_generator.v:44.24-44.38" *)
  wire [15:0] _1_;
  (* src = "RTL/i2c_clock_generator.v:33.12-33.32" *)
  wire _2_;
  (* src = "RTL/i2c_clock_generator.v:37.20-37.24" *)
  wire _3_;
  (* src = "RTL/i2c_clock_generator.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_clock_generator.v:16.12-16.19" *)
  reg [15:0] counter;
  (* src = "RTL/i2c_clock_generator.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_clock_generator.v:12.12-12.15" *)
  output scl;
  reg scl;
  assign _1_ = counter + (* src = "RTL/i2c_clock_generator.v:44.24-44.38" *) 1'h1;
  (* src = "RTL/i2c_clock_generator.v:19.1-48.4" *)
  always @(posedge clk, posedge rst)
    if (rst) scl <= 1'h1;
    else if (_2_) scl <= _3_;
  assign _2_ = counter == (* src = "RTL/i2c_clock_generator.v:33.12-33.32" *) 16'h0003;
  assign _3_ = ~ (* src = "RTL/i2c_clock_generator.v:37.20-37.24" *) scl;
  (* src = "RTL/i2c_clock_generator.v:19.1-48.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 16'h0000;
    else counter <= _0_;
  assign _0_ = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_clock_generator.v:33.12-33.32|RTL/i2c_clock_generator.v:33.9-45.12" *) 16'h0000 : _1_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\i2c_shift_register" *)
(* src = "RTL/i2c_shift_register.v:1.1-92.10" *)
module \$paramod\i2c_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000 (clk, rst, load, shift, tx_data, sda_in, sda_out, rx_data, done);
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire [3:0] _00_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire _01_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire [7:0] _02_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  wire [7:0] _03_;
  (* src = "RTL/i2c_shift_register.v:84.30-84.46" *)
  wire [3:0] _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "RTL/i2c_shift_register.v:71.16-71.41" *)
  wire _08_;
  wire [3:0] _09_;
  wire [3:0] _10_;
  wire [7:0] _11_;
  wire [7:0] _12_;
  wire _13_;
  wire _14_;
  (* src = "RTL/i2c_shift_register.v:24.11-24.20" *)
  reg [3:0] bit_count;
  (* src = "RTL/i2c_shift_register.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_shift_register.v:18.12-18.16" *)
  output done;
  reg done;
  (* src = "RTL/i2c_shift_register.v:11.12-11.16" *)
  input load;
  wire load;
  (* src = "RTL/i2c_shift_register.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_shift_register.v:17.29-17.36" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "RTL/i2c_shift_register.v:23.22-23.30" *)
  (* unused_bits = "7" *)
  reg [7:0] rx_shift;
  (* src = "RTL/i2c_shift_register.v:14.12-14.18" *)
  input sda_in;
  wire sda_in;
  (* src = "RTL/i2c_shift_register.v:16.13-16.20" *)
  output sda_out;
  wire sda_out;
  (* src = "RTL/i2c_shift_register.v:12.12-12.17" *)
  input shift;
  wire shift;
  (* src = "RTL/i2c_shift_register.v:13.29-13.36" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "RTL/i2c_shift_register.v:22.22-22.30" *)
  reg [7:0] tx_shift;
  assign _04_ = bit_count + (* src = "RTL/i2c_shift_register.v:84.30-84.46" *) 1'h1;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_data <= 8'h00;
    else if (_06_) rx_data <= { rx_shift[6:0], sda_in };
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) tx_shift <= 8'h00;
    else if (_05_) tx_shift <= _03_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) rx_shift <= 8'h00;
    else if (_05_) rx_shift <= _02_;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_count <= 4'h0;
    else if (_05_) bit_count <= _00_;
  assign _05_ = | { shift, load };
  assign _07_ = ~ load;
  assign _06_ = & { _07_, _08_, shift };
  assign _08_ = bit_count == (* src = "RTL/i2c_shift_register.v:71.16-71.41" *) 4'h7;
  (* src = "RTL/i2c_shift_register.v:30.1-91.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _01_;
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) 1'h0 : _14_;
  assign _09_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:71.16-71.41|RTL/i2c_shift_register.v:71.13-86.16" *) 4'h0 : _04_;
  assign _10_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) _09_ : 4'hx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) 4'h0 : _10_;
  assign _11_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) { rx_shift[6:0], sda_in } : 8'hxx;
  assign _02_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) 8'h00 : _11_;
  assign _12_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) { tx_shift[6:0], 1'h0 } : 8'hxx;
  assign _03_ = load ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:54.12-54.16|RTL/i2c_shift_register.v:54.9-88.12" *) tx_data : _12_;
  assign _13_ = _08_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_shift_register.v:71.16-71.41|RTL/i2c_shift_register.v:71.13-86.16" *) 1'h1 : 1'h0;
  assign _14_ = shift ? (* src = "RTL/i2c_shift_register.v:64.17-64.22|RTL/i2c_shift_register.v:64.14-88.12" *) _13_ : 1'h0;
  assign sda_out = tx_shift[7];
endmodule

(* src = "RTL/i2c_ack_detector.v:1.1-55.10" *)
module i2c_ack_detector(clk, rst, check_ack, sda, ack, error);
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  wire _0_;
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "RTL/i2c_ack_detector.v:8.12-8.15" *)
  output ack;
  reg ack;
  (* src = "RTL/i2c_ack_detector.v:5.12-5.21" *)
  input check_ack;
  wire check_ack;
  (* src = "RTL/i2c_ack_detector.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_ack_detector.v:9.12-9.17" *)
  output error;
  reg error;
  (* src = "RTL/i2c_ack_detector.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_ack_detector.v:6.12-6.15" *)
  input sda;
  wire sda;
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) ack <= 1'h0;
    else ack <= _0_;
  (* src = "RTL/i2c_ack_detector.v:13.1-54.4" *)
  always @(posedge clk, posedge rst)
    if (rst) error <= 1'h0;
    else error <= _1_;
  assign _2_ = sda ? (* full_case = 32'd1 *) (* src = "RTL/i2c_ack_detector.v:37.16-37.27|RTL/i2c_ack_detector.v:37.13-49.16" *) 1'h1 : 1'h0;
  assign _1_ = check_ack ? (* src = "RTL/i2c_ack_detector.v:33.12-33.21|RTL/i2c_ack_detector.v:33.9-51.12" *) _2_ : 1'h0;
  assign _3_ = sda ? (* full_case = 32'd1 *) (* src = "RTL/i2c_ack_detector.v:37.16-37.27|RTL/i2c_ack_detector.v:37.13-49.16" *) 1'h0 : 1'h1;
  assign _0_ = check_ack ? (* src = "RTL/i2c_ack_detector.v:33.12-33.21|RTL/i2c_ack_detector.v:33.9-51.12" *) _3_ : 1'h0;
endmodule

(* src = "RTL/i2c_master_fsm.v:1.1-152.10" *)
module i2c_master_fsm(clk, rst, start, shift_done, ack, error, start_cmd, load, shift, check_ack, stop_cmd, busy, done);
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _00_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _01_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _02_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _03_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _04_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _05_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire [2:0] _06_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire [2:0] _19_;
  wire [2:0] _20_;
  wire [2:0] _21_;
  wire [2:0] _22_;
  wire _23_;
  wire _24_;
  (* src = "RTL/i2c_master_fsm.v:7.12-7.15" *)
  input ack;
  wire ack;
  (* src = "RTL/i2c_master_fsm.v:15.12-15.16" *)
  output busy;
  reg busy;
  (* src = "RTL/i2c_master_fsm.v:13.12-13.21" *)
  output check_ack;
  reg check_ack;
  (* src = "RTL/i2c_master_fsm.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_master_fsm.v:16.12-16.16" *)
  output done;
  reg done;
  (* src = "RTL/i2c_master_fsm.v:8.12-8.17" *)
  input error;
  wire error;
  (* src = "RTL/i2c_master_fsm.v:11.12-11.16" *)
  output load;
  reg load;
  (* src = "RTL/i2c_master_fsm.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_master_fsm.v:12.12-12.17" *)
  output shift;
  reg shift;
  (* src = "RTL/i2c_master_fsm.v:6.12-6.22" *)
  input shift_done;
  wire shift_done;
  (* src = "RTL/i2c_master_fsm.v:5.12-5.17" *)
  input start;
  wire start;
  (* src = "RTL/i2c_master_fsm.v:10.12-10.21" *)
  output start_cmd;
  reg start_cmd;
  (* src = "RTL/i2c_master_fsm.v:28.11-28.16" *)
  reg [2:0] state;
  (* src = "RTL/i2c_master_fsm.v:14.12-14.20" *)
  output stop_cmd;
  reg stop_cmd;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else if (_08_) busy <= _00_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 3'h0;
    else if (_12_) state <= _06_;
  assign _08_ = | { _23_, _13_ };
  assign _09_ = { _15_, error, ack } != 3'h4;
  assign _10_ = { _23_, start } != 2'h2;
  assign _11_ = { _16_, shift_done } != 2'h2;
  assign _12_ = & { _09_, _11_, _10_ };
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) check_ack <= 1'h0;
    else check_ack <= _01_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) start_cmd <= 1'h0;
    else start_cmd <= _05_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) load <= 1'h0;
    else load <= _03_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) shift <= 1'h0;
    else shift <= _04_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) stop_cmd <= 1'h0;
    else stop_cmd <= _07_;
  (* src = "RTL/i2c_master_fsm.v:30.1-151.4" *)
  always @(posedge clk, posedge rst)
    if (rst) done <= 1'h0;
    else done <= _02_;
  assign _02_ = _13_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _07_ = _14_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _01_ = _15_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _04_ = _16_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _03_ = _17_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  assign _05_ = _18_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 1'h1 : 1'h0;
  function [2:0] _44_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _44_ = b[2:0];
      6'b????1?:
        _44_ = b[5:3];
      6'b???1??:
        _44_ = b[8:6];
      6'b??1???:
        _44_ = b[11:9];
      6'b?1????:
        _44_ = b[14:12];
      6'b1?????:
        _44_ = b[17:15];
      default:
        _44_ = a;
    endcase
  endfunction
  assign _06_ = _44_(3'h0, { _22_, 6'h13, _21_, _20_, 3'h6 }, { _23_, _18_, _17_, _16_, _15_, _14_ });
  assign _14_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h5;
  assign _19_ = error ? (* src = "RTL/i2c_master_fsm.v:115.21-115.26|RTL/i2c_master_fsm.v:115.18-117.33" *) 3'h5 : 3'hx;
  assign _20_ = ack ? (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:111.16-111.19|RTL/i2c_master_fsm.v:111.13-117.33" *) 3'h5 : _19_;
  assign _15_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h4;
  assign _21_ = shift_done ? (* src = "RTL/i2c_master_fsm.v:100.16-100.26|RTL/i2c_master_fsm.v:100.13-102.32" *) 3'h4 : 3'hx;
  assign _16_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h3;
  assign _17_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h2;
  assign _18_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h1;
  assign _22_ = start ? (* src = "RTL/i2c_master_fsm.v:68.16-68.21|RTL/i2c_master_fsm.v:68.13-74.16" *) 3'h1 : 3'hx;
  function [0:0] _54_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _54_ = b[0:0];
      2'b1?:
        _54_ = b[1:1];
      default:
        _54_ = a;
    endcase
  endfunction
  assign _00_ = _54_(1'hx, { _24_, 1'h0 }, { _23_, _13_ });
  assign _13_ = state == (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) 3'h6;
  assign _24_ = start ? (* src = "RTL/i2c_master_fsm.v:68.16-68.21|RTL/i2c_master_fsm.v:68.13-74.16" *) 1'h1 : 1'h0;
  assign _23_ = ! (* full_case = 32'd1 *) (* src = "RTL/i2c_master_fsm.v:0.0-0.0|RTL/i2c_master_fsm.v:61.9-148.16" *) state;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "RTL/i2c_master_top.v:1.1-131.10" *)
module i2c_master_top(clk, rst, start, tx_data, sda_in, scl, sda_out, busy, done, ack_error, rx_data);
  (* src = "RTL/i2c_master_top.v:128.10-128.31" *)
  wire _0_;
  (* src = "RTL/i2c_master_top.v:31.6-31.9" *)
  wire ack;
  (* src = "RTL/i2c_master_top.v:19.13-19.22" *)
  output ack_error;
  wire ack_error;
  (* src = "RTL/i2c_master_top.v:17.13-17.17" *)
  output busy;
  wire busy;
  (* src = "RTL/i2c_master_top.v:29.6-29.15" *)
  wire check_ack;
  (* src = "RTL/i2c_master_top.v:9.12-9.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_master_top.v:18.13-18.17" *)
  output done;
  wire done;
  (* src = "RTL/i2c_master_top.v:27.6-27.10" *)
  wire load;
  (* src = "RTL/i2c_master_top.v:10.12-10.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_master_top.v:20.30-20.37" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "RTL/i2c_master_top.v:15.13-15.16" *)
  output scl;
  wire scl;
  (* src = "RTL/i2c_master_top.v:13.12-13.18" *)
  input sda_in;
  wire sda_in;
  (* src = "RTL/i2c_master_top.v:16.13-16.20" *)
  output sda_out;
  wire sda_out;
  (* src = "RTL/i2c_master_top.v:68.6-68.15" *)
  wire sda_shift;
  (* src = "RTL/i2c_master_top.v:51.6-51.19" *)
  wire sda_startstop;
  (* src = "RTL/i2c_master_top.v:28.6-28.11" *)
  wire shift;
  (* src = "RTL/i2c_master_top.v:30.6-30.16" *)
  wire shift_done;
  (* src = "RTL/i2c_master_top.v:11.12-11.17" *)
  input start;
  wire start;
  (* src = "RTL/i2c_master_top.v:32.6-32.16" *)
  (* unused_bits = "0" *)
  wire start_busy;
  (* src = "RTL/i2c_master_top.v:25.6-25.15" *)
  wire start_cmd;
  (* src = "RTL/i2c_master_top.v:26.6-26.14" *)
  wire stop_cmd;
  (* src = "RTL/i2c_master_top.v:12.29-12.36" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  assign _0_ = start_cmd || (* src = "RTL/i2c_master_top.v:128.10-128.31" *) stop_cmd;
  assign sda_out = _0_ ? (* src = "RTL/i2c_master_top.v:128.9-129.44" *) sda_startstop : sda_shift;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/i2c_master_top.v:93.1-102.2" *)
  i2c_ack_detector ack_inst (
    .ack(ack),
    .check_ack(check_ack),
    .clk(clk),
    .error(ack_error),
    .rst(rst),
    .sda(sda_in)
  );
  (* src = "RTL/i2c_master_top.v:41.1-48.2" *)
  \$paramod\i2c_clock_generator\DIVIDER=s32'00000000000000000000000000000100  clock_inst (
    .clk(clk),
    .rst(rst),
    .scl(scl)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/i2c_master_top.v:106.1-124.2" *)
  i2c_master_fsm fsm_inst (
    .ack(ack),
    .busy(busy),
    .check_ack(check_ack),
    .clk(clk),
    .done(done),
    .error(ack_error),
    .load(load),
    .rst(rst),
    .shift(shift),
    .shift_done(shift_done),
    .start(start),
    .start_cmd(start_cmd),
    .stop_cmd(stop_cmd)
  );
  (* src = "RTL/i2c_master_top.v:76.1-89.2" *)
  \$paramod\i2c_shift_register\DATA_WIDTH=s32'00000000000000000000000000001000  shift_inst (
    .clk(clk),
    .done(shift_done),
    .load(load),
    .rst(rst),
    .rx_data(rx_data),
    .sda_in(sda_in),
    .sda_out(sda_shift),
    .shift(shift),
    .tx_data(tx_data)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/i2c_master_top.v:54.1-65.2" *)
  i2c_start_stop startstop_inst (
    .busy(start_busy),
    .clk(clk),
    .rst(rst),
    .scl(scl),
    .sda(sda_startstop),
    .start_cmd(start_cmd),
    .stop_cmd(stop_cmd)
  );
endmodule

(* src = "RTL/i2c_start_stop.v:1.1-54.10" *)
module i2c_start_stop(clk, rst, start_cmd, stop_cmd, scl, sda, busy);
  (* src = "RTL/i2c_start_stop.v:14.1-53.4" *)
  wire _00_;
  (* src = "RTL/i2c_start_stop.v:14.1-53.4" *)
  wire _01_;
  wire _02_;
  (* src = "RTL/i2c_start_stop.v:34.12-34.28" *)
  wire _03_;
  (* src = "RTL/i2c_start_stop.v:43.17-43.32" *)
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "RTL/i2c_start_stop.v:10.12-10.16" *)
  output busy;
  reg busy;
  (* src = "RTL/i2c_start_stop.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "RTL/i2c_start_stop.v:4.12-4.15" *)
  input rst;
  wire rst;
  (* src = "RTL/i2c_start_stop.v:7.12-7.15" *)
  input scl;
  wire scl;
  (* src = "RTL/i2c_start_stop.v:9.12-9.15" *)
  output sda;
  reg sda;
  (* src = "RTL/i2c_start_stop.v:5.12-5.21" *)
  input start_cmd;
  wire start_cmd;
  (* src = "RTL/i2c_start_stop.v:6.12-6.20" *)
  input stop_cmd;
  wire stop_cmd;
  (* src = "RTL/i2c_start_stop.v:14.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) sda <= 1'h1;
    else if (_02_) sda <= _01_;
  assign _02_ = | { _04_, _03_ };
  assign _03_ = start_cmd && (* src = "RTL/i2c_start_stop.v:34.12-34.28" *) scl;
  assign _04_ = stop_cmd && (* src = "RTL/i2c_start_stop.v:43.17-43.32" *) scl;
  (* src = "RTL/i2c_start_stop.v:14.1-53.4" *)
  always @(posedge clk, posedge rst)
    if (rst) busy <= 1'h0;
    else busy <= _00_;
  assign _05_ = _04_ ? (* src = "RTL/i2c_start_stop.v:43.17-43.32|RTL/i2c_start_stop.v:43.14-50.12" *) 1'h1 : 1'h0;
  assign _00_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_start_stop.v:34.12-34.28|RTL/i2c_start_stop.v:34.9-50.12" *) 1'h1 : _05_;
  assign _06_ = _04_ ? (* src = "RTL/i2c_start_stop.v:43.17-43.32|RTL/i2c_start_stop.v:43.14-50.12" *) 1'h1 : 1'hx;
  assign _01_ = _03_ ? (* full_case = 32'd1 *) (* src = "RTL/i2c_start_stop.v:34.12-34.28|RTL/i2c_start_stop.v:34.9-50.12" *) 1'h0 : _06_;
endmodule
