/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/pwm_generator.v:1.1-32.10" *)
module pwm_generator(clk, rst, duty, pwm);
  (* src = "RTL/pwm_generator.v:12.1-21.4" *)
  wire [7:0] _0_;
  (* src = "RTL/pwm_generator.v:19.20-19.31" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _1_;
  (* src = "RTL/pwm_generator.v:26.8-26.22" *)
  wire _2_;
  (* src = "RTL/pwm_generator.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/pwm_generator.v:10.11-10.18" *)
  reg [7:0] counter;
  (* src = "RTL/pwm_generator.v:5.17-5.21" *)
  input [7:0] duty;
  wire [7:0] duty;
  (* src = "RTL/pwm_generator.v:7.16-7.19" *)
  output pwm;
  wire pwm;
  (* src = "RTL/pwm_generator.v:4.11-4.14" *)
  input rst;
  wire rst;
  assign { _1_[31:8], _0_ } = counter + (* src = "RTL/pwm_generator.v:19.20-19.31" *) 32'd1;
  assign _2_ = counter < (* src = "RTL/pwm_generator.v:26.8-26.22" *) duty;
  (* src = "RTL/pwm_generator.v:12.1-21.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 8'h00;
    else counter <= _0_;
  assign pwm = _2_ ? (* full_case = 32'd1 *) (* src = "RTL/pwm_generator.v:26.8-26.22|RTL/pwm_generator.v:26.5-29.20" *) 1'h1 : 1'h0;
  assign _1_[7:0] = _0_;
endmodule
