/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/timer.v:1.1-45.10" *)
module timer(clk, rst, enable, period, timeout);
  (* src = "RTL/timer.v:14.1-44.4" *)
  wire _00_;
  (* src = "RTL/timer.v:34.24-34.35" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _01_;
  (* src = "RTL/timer.v:26.12-26.29" *)
  wire _02_;
  wire [7:0] _03_;
  wire _04_;
  (* src = "RTL/timer.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/timer.v:12.11-12.18" *)
  reg [7:0] counter;
  (* src = "RTL/timer.v:5.11-5.17" *)
  input enable;
  wire enable;
  (* src = "RTL/timer.v:6.17-6.23" *)
  input [7:0] period;
  wire [7:0] period;
  (* src = "RTL/timer.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/timer.v:8.16-8.23" *)
  output timeout;
  reg timeout;
  assign _01_ = counter + (* src = "RTL/timer.v:34.24-34.35" *) 32'd1;
  (* src = "RTL/timer.v:14.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) counter <= 8'h00;
    else if (enable) counter <= _03_;
  assign _02_ = counter == (* src = "RTL/timer.v:26.12-26.29" *) period;
  (* src = "RTL/timer.v:14.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) timeout <= 1'h0;
    else timeout <= _00_;
  assign _03_ = _02_ ? (* full_case = 32'd1 *) (* src = "RTL/timer.v:26.12-26.29|RTL/timer.v:26.9-36.12" *) 8'h00 : _01_[7:0];
  assign _04_ = _02_ ? (* full_case = 32'd1 *) (* src = "RTL/timer.v:26.12-26.29|RTL/timer.v:26.9-36.12" *) 1'h1 : 1'h0;
  assign _00_ = enable ? (* full_case = 32'd1 *) (* src = "RTL/timer.v:23.13-23.19|RTL/timer.v:23.10-42.8" *) _04_ : 1'h0;
endmodule
