/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/forwarding_unit.v:1.1-37.10" *)
module forwarding_unit(ex_mem_rd, ex_mem_reg_write, mem_wb_rd, mem_wb_reg_write, id_ex_rs1, id_ex_rs2, forward_a, forward_b);
  (* src = "RTL/forwarding_unit.v:13.1-35.4" *)
  wire [1:0] _00_;
  (* src = "RTL/forwarding_unit.v:13.1-35.4" *)
  wire [1:0] _01_;
  (* src = "RTL/forwarding_unit.v:21.10-21.32" *)
  wire _02_;
  (* src = "RTL/forwarding_unit.v:25.15-25.37" *)
  wire _03_;
  (* src = "RTL/forwarding_unit.v:29.10-29.32" *)
  wire _04_;
  (* src = "RTL/forwarding_unit.v:33.15-33.37" *)
  wire _05_;
  (* src = "RTL/forwarding_unit.v:20.9-20.48" *)
  wire _06_;
  (* src = "RTL/forwarding_unit.v:20.9-21.33" *)
  wire _07_;
  (* src = "RTL/forwarding_unit.v:24.14-24.53" *)
  wire _08_;
  (* src = "RTL/forwarding_unit.v:24.14-25.38" *)
  wire _09_;
  (* src = "RTL/forwarding_unit.v:28.9-29.33" *)
  wire _10_;
  (* src = "RTL/forwarding_unit.v:32.14-33.38" *)
  wire _11_;
  (* src = "RTL/forwarding_unit.v:20.30-20.47" *)
  wire _12_;
  (* src = "RTL/forwarding_unit.v:24.35-24.52" *)
  wire _13_;
  (* src = "RTL/forwarding_unit.v:2.23-2.32" *)
  input [4:0] ex_mem_rd;
  wire [4:0] ex_mem_rd;
  (* src = "RTL/forwarding_unit.v:3.17-3.33" *)
  input ex_mem_reg_write;
  wire ex_mem_reg_write;
  (* src = "RTL/forwarding_unit.v:9.23-9.32" *)
  output [1:0] forward_a;
  wire [1:0] forward_a;
  (* src = "RTL/forwarding_unit.v:10.23-10.32" *)
  output [1:0] forward_b;
  wire [1:0] forward_b;
  (* src = "RTL/forwarding_unit.v:6.23-6.32" *)
  input [4:0] id_ex_rs1;
  wire [4:0] id_ex_rs1;
  (* src = "RTL/forwarding_unit.v:7.23-7.32" *)
  input [4:0] id_ex_rs2;
  wire [4:0] id_ex_rs2;
  (* src = "RTL/forwarding_unit.v:4.23-4.32" *)
  input [4:0] mem_wb_rd;
  wire [4:0] mem_wb_rd;
  (* src = "RTL/forwarding_unit.v:5.17-5.33" *)
  input mem_wb_reg_write;
  wire mem_wb_reg_write;
  assign _02_ = ex_mem_rd == (* src = "RTL/forwarding_unit.v:21.10-21.32" *) id_ex_rs1;
  assign _03_ = mem_wb_rd == (* src = "RTL/forwarding_unit.v:25.15-25.37" *) id_ex_rs1;
  assign _04_ = ex_mem_rd == (* src = "RTL/forwarding_unit.v:29.10-29.32" *) id_ex_rs2;
  assign _05_ = mem_wb_rd == (* src = "RTL/forwarding_unit.v:33.15-33.37" *) id_ex_rs2;
  assign _07_ = _06_ && (* src = "RTL/forwarding_unit.v:20.9-21.33" *) _02_;
  assign _09_ = _08_ && (* src = "RTL/forwarding_unit.v:24.14-25.38" *) _03_;
  assign _06_ = ex_mem_reg_write && (* src = "RTL/forwarding_unit.v:28.9-28.48" *) _12_;
  assign _10_ = _06_ && (* src = "RTL/forwarding_unit.v:28.9-29.33" *) _04_;
  assign _08_ = mem_wb_reg_write && (* src = "RTL/forwarding_unit.v:32.14-32.53" *) _13_;
  assign _11_ = _08_ && (* src = "RTL/forwarding_unit.v:32.14-33.38" *) _05_;
  assign _12_ = | (* src = "RTL/forwarding_unit.v:28.30-28.47" *) ex_mem_rd;
  assign _13_ = | (* src = "RTL/forwarding_unit.v:32.35-32.52" *) mem_wb_rd;
  assign _01_ = _11_ ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_unit.v:32.14-33.38|RTL/forwarding_unit.v:32.10-34.27" *) 2'h1 : 2'h0;
  assign forward_b = _10_ ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_unit.v:28.9-29.33|RTL/forwarding_unit.v:28.5-34.27" *) 2'h2 : _01_;
  assign _00_ = _09_ ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_unit.v:24.14-25.38|RTL/forwarding_unit.v:24.10-26.27" *) 2'h1 : 2'h0;
  assign forward_a = _07_ ? (* full_case = 32'd1 *) (* src = "RTL/forwarding_unit.v:20.9-21.33|RTL/forwarding_unit.v:20.5-26.27" *) 2'h2 : _00_;
endmodule
