/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/dma_address_generator.v:1.1-45.10" *)
module dma_address_generator(clk, rst, load, increment, src_addr_in, dst_addr_in, src_addr, dst_addr);
  (* src = "RTL/dma_address_generator.v:16.1-44.4" *)
  wire [31:0] _00_;
  (* src = "RTL/dma_address_generator.v:16.1-44.4" *)
  wire [31:0] _01_;
  (* src = "RTL/dma_address_generator.v:39.21-39.37" *)
  wire [31:0] _02_;
  (* src = "RTL/dma_address_generator.v:40.21-40.37" *)
  wire [31:0] _03_;
  wire _04_;
  wire [31:0] _05_;
  wire [31:0] _06_;
  (* src = "RTL/dma_address_generator.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/dma_address_generator.v:12.23-12.31" *)
  output [31:0] dst_addr;
  reg [31:0] dst_addr;
  (* src = "RTL/dma_address_generator.v:9.23-9.34" *)
  input [31:0] dst_addr_in;
  wire [31:0] dst_addr_in;
  (* src = "RTL/dma_address_generator.v:7.16-7.25" *)
  input increment;
  wire increment;
  (* src = "RTL/dma_address_generator.v:6.16-6.20" *)
  input load;
  wire load;
  (* src = "RTL/dma_address_generator.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/dma_address_generator.v:11.23-11.31" *)
  output [31:0] src_addr;
  reg [31:0] src_addr;
  (* src = "RTL/dma_address_generator.v:8.23-8.34" *)
  input [31:0] src_addr_in;
  wire [31:0] src_addr_in;
  assign _02_ = src_addr + (* src = "RTL/dma_address_generator.v:39.21-39.37" *) 32'd4;
  assign _03_ = dst_addr + (* src = "RTL/dma_address_generator.v:40.21-40.37" *) 32'd4;
  (* src = "RTL/dma_address_generator.v:16.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) src_addr <= 32'd0;
    else if (_04_) src_addr <= _01_;
  (* src = "RTL/dma_address_generator.v:16.1-44.4" *)
  always @(posedge clk, posedge rst)
    if (rst) dst_addr <= 32'd0;
    else if (_04_) dst_addr <= _00_;
  assign _04_ = | { increment, load };
  assign _01_ = load ? (* full_case = 32'd1 *) (* src = "RTL/dma_address_generator.v:27.13-27.17|RTL/dma_address_generator.v:27.10-42.8" *) src_addr_in : _06_;
  assign _05_ = increment ? (* src = "RTL/dma_address_generator.v:35.13-35.22|RTL/dma_address_generator.v:35.10-42.8" *) _03_ : 32'hxxxxxxxx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/dma_address_generator.v:27.13-27.17|RTL/dma_address_generator.v:27.10-42.8" *) dst_addr_in : _05_;
  assign _06_ = increment ? (* src = "RTL/dma_address_generator.v:35.13-35.22|RTL/dma_address_generator.v:35.10-42.8" *) _02_ : 32'hxxxxxxxx;
endmodule
