/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/dma_transfer_counter.v:1.1-33.10" *)
module dma_transfer_counter(clk, rst, load, decrement, transfer_length, count, transfer_done);
  (* src = "RTL/dma_transfer_counter.v:15.1-28.4" *)
  wire [15:0] _00_;
  wire _01_;
  (* src = "RTL/dma_transfer_counter.v:25.13-25.36" *)
  wire _02_;
  (* src = "RTL/dma_transfer_counter.v:25.26-25.36" *)
  wire _03_;
  wire [15:0] _04_;
  (* src = "RTL/dma_transfer_counter.v:26.18-26.27" *)
  (* unused_bits = "16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _05_;
  (* src = "RTL/dma_transfer_counter.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "RTL/dma_transfer_counter.v:10.23-10.28" *)
  output [15:0] count;
  reg [15:0] count;
  (* src = "RTL/dma_transfer_counter.v:7.16-7.25" *)
  input decrement;
  wire decrement;
  (* src = "RTL/dma_transfer_counter.v:6.16-6.20" *)
  input load;
  wire load;
  (* src = "RTL/dma_transfer_counter.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "RTL/dma_transfer_counter.v:11.17-11.30" *)
  output transfer_done;
  wire transfer_done;
  (* src = "RTL/dma_transfer_counter.v:8.23-8.38" *)
  input [15:0] transfer_length;
  wire [15:0] transfer_length;
  (* src = "RTL/dma_transfer_counter.v:15.1-28.4" *)
  always @(posedge clk, posedge rst)
    if (rst) count <= 16'h0000;
    else if (_01_) count <= _00_;
  assign _01_ = | { _02_, load };
  assign transfer_done = ! (* src = "RTL/dma_transfer_counter.v:31.25-31.35" *) count;
  assign _02_ = decrement && (* src = "RTL/dma_transfer_counter.v:25.13-25.36" *) _03_;
  assign _03_ = | (* src = "RTL/dma_transfer_counter.v:25.26-25.36" *) count;
  assign _04_ = _02_ ? (* src = "RTL/dma_transfer_counter.v:25.13-25.36|RTL/dma_transfer_counter.v:25.10-26.28" *) _05_[15:0] : 16'hxxxx;
  assign _00_ = load ? (* full_case = 32'd1 *) (* src = "RTL/dma_transfer_counter.v:21.13-21.17|RTL/dma_transfer_counter.v:21.10-26.28" *) transfer_length : _04_;
  assign _05_ = count - (* src = "RTL/dma_transfer_counter.v:26.18-26.27" *) 32'd1;
endmodule
