/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "RTL/vending_machine_fsm.v:1.1-55.10" *)
module vending_machine_fsm(clk, rst, coin_5, coin_10, dispense);
  (* src = "RTL/vending_machine_fsm.v:15.1-46.4" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "RTL/vending_machine_fsm.v:50.8-50.20" *)
  wire _04_;
  (* src = "RTL/vending_machine_fsm.v:34.20-34.37" *)
  wire _05_;
  wire [1:0] _06_;
  wire _07_;
  wire [1:0] _08_;
  wire [1:0] _09_;
  wire _10_;
  (* src = "RTL/vending_machine_fsm.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "RTL/vending_machine_fsm.v:6.11-6.18" *)
  input coin_10;
  wire coin_10;
  (* src = "RTL/vending_machine_fsm.v:5.11-5.17" *)
  input coin_5;
  wire coin_5;
  (* src = "RTL/vending_machine_fsm.v:7.16-7.24" *)
  output dispense;
  wire dispense;
  (* src = "RTL/vending_machine_fsm.v:4.11-4.14" *)
  input rst;
  wire rst;
  (* src = "RTL/vending_machine_fsm.v:13.11-13.16" *)
  reg [1:0] state;
  (* src = "RTL/vending_machine_fsm.v:15.1-46.4" *)
  always @(posedge clk, posedge rst)
    if (rst) state <= 2'h0;
    else if (_03_) state <= _00_;
  assign _01_ = { _10_, coin_10, coin_5 } != 3'h4;
  assign _02_ = { _07_, _05_ } != 2'h2;
  assign _03_ = & { _02_, _01_ };
  assign _04_ = state == (* src = "RTL/vending_machine_fsm.v:50.8-50.20" *) 2'h2;
  assign _05_ = coin_5 || (* src = "RTL/vending_machine_fsm.v:34.20-34.37" *) coin_10;
  assign _06_ = _05_ ? (* src = "RTL/vending_machine_fsm.v:34.20-34.37|RTL/vending_machine_fsm.v:34.17-35.34" *) 2'h2 : 2'hx;
  function [1:0] _18_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "RTL/vending_machine_fsm.v:0.0-0.0|RTL/vending_machine_fsm.v:22.9-44.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _18_ = b[1:0];
      2'b1?:
        _18_ = b[3:2];
      default:
        _18_ = a;
    endcase
  endfunction
  assign _00_ = _18_(2'h0, { _09_, _06_ }, { _10_, _07_ });
  assign _07_ = state == (* full_case = 32'd1 *) (* src = "RTL/vending_machine_fsm.v:0.0-0.0|RTL/vending_machine_fsm.v:22.9-44.16" *) 2'h1;
  assign _08_ = coin_5 ? (* src = "RTL/vending_machine_fsm.v:28.25-28.31|RTL/vending_machine_fsm.v:28.22-29.33" *) 2'h1 : 2'hx;
  assign _09_ = coin_10 ? (* full_case = 32'd1 *) (* src = "RTL/vending_machine_fsm.v:26.20-26.27|RTL/vending_machine_fsm.v:26.17-29.33" *) 2'h2 : _08_;
  assign _10_ = ! (* full_case = 32'd1 *) (* src = "RTL/vending_machine_fsm.v:0.0-0.0|RTL/vending_machine_fsm.v:22.9-44.16" *) state;
  assign dispense = _04_ ? (* full_case = 32'd1 *) (* src = "RTL/vending_machine_fsm.v:50.8-50.20|RTL/vending_machine_fsm.v:50.5-53.25" *) 1'h1 : 1'h0;
endmodule
